//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ABUMediationSlotConfig, NSArray, NSString;

@interface ABUAdLoadConfig : NSObject
{
    NSArray *_mediaSlotConfigs;
    ABUMediationSlotConfig *_slotConfig;
    NSString *_linkID;
    long long _preloadType;
}

- (void).cxx_destruct;
@property(nonatomic) long long preloadType; // @synthesize preloadType=_preloadType;
@property(readonly, copy, nonatomic) NSString *linkID; // @synthesize linkID=_linkID;
@property(retain, nonatomic) ABUMediationSlotConfig *slotConfig; // @synthesize slotConfig=_slotConfig;
@property(copy, nonatomic) NSArray *mediaSlotConfigs; // @synthesize mediaSlotConfigs=_mediaSlotConfigs;
- (void)updateLinkID:(id)arg1;
@property(readonly, nonatomic) _Bool isPreloadCache;
@property(readonly, nonatomic) _Bool isPreload;

@end

