//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ABUAdapterManager : NSObject
{
}

+ (void)setConfigAdapter:(id)arg1 forAdAdapter:(id)arg2;
+ (void)setMediaSlotConfig:(id)arg1 forAdAdapter:(id)arg2;
+ (void)addIsCustomAdapter:(_Bool)arg1 toAdapter:(id)arg2;
+ (void)setBridge:(id)arg1 forAdAdapter:(id)arg2;
+ (id)adAdapterWithMediationSlotConfig:(id)arg1 andMediaSlotConfig:(id)arg2;
+ (void)sendUserConfigRequestToAdapters:(id)arg1;
+ (void)sendPrivacyConfigRequestToAdapters:(id)arg1;
+ (id)customConfigAdapterWithServerKey:(id)arg1;
+ (void)enumerateServerKeyAndAdapterUsingBlock:(CDUnknownBlockType)arg1;
+ (id)setupAdapterWithConfig:(id)arg1 andPrivacyConfig:(id)arg2;
+ (id)didSetupConfigs;

@end

