//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSObject, UIView;
@protocol ABUBaidu_BaiduMobAdNativeAdObject, ABUBaidu_BaiduMobAdVideoViewDelegate;

@protocol ABUBaidu_BaiduMobAdNativeShakeViewDelegate <NSObject>
@property(nonatomic) __weak id <ABUBaidu_BaiduMobAdVideoViewDelegate> delegate;
- (void)nativeShakeViewDismiss:(UIView *)arg1 adObject:(NSObject<ABUBaidu_BaiduMobAdNativeAdObject> *)arg2;
@end

