//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSError, UIViewController;
@protocol ABUCustomFullscreenVideoAdapter;

@protocol ABUCustomFullscreenVideoAdapterBridge <NSObject>

@optional
- (void)rewardedVideoAd:(id <ABUCustomFullscreenVideoAdapter>)arg1 didServerRewardSuccessWithInfo:(void (^)(ABUAdapterRewardAdInfo *))arg2;
- (UIViewController *)viewControllerForPresentingModalView;
- (void)fullscreenVideoAd:(id <ABUCustomFullscreenVideoAdapter>)arg1 renderFailedWithError:(NSError *)arg2;
- (void)fullscreenVideoAdRenderSuccess:(id <ABUCustomFullscreenVideoAdapter>)arg1;
- (void)fullscreenVideoAdDidClickSkip:(id <ABUCustomFullscreenVideoAdapter>)arg1;
- (void)fullscreenVideoAd:(id <ABUCustomFullscreenVideoAdapter>)arg1 didPlayFinishWithError:(NSError *)arg2;
- (void)fullscreenVideoAdWillPresentFullscreenModal:(id <ABUCustomFullscreenVideoAdapter>)arg1;
- (void)fullscreenVideoAdDidClick:(id <ABUCustomFullscreenVideoAdapter>)arg1;
- (void)fullscreenVideoAdDidClose:(id <ABUCustomFullscreenVideoAdapter>)arg1;
- (void)fullscreenVideoAdDidShowFailed:(id <ABUCustomFullscreenVideoAdapter>)arg1 error:(NSError *)arg2;
- (void)fullscreenVideoAdDidVisible:(id <ABUCustomFullscreenVideoAdapter>)arg1;
- (void)fullscreenVideoAdVideoDidLoad:(id <ABUCustomFullscreenVideoAdapter>)arg1;
- (void)fullscreenVideoAd:(id <ABUCustomFullscreenVideoAdapter>)arg1 didLoadFailWithError:(NSError *)arg2 ext:(NSDictionary *)arg3;
- (void)fullscreenVideoAd:(id <ABUCustomFullscreenVideoAdapter>)arg1 didLoadWithExt:(NSDictionary *)arg2;
@end

