//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSError, UIView, UIViewController;
@protocol ABUCustomNativeAdapter;

@protocol ABUCustomNativeAdapterBridge <NSObject>

@optional
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 videoDidPlayFinish:(id)arg2;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 videoDidClick:(id)arg2;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 rewardDidCountDown:(long long)arg2 andNativeAd:(id)arg3;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 videoStateDidChangedWithState:(long long)arg2 andNativeAd:(id)arg3;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 didCloseWithExpressView:(UIView *)arg2 closeReasons:(NSArray *)arg3;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 renderFailWithExpressView:(UIView *)arg2 andError:(NSError *)arg3;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 renderSuccessWithExpressView:(UIView *)arg2;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 didShakeViewDismissWithNativeAd:(id)arg2;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 didDismissFullScreenModalWithMediatedNativeAd:(id)arg2;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 willPresentFullScreenModalWithMediatedNativeAd:(id)arg2;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 didClickWithMediatedNativeAd:(id)arg2;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 didVisibleWithMediatedNativeAd:(id)arg2;
- (UIViewController *)viewControllerForPresentingModalView;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 didLoadFailWithError:(NSError *)arg2;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 didLoadWithExpressViews:(NSArray *)arg2 exts:(NSArray *)arg3;
- (void)nativeAd:(id <ABUCustomNativeAdapter>)arg1 didLoadWithNativeAds:(NSArray *)arg2 exts:(NSArray *)arg3;
@end

