//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUMMediatedNativeAdViewCreator-Protocol.h"

@class NSString, UIButton, UIImageView, UILabel, UIView;
@protocol ABUGDT_GDTUnifiedNativeAdView;

@interface ABUGDTNativeAdViewCreator : NSObject <BUMMediatedNativeAdViewCreator>
{
    UIView<ABUGDT_GDTUnifiedNativeAdView> *_adView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView<ABUGDT_GDTUnifiedNativeAdView> *adView; // @synthesize adView=_adView;
@property(readonly, nonatomic) UIView *adLogoView;
@property(readonly, nonatomic) UIView *mediaView;
- (id)initWithAd:(id)arg1;

// Remaining properties
@property(readonly, nonatomic) UIView *advertiserView;
@property(readonly, nonatomic) UIButton *callToActionBtn;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic) UILabel *descLabel;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) UIButton *dislikeBtn;
@property(readonly, nonatomic) _Bool hasSupportActionBtn;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) UIImageView *iconImageView;
@property(readonly, nonatomic) UIImageView *imageView;
@property(readonly) Class superclass;
@property(readonly, nonatomic) UILabel *titleLabel;

@end

