//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, UIView;
@protocol ABUGDT_GDTUnifiedBannerView;

@protocol ABUGDT_GDTUnifiedBannerViewDelegate <NSObject>

@optional
- (void)unifiedBannerViewWillClose:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
- (void)unifiedBannerViewWillLeaveApplication:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
- (void)unifiedBannerViewDidDismissFullScreenModal:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
- (void)unifiedBannerViewWillDismissFullScreenModal:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
- (void)unifiedBannerViewDidPresentFullScreenModal:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
- (void)unifiedBannerViewWillPresentFullScreenModal:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
- (void)unifiedBannerViewClicked:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
- (void)unifiedBannerViewWillExpose:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
- (void)unifiedBannerViewFailedToLoad:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1 error:(NSError *)arg2;
- (void)unifiedBannerViewDidLoad:(UIView<ABUGDT_GDTUnifiedBannerView> *)arg1;
@end

