//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface ABUInvalidNonServerBiddingResult : NSObject
{
    NSString *_name;
    NSString *_slotID;
    long long _errorCode;
    NSString *_errorMsg;
    NSString *_logSource;
    NSDictionary *_dictValue;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSDictionary *dictValue; // @synthesize dictValue=_dictValue;
@property(readonly, copy, nonatomic) NSString *logSource; // @synthesize logSource=_logSource;
@property(readonly, copy, nonatomic) NSString *errorMsg; // @synthesize errorMsg=_errorMsg;
@property(readonly, nonatomic) long long errorCode; // @synthesize errorCode=_errorCode;
@property(readonly, copy, nonatomic) NSString *slotID; // @synthesize slotID=_slotID;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
- (id)initWithDict:(id)arg1;

@end

