//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class ABUAdapterRewardAdInfo, ABUInterstitialProAd, NSError;

@protocol ABUInterstitialProAdDelegate <NSObject>

@optional
- (void)interstitialProAdServerRewardDidSucceed:(ABUInterstitialProAd *)arg1 rewardInfo:(ABUAdapterRewardAdInfo *)arg2 verify:(_Bool)arg3;
- (void)interstitialProAdWillPresentFullScreenModal:(ABUInterstitialProAd *)arg1;
- (void)interstitialProAdDidClose:(ABUInterstitialProAd *)arg1;
- (void)interstitialProAdDidSkip:(ABUInterstitialProAd *)arg1;
- (void)interstitialProAdDidClick:(ABUInterstitialProAd *)arg1;
- (void)interstitialProAdDidShowFailed:(ABUInterstitialProAd *)arg1 error:(NSError *)arg2;
- (void)interstitialProAdDidVisible:(ABUInterstitialProAd *)arg1;
- (void)interstitialProAdViewRenderFail:(ABUInterstitialProAd *)arg1 error:(NSError *)arg2;
- (void)interstitialProAd:(ABUInterstitialProAd *)arg1 didFailWithError:(NSError *)arg2;
- (void)interstitialProAdDidPlayFinish:(ABUInterstitialProAd *)arg1 didFailWithError:(NSError *)arg2;
- (void)interstitialProAdDidDownLoadVideo:(ABUInterstitialProAd *)arg1;
- (void)interstitialProAdDidLoad:(ABUInterstitialProAd *)arg1;
@end

