//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ABUAdLoader.h"

@interface ABUInterstitialProAdLoader : ABUAdLoader
{
}

- (void)fullscreenVideoAd:(id)arg1 didLoadFailWithError:(id)arg2 ext:(id)arg3;
- (void)fullscreenVideoAd:(id)arg1 didLoadWithExt:(id)arg2;
- (void)interstitialAd:(id)arg1 didLoadFailWithError:(id)arg2 ext:(id)arg3;
- (void)interstitialAd:(id)arg1 didLoadWithExt:(id)arg2;
- (void)loadMediaAdWithAdapter:(id)arg1 mediaSlotConfig:(id)arg2 params:(id)arg3;
- (void)willLoadMediaAdUsingRules:(id)arg1 withMediaSlotConfig:(id)arg2;
- (_Bool)isValidAdapter:(id)arg1 mediaSlotConfig:(id)arg2;

@end

