//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ABUMediaAdLoadID : NSObject
{
    NSString *_groupID;
    NSString *_mediaRitID;
    NSString *_aid;
    NSString *_uniqueID;
}

+ (id)loadIDWithGroupID:(id)arg1 andMediaRitID:(id)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *uniqueID; // @synthesize uniqueID=_uniqueID;
@property(copy, nonatomic) NSString *aid; // @synthesize aid=_aid;
@property(readonly, copy, nonatomic) NSString *mediaRitID; // @synthesize mediaRitID=_mediaRitID;
@property(readonly, copy, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
- (id)initWithGroupID:(id)arg1 andMediaRitID:(id)arg2;

@end

