//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ABUMediaAdProcess : NSObject
{
    _Bool _isMockDownloadCallback;
    _Bool _isShowAgain;
    double _startRequestTimeInterval;
    long long _ritReqType;
}

@property(nonatomic) _Bool isShowAgain; // @synthesize isShowAgain=_isShowAgain;
@property(nonatomic) _Bool isMockDownloadCallback; // @synthesize isMockDownloadCallback=_isMockDownloadCallback;
@property(nonatomic) long long ritReqType; // @synthesize ritReqType=_ritReqType;
@property(nonatomic) double startRequestTimeInterval; // @synthesize startRequestTimeInterval=_startRequestTimeInterval;

@end

