//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ABUSDKCommonConfig : NSObject
{
    int _eventBatchSize;
    long long _eventSendType;
    long long _eventRoutineInterval;
    long long _preFetchCount;
    long long _abTest_ifUseNewSdkinit;
    double _tncInterval;
}

@property(readonly, nonatomic) double tncInterval; // @synthesize tncInterval=_tncInterval;
@property(readonly, nonatomic) long long abTest_ifUseNewSdkinit; // @synthesize abTest_ifUseNewSdkinit=_abTest_ifUseNewSdkinit;
@property(readonly, nonatomic) long long preFetchCount; // @synthesize preFetchCount=_preFetchCount;
@property(readonly, nonatomic) long long eventRoutineInterval; // @synthesize eventRoutineInterval=_eventRoutineInterval;
@property(readonly, nonatomic) long long eventSendType; // @synthesize eventSendType=_eventSendType;
@property(readonly, nonatomic) int eventBatchSize; // @synthesize eventBatchSize=_eventBatchSize;
- (id)initWithDict:(id)arg1;

@end

