//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ABUTimer : NSObject
{
}

+ (void)cancelTimer:(id)arg1;
+ (id)startTimerWithExecAction:(CDUnknownBlockType)arg1 after:(double)arg2 interval:(double)arg3 repeats:(_Bool)arg4 mainThread:(_Bool)arg5;
+ (id)startTimerInMode:(unsigned long long)arg1 execAction:(CDUnknownBlockType)arg2 after:(double)arg3 interval:(double)arg4 repeats:(_Bool)arg5 mainThread:(_Bool)arg6;
+ (void)initialize;

@end

