//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface ABUUserConfig : NSObject <NSCopying>
{
    _Bool _logEnable;
    _Bool _testMode;
    long long _themeStatus;
    NSDictionary *_extraDeviceMap;
    NSString *_advanceSDKConfigPath;
    NSString *_customIDFA;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *customIDFA; // @synthesize customIDFA=_customIDFA;
@property(copy, nonatomic) NSString *advanceSDKConfigPath; // @synthesize advanceSDKConfigPath=_advanceSDKConfigPath;
@property(nonatomic) _Bool testMode; // @synthesize testMode=_testMode;
@property(copy, nonatomic) NSDictionary *extraDeviceMap; // @synthesize extraDeviceMap=_extraDeviceMap;
@property(nonatomic) long long themeStatus; // @synthesize themeStatus=_themeStatus;
@property(nonatomic) _Bool logEnable; // @synthesize logEnable=_logEnable;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

