//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSSecureCoding-Protocol.h"

@interface ABUUserValue : NSObject <NSSecureCoding>
{
    long long _timestamp;
    double _ecpm;
}

+ (_Bool)supportsSecureCoding;
@property(nonatomic) double ecpm; // @synthesize ecpm=_ecpm;
@property(nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

