//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AlibcJSONModel.h"

@class AlibcTradeSDKActionParamModel, NSString;

@interface AlibcTradeSDKActionModel : AlibcJSONModel
{
    NSString *_openType;
    AlibcTradeSDKActionParamModel *_param;
}

- (void).cxx_destruct;
@property(retain, nonatomic) AlibcTradeSDKActionParamModel *param; // @synthesize param=_param;
@property(copy, nonatomic) NSString *openType; // @synthesize openType=_openType;

@end

