//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface ALSLURI : NSObject <NSCopying>
{
    _Bool _useUniversalLinks;
    NSString *_url;
    NSString *_target;
    unsigned long long _degradeType;
    NSString *_degradeH5Url;
    NSString *_backUrl;
    NSString *_module;
    NSDictionary *_extraParam;
    NSString *_bc_fl_src;
}

@property(copy, nonatomic) NSString *bc_fl_src; // @synthesize bc_fl_src=_bc_fl_src;
@property(copy, nonatomic) NSDictionary *extraParam; // @synthesize extraParam=_extraParam;
@property(copy, nonatomic) NSString *module; // @synthesize module=_module;
@property(copy, nonatomic) NSString *backUrl; // @synthesize backUrl=_backUrl;
@property(copy, nonatomic) NSString *degradeH5Url; // @synthesize degradeH5Url=_degradeH5Url;
@property(nonatomic) unsigned long long degradeType; // @synthesize degradeType=_degradeType;
@property(copy, nonatomic) NSString *target; // @synthesize target=_target;
@property(nonatomic) _Bool useUniversalLinks; // @synthesize useUniversalLinks=_useUniversalLinks;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

