//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALSmartLink : NSObject
{
    _Bool _bInit;
}

+ (id)sharedInstance;
- (void)saveToClipBoard:(id)arg1;
- (id)getH5DegradeUrlWithURI:(id)arg1;
- (void)degradeWithURI:(id)arg1 isSmart:(_Bool)arg2 downloadURL:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (_Bool)tryOpenURI:(id)arg1;
- (void)openSmartWithURI:(id)arg1 downloadURL:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)applicationEnterBackground;
- (void)disableSmartOpen:(_Bool)arg1;
- (void)useDeferredLink:(_Bool)arg1;
- (void)setDebugOn:(_Bool)arg1;
- (_Bool)isSmartLinkEnable;
- (void)supportOpenTaobaoWhenTmallNotInstalled:(_Bool)arg1;
- (_Bool)canOpenApp:(id)arg1;
- (void)openURI:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)initWithAppkey:(id)arg1;

@end

