//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITextFieldDelegate-Protocol.h"

@class NSMutableArray, NSString, SAImagePickerManager, UIButton, UIImage, UIImageView, UITextField, UIView;

@interface ApplyAddVUploadInfoViewController : UIViewController <UITextFieldDelegate>
{
    UITextField *_nameField;
    UITextField *_numberField;
    UIImageView *_handdefaultView;
    UIImageView *_handidImageView;
    UIImage *_handImage;
    UIButton *_handCloseBtn;
    UIImageView *_frontidImageView;
    UIImageView *_frontdefaultView;
    UIImage *_frontImage;
    UIButton *_frontCloseBtn;
    double _psoffsety;
    UIView *_psView;
    UIButton *_applyBtn;
    long long _imageType;
    long long _fieldid;
    NSMutableArray *_psArray;
    SAImagePickerManager *_imagePicker;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SAImagePickerManager *imagePicker; // @synthesize imagePicker=_imagePicker;
@property(retain, nonatomic) NSMutableArray *psArray; // @synthesize psArray=_psArray;
@property(retain, nonatomic) UIImage *frontImage; // @synthesize frontImage=_frontImage;
@property(retain, nonatomic) UIImage *handImage; // @synthesize handImage=_handImage;
@property(nonatomic) long long fieldid; // @synthesize fieldid=_fieldid;
- (void)applyEvent;
- (void)refreshSubmitBtn;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldChnaged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)goImagePicker:(long long)arg1;
- (void)chooseIDPicture:(id)arg1;
- (void)addMorePS;
- (void)closeIDImage:(id)arg1;
- (void)closePSImage:(id)arg1;
- (void)refresPSView;
- (void)setupUI;
- (void)tapGesture;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

