//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSString;

@interface AssetAccountModel : NSManagedObject
{
}

+ (id)fetchRequest;
- (id)pcID;

// Remaining properties
@property(copy, nonatomic) NSNumber *aid;
@property(copy, nonatomic) NSString *amount; // @dynamic amount;
@property(copy, nonatomic) NSNumber *bookID; // @dynamic bookID;
@property(copy, nonatomic) NSString *card_number; // @dynamic card_number;
@property(copy, nonatomic) NSNumber *cc_index;
@property(copy, nonatomic) NSNumber *cc_type;
@property(copy, nonatomic) NSString *cid; // @dynamic cid;
@property(copy, nonatomic) NSString *img;
@property(copy, nonatomic) NSNumber *is_cc; // @dynamic is_cc;
@property(copy, nonatomic) NSString *last_dt; // @dynamic last_dt;
@property(copy, nonatomic) NSNumber *minus; // @dynamic minus;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(copy, nonatomic) NSNumber *pid; // @dynamic pid;
@property(copy, nonatomic) NSString *remark; // @dynamic remark;
@property(copy, nonatomic) NSString *rid; // @dynamic rid;
@property(copy, nonatomic) NSString *userID; // @dynamic userID;

@end

