//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface ATAddEditData : NSObject
{
    NSArray *_dataArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *dataArray; // @synthesize dataArray=_dataArray;
- (id)endTimeTextField;
- (id)periodTextField;
- (id)remarkTextField;
- (id)amountTextField;
- (id)beginTimeTextField;
- (id)labelTextField;
- (id)accountTextField;
- (id)typeTextField;
- (id)data7;
- (id)data6;
- (id)data5;
- (id)data4;
- (id)data3;
- (id)data2;
- (id)data1;
- (id)data0;

@end

