//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "BaiduMobAdComponentLottieDelegate-Protocol.h"

@class BaiduMobAdComponentModel, NSString;

@interface BaiduMobAdComponentView : UIView <BaiduMobAdComponentLottieDelegate>
{
    BaiduMobAdComponentModel *_model;
    UIView *_foregroundMaskView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *foregroundMaskView; // @synthesize foregroundMaskView=_foregroundMaskView;
@property(retain, nonatomic) BaiduMobAdComponentModel *model; // @synthesize model=_model;
- (void)nativeComponentLottieSendFinish:(_Bool)arg1 view:(id)arg2 viewName:(id)arg3 special:(id)arg4;
- (void)nativeComponentLottieSendClickView:(id)arg1 viewName:(id)arg2 special:(id)arg3;
- (void)hiddenForegroundView;
- (void)createForegroundView;
- (void)successCreatComponentView:(id)arg1 model:(id)arg2;
- (void)renderComponentViewWithModel:(id)arg1 baseView:(id)arg2;
- (void)creatComponentViewWithModel:(id)arg1 baseView:(id)arg2;
- (void)removeGradientLayer;
- (_Bool)isEnableGradientColor;
- (id)initWithFrame:(struct CGRect)arg1 superView:(id)arg2 model:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

