//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "BaiduMobAdShakeFuncManagerDelegate-Protocol.h"

@class BaiduMobAdShakeFuncManager, NSString, UIImageView, UILabel;

@interface BaiduMobAdSplashShakeView : UIView <BaiduMobAdShakeFuncManagerDelegate>
{
    _Bool _isShakeClickCanBeResponse;
    _Bool _firstClick;
    _Bool _isNeedResetConfig;
    double _intervalTime;
    double _detectionTimes;
    double _velocity;
    double _speed;
    double _shakeAngle;
    double _shakeOptTime;
    double _startupRate;
    double _triggerInterval;
    UIImageView *_shakeImageView;
    UILabel *_noticeLabel;
    UIView *_shadowView;
    CDUnknownBlockType _clickBlock;
    double _scale;
    double _textLabelHeigth;
    double _shakeImageViewSize;
    double _lastTriggerTime;
    BaiduMobAdShakeFuncManager *_shakeManager;
    struct CGRect _originFrame;
}

- (void).cxx_destruct;
@property(retain, nonatomic) BaiduMobAdShakeFuncManager *shakeManager; // @synthesize shakeManager=_shakeManager;
@property(nonatomic) double lastTriggerTime; // @synthesize lastTriggerTime=_lastTriggerTime;
@property(nonatomic) _Bool isNeedResetConfig; // @synthesize isNeedResetConfig=_isNeedResetConfig;
@property(nonatomic) struct CGRect originFrame; // @synthesize originFrame=_originFrame;
@property(nonatomic) _Bool firstClick; // @synthesize firstClick=_firstClick;
@property(nonatomic) double shakeImageViewSize; // @synthesize shakeImageViewSize=_shakeImageViewSize;
@property(nonatomic) double textLabelHeigth; // @synthesize textLabelHeigth=_textLabelHeigth;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
@property(nonatomic) _Bool isShakeClickCanBeResponse; // @synthesize isShakeClickCanBeResponse=_isShakeClickCanBeResponse;
@property(retain, nonatomic) UIView *shadowView; // @synthesize shadowView=_shadowView;
@property(retain, nonatomic) UILabel *noticeLabel; // @synthesize noticeLabel=_noticeLabel;
@property(retain, nonatomic) UIImageView *shakeImageView; // @synthesize shakeImageView=_shakeImageView;
@property(nonatomic) double triggerInterval; // @synthesize triggerInterval=_triggerInterval;
@property(nonatomic) double startupRate; // @synthesize startupRate=_startupRate;
@property(nonatomic) double shakeOptTime; // @synthesize shakeOptTime=_shakeOptTime;
@property(nonatomic) double shakeAngle; // @synthesize shakeAngle=_shakeAngle;
@property(nonatomic) double speed; // @synthesize speed=_speed;
@property(nonatomic) double velocity; // @synthesize velocity=_velocity;
@property(nonatomic) double detectionTimes; // @synthesize detectionTimes=_detectionTimes;
@property(nonatomic) double intervalTime; // @synthesize intervalTime=_intervalTime;
- (void)nativeShakeFuncMotion:(_Bool)arg1;
- (void)dealloc;
- (void)removeShakeView;
- (void)reSize;
- (void)willEnterForeground;
- (void)didEnterBackground;
- (void)stopMotion;
- (void)startMotion;
- (void)clickAdsCompletionBlock:(CDUnknownBlockType)arg1;
- (void)adClick:(id)arg1;
- (void)resetShakeConfig;
- (void)addClickEvent;
- (void)shakeAnimation;
- (void)resizeViewHeight;
- (void)setImageViewSize:(double)arg1;
- (void)setupCardViewShakeViewUI:(struct CGRect)arg1 labelSize:(double)arg2;
- (void)setupUI:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)resizeLabelMarginWithIcon:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1 labelSize:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1 shakeImageSize:(double)arg2 labelScale:(double)arg3 needResetConfig:(_Bool)arg4 autoStart:(_Bool)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

