//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaiduMobAdVideoRenderer.h"

@class BaiduAdVideoTailFrame, BaiduMobAdVideoDLViewController, UIButton, UISlider, UIView;

@interface BaiduMobAdVideoLpRenderer : BaiduMobAdVideoRenderer
{
    _Bool _isPlayEnd;
    _Bool _isLpVideo;
    _Bool _isPlayError;
    _Bool _isSmallVideo;
    BaiduAdVideoTailFrame *_tailFrame;
    BaiduMobAdVideoDLViewController *_baseViewController;
    CDUnknownBlockType _clickCloseVideoBlock;
    UISlider *_progress;
    UIButton *_btnPlayOrPause;
    UIButton *_btnFullScreen;
    UIView *_controlView;
    UIButton *_btnDone;
    UIButton *_btnEndCard;
    UIButton *_closeBtn;
    struct CGRect _fullBtnRect;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(nonatomic) struct CGRect fullBtnRect; // @synthesize fullBtnRect=_fullBtnRect;
@property(retain, nonatomic) UIButton *btnEndCard; // @synthesize btnEndCard=_btnEndCard;
@property(retain, nonatomic) UIButton *btnDone; // @synthesize btnDone=_btnDone;
@property(retain, nonatomic) UIView *controlView; // @synthesize controlView=_controlView;
@property(retain, nonatomic) UIButton *btnFullScreen; // @synthesize btnFullScreen=_btnFullScreen;
@property(retain, nonatomic) UIButton *btnPlayOrPause; // @synthesize btnPlayOrPause=_btnPlayOrPause;
@property(retain, nonatomic) UISlider *progress; // @synthesize progress=_progress;
@property(copy, nonatomic) CDUnknownBlockType clickCloseVideoBlock; // @synthesize clickCloseVideoBlock=_clickCloseVideoBlock;
@property(nonatomic) _Bool isSmallVideo; // @synthesize isSmallVideo=_isSmallVideo;
@property(nonatomic) _Bool isPlayError; // @synthesize isPlayError=_isPlayError;
@property(nonatomic) _Bool isLpVideo; // @synthesize isLpVideo=_isLpVideo;
@property(nonatomic) _Bool isPlayEnd; // @synthesize isPlayEnd=_isPlayEnd;
@property(retain, nonatomic) BaiduMobAdVideoDLViewController *baseViewController; // @synthesize baseViewController=_baseViewController;
@property(retain, nonatomic) BaiduAdVideoTailFrame *tailFrame; // @synthesize tailFrame=_tailFrame;
- (void)dealloc;
- (_Bool)isPlaying;
- (void)playVideo;
- (void)pauseVideo;
- (void)willEnterForeground;
- (void)playClick:(id)arg1;
- (void)tailFrameBtnClick;
- (void)createTailFrame;
- (void)onPlayerItemDidReachEnd:(id)arg1;
- (void)playbackFail:(id)arg1;
- (void)updateValue:(id)arg1;
- (void)onPlayerRateChange;
- (_Bool)newWindowTransform;
- (void)changeOrientation;
- (void)closeVideoWindows;
- (void)clickFullScreen:(id)arg1;
- (void)handleTapGesture:(id)arg1;
- (void)addProgressObserver;
- (void)backClick:(id)arg1;
- (void)buttonAction:(SEL)arg1;
- (void)showErrorView;
- (void)setupUI;
- (void)start;

@end

