//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@class UIViewController;

@interface BaiduMobAdToastView : UILabel
{
    UIViewController *_baseVC;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIViewController *baseVC; // @synthesize baseVC=_baseVC;
- (void)removeToastView;
- (void)reSize;
- (void)showToastView;
- (id)initWithFrame:(struct CGRect)arg1 backgroundColor:(id)arg2 toastText:(id)arg3 textColor:(id)arg4 textSize:(double)arg5 alpha:(double)arg6 cornerRate:(double)arg7;

@end

