//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BaiduMobAdNative, BaiduMobAdNativeAdObject, NSArray, NSNumber, NSString;

@protocol BaiduMobAdNativeAdDelegate <NSObject>

@optional
- (void)nativeAdsFailLoad:(int)arg1 nativeAd:(BaiduMobAdNative *)arg2;
- (void)smartFeedbackSelectedWithObject:(BaiduMobAdNativeAdObject *)arg1;
- (void)nativeAdsFailLoadCode:(NSString *)arg1 message:(NSString *)arg2 nativeAd:(BaiduMobAdNative *)arg3;
- (void)nativeAdObjectsSuccessLoad:(NSArray *)arg1 nativeAd:(BaiduMobAdNative *)arg2;
- (_Bool)enableLocation;
- (NSString *)channelId;
- (NSNumber *)baiduMobAdsWidth;
- (NSNumber *)baiduMobAdsHeight;
- (NSString *)apId;
- (NSString *)publisherId;
@end

