//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

#import "BaiduMobAdComponentDelegate-Protocol.h"
#import "IBaiduMobAdRenderEventDelegate-Protocol.h"

@class BaiduMobAdInstance, BaiduMobAdNativeProfessionalComponent, NSString, UILabel, UIView;
@protocol BaiduMobAdCycleViewCellDelegate;

@interface BaiduMobAdCycleViewCell : UICollectionViewCell <IBaiduMobAdRenderEventDelegate, BaiduMobAdComponentDelegate>
{
    id <BaiduMobAdCycleViewCellDelegate> _delegate;
    BaiduMobAdNativeProfessionalComponent *_componentView;
    UIView *_retainDialog;
    UILabel *_retainDialogRewardLabel;
    BaiduMobAdInstance *_adInstance;
    NSString *_finalJSONString;
    UIView *_skipBtn;
    UILabel *_rewardLabel;
    UIView *_rendererSuperView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *rendererSuperView; // @synthesize rendererSuperView=_rendererSuperView;
@property(retain, nonatomic) UILabel *rewardLabel; // @synthesize rewardLabel=_rewardLabel;
@property(retain, nonatomic) UIView *skipBtn; // @synthesize skipBtn=_skipBtn;
@property(retain, nonatomic) NSString *finalJSONString; // @synthesize finalJSONString=_finalJSONString;
@property(retain, nonatomic) BaiduMobAdInstance *adInstance; // @synthesize adInstance=_adInstance;
@property(retain, nonatomic) UILabel *retainDialogRewardLabel; // @synthesize retainDialogRewardLabel=_retainDialogRewardLabel;
@property(retain, nonatomic) UIView *retainDialog; // @synthesize retainDialog=_retainDialog;
@property(retain, nonatomic) BaiduMobAdNativeProfessionalComponent *componentView; // @synthesize componentView=_componentView;
@property(nonatomic) __weak id <BaiduMobAdCycleViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)stop;
- (void)nativeComponentEvent:(id)arg1 component:(id)arg2;
- (void)nativeComponentClick:(long long)arg1 clickView:(id)arg2 viewName:(id)arg3 special:(id)arg4 component:(id)arg5;
- (void)nativeComponentCreateSuccess:(id)arg1 viewName:(id)arg2 special:(id)arg3 component:(id)arg4;
- (void)render;
- (void)setCellAdInstance:(id)arg1 rendererSuperView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

