//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface BUCloudCommandNetworkUtil : NSObject
{
}

+ (id)_requestBodyWithParams:(id)arg1;
+ (id)_requestUrlWithParams:(id)arg1 baseUrl:(id)arg2;
+ (id)_requestWithUrl:(id)arg1 requestMethod:(id)arg2 requestHeaders:(id)arg3;
+ (void)uploadWithUrl:(id)arg1 data:(id)arg2 requestHeaders:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (void)requestWithUrl:(id)arg1 method:(id)arg2 params:(id)arg3 requestHeaders:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (id)_uploadRequestBodyWithMultiData:(id)arg1 params:(id)arg2 commonParams:(id)arg3;
+ (void)_dealWithResultData:(id)arg1 ran:(id)arg2 error:(id)arg3 url:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
+ (void)uploadMultiDataWithUrl:(id)arg1 dataArray:(id)arg2 params:(id)arg3 commonParams:(id)arg4 requestHeaders:(id)arg5 success:(CDUnknownBlockType)arg6 failure:(CDUnknownBlockType)arg7;
+ (void)uploadDataWithUrl:(id)arg1 fileName:(id)arg2 fileType:(id)arg3 data:(id)arg4 params:(id)arg5 commonParams:(id)arg6 mimeType:(id)arg7 requestHeaders:(id)arg8 success:(CDUnknownBlockType)arg9 failure:(CDUnknownBlockType)arg10;
+ (void)requestWithUrl:(id)arg1 requestMethod:(long long)arg2 params:(id)arg3 requestHeaders:(id)arg4 success:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
+ (void)initialize;

@end

