//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class BUImage, NSString;

@protocol BUMaterialMetaMediationProtocol <NSObject>
@property(readonly, copy, nonatomic) NSString *brandName;
@property(readonly, copy, nonatomic) NSString *advertiser;
@property(readonly, nonatomic) NSString *appPrice;
@property(readonly, nonatomic) double videoAspectRatio;
@property(readonly, nonatomic) BUImage *adLogo;
@end

