//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@class NSArray;
@protocol BURaptorTrackerNetworkOperationDelegate;

@interface BURaptorTrackerNetworkOperation : NSOperation
{
    _Bool _executing;
    _Bool _finished;
    id <BURaptorTrackerNetworkOperationDelegate> _delegate;
    long long _sendIndex;
    NSArray *_modelArray;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *modelArray; // @synthesize modelArray=_modelArray;
@property(nonatomic) long long sendIndex; // @synthesize sendIndex=_sendIndex;
@property(nonatomic) __weak id <BURaptorTrackerNetworkOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isFinished) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic, getter=isExecuting) _Bool executing; // @synthesize executing=_executing;
- (void)safeDelegate_operation:(id)arg1 sendWithModelArray:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (_Bool)isConcurrent;
- (void)start;
- (id)initWithModelArray:(id)arg1;

@end

