//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BURaptorTrackerNetworkOperationDelegate-Protocol.h"

@class NSDate, NSMutableArray, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface BURaptorTracker : NSObject <BURaptorTrackerNetworkOperationDelegate>
{
    NSObject<OS_dispatch_queue> *_databaseSerialQueue;
    long long _failedCount;
    NSDate *_nextAvailableDate;
    NSMutableArray *_waitingArray;
    NSOperationQueue *_networkOperationQueue;
    long long _networkSendIndex;
    NSDate *_lastReportDate;
    NSObject<OS_dispatch_queue> *_logSerialQueue;
    long long _sdkEventIndex;
    long long _sdkEventValidIndex;
}

+ (id)sharedInstance;
+ (void)_pbu_set_sessionId;
+ (void)setupRaptorTrack;
+ (id)sessionId;
- (void).cxx_destruct;
@property(nonatomic) long long sdkEventValidIndex; // @synthesize sdkEventValidIndex=_sdkEventValidIndex;
@property(nonatomic) long long sdkEventIndex; // @synthesize sdkEventIndex=_sdkEventIndex;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *logSerialQueue; // @synthesize logSerialQueue=_logSerialQueue;
@property(retain) NSDate *lastReportDate; // @synthesize lastReportDate=_lastReportDate;
@property(nonatomic) long long networkSendIndex; // @synthesize networkSendIndex=_networkSendIndex;
@property(retain, nonatomic) NSOperationQueue *networkOperationQueue; // @synthesize networkOperationQueue=_networkOperationQueue;
@property(retain, nonatomic) NSMutableArray *waitingArray; // @synthesize waitingArray=_waitingArray;
@property(retain, nonatomic) NSDate *nextAvailableDate; // @synthesize nextAvailableDate=_nextAvailableDate;
@property(nonatomic) long long failedCount; // @synthesize failedCount=_failedCount;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *databaseSerialQueue; // @synthesize databaseSerialQueue=_databaseSerialQueue;
- (id)init;
- (long long)adlog_exception_batch;
- (long long)adlog_interval;
- (long long)adlog_batch;
- (id)sentNotificationName;
- (id)didCleanNotificationName;
- (id)willCleanNotificationName;
- (id)eventKey;
- (Class)raptorModelClass;
- (long long)raptorTrackerType;
- (void)operation:(id)arg1 sendWithModelArray:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)_pbu_inUnknown_sendWithPostDict:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)extraInfoBeforeSend;
- (void)eventDidSendWithModelArray:(id)arg1;
- (void)eventHaveSendResultWithModelArray:(id)arg1;
- (void)eventDidSendFailedWithModelArray:(id)arg1 error:(id)arg2;
- (void)eventDidSendSuccessWithModelArray:(id)arg1 valid:(_Bool)arg2 logid:(id)arg3;
- (void)eventWillSendWithModelArray:(id)arg1;
- (void)eventDidSaveWithModel:(id)arg1;
- (void)eventDidSaveSuccessWithModel:(id)arg1;
- (void)eventDidSaveFailedWithModel:(id)arg1 error:(id)arg2;
- (void)eventWillSaveWithModel:(id)arg1;
- (id)_debugInfoWithModelArray:(id)arg1;
- (void)_logWithMessage:(id)arg1 queueType:(long long)arg2 subType:(long long)arg3;
- (void)applicationWillEnterForegroundNotification:(id)arg1;
- (void)_pbu_st_inMain_postNotificationWithName:(id)arg1 userInfo:(id)arg2;
- (void)_pbu_inDB_handleWithOperation:(id)arg1 request:(id)arg2 modelArray:(id)arg3;
- (void)_pbu_inDB_addSendTaskWithModelArray:(id)arg1 maxBatchCount:(long long)arg2;
- (void)_pbu_inDB_deleteExpiredData;
- (void)_pbu_inDB_updateAllSendingStatusWhenSDKInit;
- (void)_pbu_inDB_updateWithModelArray:(id)arg1 sendingStatus:(_Bool)arg2;
- (void)_pbu_inDB_deleteWithModelArray:(id)arg1;
- (void)_pbu_inDB_maybeSendWhenAppWillEnterForeground;
- (void)_pbu_inDB_maybeSendWhenSDKInit;
- (void)_pbu_inDB_maybeSendWhenSaveSuccessWithModel:(id)arg1;
- (_Bool)_pbu_inDB_checkWhenSaveSuccessWithModelArray:(id)arg1 model:(id)arg2;
- (void)_pbu_inDB_saveData:(id)arg1;
- (void)setup;
- (void)eventData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

