//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BURaptorTrackerModel.h"

@interface BUStatsRaptorTrackerModel : BURaptorTrackerModel
{
}

- (id)Win_LdsWith;
- (id)Carl_YESSelf;
- (id)Rect_TimeBOOL;
- (id)Msg_LineMARK;

@end

