//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"

@class AdjustButton, CBBillDatePicker, DetaiTableView, NSCalendar, NSDateFormatter, NSString, SKCalendarTableViewHeader, SKCalendarView, UIPanGestureRecognizer;

@interface CalendarController : UIViewController <UIScrollViewDelegate>
{
    _Bool _isMoveTop;
    UIPanGestureRecognizer *_panGesture;
    NSString *_currentMonth;
    NSString *_currentDate;
    NSCalendar *_calendar;
    _Bool _showAmount;
    double _rowHeight;
    CBBillDatePicker *_datePicker;
    AdjustButton *_titleBtn;
    SKCalendarView *_calendarView;
    NSDateFormatter *_dateFormatter;
    DetaiTableView *_tableView;
    NSDateFormatter *_dayFormatter;
    SKCalendarTableViewHeader *_showAmountHeaderView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SKCalendarTableViewHeader *showAmountHeaderView; // @synthesize showAmountHeaderView=_showAmountHeaderView;
@property(retain, nonatomic) NSDateFormatter *dayFormatter; // @synthesize dayFormatter=_dayFormatter;
@property(retain, nonatomic) DetaiTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) SKCalendarView *calendarView; // @synthesize calendarView=_calendarView;
@property(retain, nonatomic) AdjustButton *titleBtn; // @synthesize titleBtn=_titleBtn;
@property(retain, nonatomic) CBBillDatePicker *datePicker; // @synthesize datePicker=_datePicker;
- (_Bool)dateForCurrentMonth:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)handleScrollView:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidScroll:(id)arg1;
- (void)adjustCalendView;
- (void)adjustCalendarView;
- (void)titleButtonAciton;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)tallyAction;
- (void)todayAction;
- (void)tallyDataEditNotification:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

