//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BuyMiniBaseViewController.h"

#import "UISearchBarDelegate-Protocol.h"

@class BuyDiallelCollectionView, NSString;

@interface CouponPlatformListController : BuyMiniBaseViewController <UISearchBarDelegate>
{
    BuyDiallelCollectionView *_collectionView;
    long long _platformType;
    NSString *_typeID;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *typeID; // @synthesize typeID=_typeID;
@property(nonatomic) long long platformType; // @synthesize platformType=_platformType;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (void)collectionViewScrollToTopaction;
- (void)lookRule;
- (id)headerView;
- (void)addCollectionView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

