//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class CAShapeLayer, NSString, UILabel, UIView;

@interface CouponMineCell : UITableViewCell
{
    UILabel *_titleLabel;
    UIView *_bgView;
    UIView *_selectedBgView;
    UIView *_selectedCoverView;
    CAShapeLayer *_shapeLayer;
    NSString *_title;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

