//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CSJAdClientBiddingProtocol-Protocol.h"

@class NSNumber, NSString;

@interface CSJAdClientBiddingHandle : NSObject <CSJAdClientBiddingProtocol>
{
    _Bool _isSendWin;
    _Bool _isSendLoss;
    CDUnknownBlockType _getMediaExtBlock;
    NSNumber *_userAuctionPrice;
    NSString *_winUrl;
    NSString *_lossUrl;
    NSString *_serverPrice;
    unsigned long long _biddingType;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long biddingType; // @synthesize biddingType=_biddingType;
@property(copy, nonatomic) NSString *serverPrice; // @synthesize serverPrice=_serverPrice;
@property(copy, nonatomic) NSString *lossUrl; // @synthesize lossUrl=_lossUrl;
@property(copy, nonatomic) NSString *winUrl; // @synthesize winUrl=_winUrl;
@property(copy, nonatomic) NSNumber *userAuctionPrice; // @synthesize userAuctionPrice=_userAuctionPrice;
@property(copy, nonatomic) CDUnknownBlockType getMediaExtBlock; // @synthesize getMediaExtBlock=_getMediaExtBlock;
- (_Bool)p_isClientBidding;
- (void)p_getInfo;
- (id)p_checkUrl:(id)arg1;
- (void)loss:(id)arg1 lossReason:(id)arg2 winBidder:(id)arg3;
- (void)win:(id)arg1;
- (void)setPrice:(id)arg1;
- (id)getAuctionPrice;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

