//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CSJExpressAdMonitor, CSJSDKMonitor, CSJUserMonitor;

@interface CSJAdMonitorManager : NSObject
{
    CSJExpressAdMonitor *_expressAdMonitor;
    CSJUserMonitor *_userMonitor;
    CSJSDKMonitor *_sdkMonitor;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
@property(retain, nonatomic) CSJSDKMonitor *sdkMonitor; // @synthesize sdkMonitor=_sdkMonitor;
@property(retain, nonatomic) CSJUserMonitor *userMonitor; // @synthesize userMonitor=_userMonitor;
@property(retain, nonatomic) CSJExpressAdMonitor *expressAdMonitor; // @synthesize expressAdMonitor=_expressAdMonitor;
- (id)init;

@end

