//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CSJAppStorePreloadItemPendant : NSObject
{
    CDUnknownBlockType _Body_OfApp;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType Body_OfApp; // @synthesize Body_OfApp=_Body_OfApp;
- (void)dealloc;

@end

