//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface CSJByteFinderManager : NSObject
{
    _Bool _ignoreMSDK;
    NSString *_did;
    NSString *_applogDid;
}

+ (id)sdkVersion;
+ (id)host_appid;
+ (void)_signalAction;
+ (void)startAPMWithDid:(id)arg1 ignoreMSDK:(_Bool)arg2 host:(id)arg3;
+ (void)startLogsdkWithDC:(id)arg1 did:(id)arg2 ignoreMSDK:(_Bool)arg3 host:(id)arg4 To_PlayView:(_Bool)arg5;
+ (void)startCrashAndAppLogSDKWithDC:(id)arg1 did:(id)arg2 host:(id)arg3 To_PlayView:(_Bool)arg4;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *applogDid; // @synthesize applogDid=_applogDid;
@property(nonatomic) _Bool ignoreMSDK; // @synthesize ignoreMSDK=_ignoreMSDK;
@property(copy, nonatomic) NSString *did; // @synthesize did=_did;
- (void)setupCrashAndAppLogSDKWithHost:(id)arg1 To_PlayView:(_Bool)arg2;
- (id)init;

@end

