//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CSJDynamicEngine, CSJDynamicView, NSError;

@protocol CSJDynamicEngineDelegate <NSObject>
- (void)endRenderInDynamicEngine:(CSJDynamicEngine *)arg1 error:(NSError *)arg2;
- (void)middleRenderInDynamicEngine:(CSJDynamicEngine *)arg1 dynamicView:(CSJDynamicView *)arg2 error:(NSError *)arg3;
- (void)beginRenderInDynamicEngine:(CSJDynamicEngine *)arg1;
- (void)endParseInDynamicEngine:(CSJDynamicEngine *)arg1 error:(NSError *)arg2;
- (void)beginParseInDynamicEngine:(CSJDynamicEngine *)arg1;
@end

