//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJDynamicAbstractDecorator.h"

@class CSJLOTAnimationView;

@interface CSJDynamicImageLottieDecorator : CSJDynamicAbstractDecorator
{
    CSJLOTAnimationView *_lotAnimationView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJLOTAnimationView *lotAnimationView; // @synthesize lotAnimationView=_lotAnimationView;
- (void)pbu_loadLottieWithItem:(id)arg1;
- (void)render;

@end

