//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CSJNativeAd, NSArray, NSMutableArray;

@interface CSJDislike : NSObject
{
    NSArray *_filterWords;
    CSJNativeAd *_nativeAd;
    NSMutableArray *_IOS_TODOT5;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *IOS_TODOT5; // @synthesize IOS_TODOT5=_IOS_TODOT5;
@property(retain, nonatomic) CSJNativeAd *nativeAd; // @synthesize nativeAd=_nativeAd;
@property(copy, nonatomic) NSArray *filterWords; // @synthesize filterWords=_filterWords;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (void)didSelectedFilterWordWithReason:(id)arg1;
- (id)initWithNativeAd:(id)arg1;

@end

