//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJDynamicInteractionAbstractDecorator.h"

@class CSJDynamicInteractionCombationBottomView, CSJDynamicInteractionMaskView, CSJSplashUpSwipeComponentView;

@interface CSJDynamicInteractionCombinationDecorator : CSJDynamicInteractionAbstractDecorator
{
    CSJDynamicInteractionCombationBottomView *_bottomView;
    CSJSplashUpSwipeComponentView *_slideAnimationView;
    CSJDynamicInteractionMaskView *_maskView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJDynamicInteractionMaskView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) CSJSplashUpSwipeComponentView *slideAnimationView; // @synthesize slideAnimationView=_slideAnimationView;
@property(retain, nonatomic) CSJDynamicInteractionCombationBottomView *bottomView; // @synthesize bottomView=_bottomView;
- (id)p_shakeScence;
- (id)contentView;
- (void)dealloc;
- (void)interactionViewDidShow;
- (void)showSlideAnimationView;
- (void)hiddenInteractionAnimaiton;
- (void)showInteractionAnimation;
- (void)bottomViewAction:(id)arg1;
- (void)render;

@end

