//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextViewDelegate-Protocol.h"

@class NSString, UIButton, UIColor, UILabel, UITextView;

@interface CSJDislikeNewRealInputView : UIView <UITextViewDelegate>
{
    CDUnknownBlockType _cancelBlock;
    CDUnknownBlockType _Push_MsgDic;
    UIView *_Key_It_rhs;
    UIButton *_Objc_NilPtr;
    UILabel *_titleLabel;
    UIButton *_Ad_YouIs;
    UIView *_lineView;
    UITextView *_textView;
    UILabel *_Rit_X2View;
    UILabel *_countLabel;
    UIColor *_Icon_StopIpv4;
    UIColor *_Ads_IDAdm;
    UIColor *__cmd_OutAre;
    UIColor *_BOOL_ThatOnly;
    long long _maxInputLength;
}

- (void).cxx_destruct;
@property(nonatomic) long long maxInputLength; // @synthesize maxInputLength=_maxInputLength;
@property(retain, nonatomic) UIColor *BOOL_ThatOnly; // @synthesize BOOL_ThatOnly=_BOOL_ThatOnly;
@property(retain, nonatomic) UIColor *_cmd_OutAre; // @synthesize _cmd_OutAre=__cmd_OutAre;
@property(retain, nonatomic) UIColor *Ads_IDAdm; // @synthesize Ads_IDAdm=_Ads_IDAdm;
@property(retain, nonatomic) UIColor *Icon_StopIpv4; // @synthesize Icon_StopIpv4=_Icon_StopIpv4;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UILabel *Rit_X2View; // @synthesize Rit_X2View=_Rit_X2View;
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIButton *Ad_YouIs; // @synthesize Ad_YouIs=_Ad_YouIs;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *Objc_NilPtr; // @synthesize Objc_NilPtr=_Objc_NilPtr;
@property(retain, nonatomic) UIView *Key_It_rhs; // @synthesize Key_It_rhs=_Key_It_rhs;
@property(copy, nonatomic) CDUnknownBlockType Push_MsgDic; // @synthesize Push_MsgDic=_Push_MsgDic;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
- (id)CCPA_VliApp:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)submitButtonTouchUpInside:(id)arg1;
- (void)cancelButtonTouchUpInside:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

