//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJDynamicInteractionAbstractDecorator.h"

@class CSJDynamicInteractionUnlockView;

@interface CSJDynamicInteractionUnlockDecorator : CSJDynamicInteractionAbstractDecorator
{
    CSJDynamicInteractionUnlockView *_unlockView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJDynamicInteractionUnlockView *unlockView; // @synthesize unlockView=_unlockView;
- (void)showInteractionAnimation;
- (void)interactionViewDidShow;
- (void)render;

@end

