//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJDynamicInteractionAbstractDecorator.h"

@class CSJSplashShakeComponentView;

@interface CSJDynamicInteractionShake2_3Decorator : CSJDynamicInteractionAbstractDecorator
{
    CSJSplashShakeComponentView *_shakeAnimationMask;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJSplashShakeComponentView *shakeAnimationMask; // @synthesize shakeAnimationMask=_shakeAnimationMask;
- (void)interactionGestureAction:(id)arg1;
- (void)interactionViewDidShow;
- (void)showShakeAnimation;
- (void)hiddenInteractionAnimaiton;
- (void)showInteractionAnimation;
- (void)render;

@end

