//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJDynamicRenderStrategy.h"

#import "BUPlayableAdDelegate-Protocol.h"
#import "BUWebViewDelegate-Protocol.h"
#import "CSJWKWebViewClientInterceptionDelegate-Protocol.h"
#import "CSJWebViewDynamicRenderInterface-Protocol.h"

@class BUPlayableAd, BUTimer, CSJWKWebViewClient, CSJWebViewOwner, NSDictionary, NSMutableDictionary, NSString, UIView;
@protocol CSJWebViewDynamicRenderDelegate;

@interface CSJDynamicRenderTemplateStrategy : CSJDynamicRenderStrategy <BUWebViewDelegate, CSJWebViewDynamicRenderInterface, BUPlayableAdDelegate, CSJWKWebViewClientInterceptionDelegate>
{
    _Bool _haveDetectBlank;
    id <CSJWebViewDynamicRenderDelegate> implementation_delegate;
    CSJWebViewOwner *_webViewOwner;
    CSJWKWebViewClient *_webview;
    BUPlayableAd *_playableAd;
    NSDictionary *_relatedMaterialMetaJSON;
    BUTimer *_renderTimer;
    BUTimer *_retryTimer;
    NSMutableDictionary *_webview_time_trackDictionary;
    UIView *_dialogView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIView *dialogView; // @synthesize dialogView=_dialogView;
@property(retain, nonatomic) NSMutableDictionary *webview_time_trackDictionary; // @synthesize webview_time_trackDictionary=_webview_time_trackDictionary;
@property(retain, nonatomic) BUTimer *retryTimer; // @synthesize retryTimer=_retryTimer;
@property(retain, nonatomic) BUTimer *renderTimer; // @synthesize renderTimer=_renderTimer;
@property(nonatomic) _Bool haveDetectBlank; // @synthesize haveDetectBlank=_haveDetectBlank;
@property(copy, nonatomic) NSDictionary *relatedMaterialMetaJSON; // @synthesize relatedMaterialMetaJSON=_relatedMaterialMetaJSON;
@property(retain, nonatomic) BUPlayableAd *playableAd; // @synthesize playableAd=_playableAd;
@property(retain, nonatomic) CSJWKWebViewClient *webview; // @synthesize webview=_webview;
@property(retain, nonatomic) CSJWebViewOwner *webViewOwner; // @synthesize webViewOwner=_webViewOwner;
@property(nonatomic) __weak id <CSJWebViewDynamicRenderDelegate> implementation_delegate; // @synthesize implementation_delegate;
- (void)_onDialogCloseButton;
- (void)_showDialogWithContent:(id)arg1;
- (id)logKeyName;
- (long long)renderType;
- (void)buWKWebViewClientInterceptedWithStartTime:(double)arg1 url:(id)arg2 type:(id)arg3 isCache:(_Bool)arg4 extraDic:(id)arg5;
- (void)playableEventReportNotification:(id)arg1;
- (id)pbu_csj_piperArray;
- (void)addObservers;
- (void)trackEvent:(id)arg1 params:(id)arg2;
- (id)playableAdCurrentURL:(id)arg1;
- (void)playableAdRenderFailed:(id)arg1;
- (struct CGRect)webViewFrameInPlayableAd:(id)arg1;
- (long long)netTypeForDeviceInPlayableAd:(id)arg1;
- (void)sendRewardFromH5CallbackInPlayableAd:(id)arg1;
- (void)openAppStoreInPlayableAd:(id)arg1 params:(id)arg2;
- (void)playableAd:(id)arg1 executeJavaScript:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)playableAd:(id)arg1 fireEvent:(id)arg2 params:(id)arg3;
- (void)playableAd:(id)arg1 registerHandlerBlock:(CDUnknownBlockType)arg2 forJSMethod:(id)arg3;
- (void)playableAd:(id)arg1 loadRequest:(id)arg2;
- (id)pbu_valid_playable_url;
- (void)pbu_setup_playable;
- (id)jsCallNative_rewardPlayAgainWithParams:(id)arg1;
- (id)jsCallNative_open_app_store;
- (id)jsCallNative_interactiveFinishWithParams:(id)arg1;
- (void)jsCallNative_openPlayableWithParams:(id)arg1;
- (void)jsCallNative_webview_time_trackWithParams:(id)arg1;
- (id)jsCallNative_dynamicTrackWithParams:(id)arg1;
- (void)jsCallNative_preventTouchEventWithParams:(id)arg1;
- (id)jsCallNative_renderDidFinishWithParams:(id)arg1;
- (id)buJSB3_requestPauseVideoWithViewModel:(id)arg1;
- (id)buJSB3_adAnalysisDataWithViewModel:(id)arg1;
- (id)buJSB3_getMaterialMetaWithViewModel:(id)arg1;
- (id)buJSB3_immersiveVideoPageBackWithViewModel:(id)arg1;
- (id)buJSB3_startVideoTransformWithViewModel:(id)arg1;
- (id)buJSB3_skipVideoWithViewModel:(id)arg1;
- (id)buJSB3_getCurrentVideoStateWithViewModel:(id)arg1;
- (id)buJSB3_changeVideoStateWithViewModel:(id)arg1;
- (id)buJSB3_muteVideoWithViewModel:(id)arg1;
- (id)buJSB3_rewardPlayAgainWithViewModel:(id)arg1;
- (id)buJSB3_openPlayableWithViewModel:(id)arg1;
- (id)buJSB3_interstitial_webview_closeWithViewModel:(id)arg1;
- (id)buJSB3_adInfoDialogWithViewModel:(id)arg1;
- (id)buJSB3_preventTouchEventWithViewModel:(id)arg1;
- (id)buJSB3_webview_time_trackWithViewModel:(id)arg1;
- (id)buJSB3_openPrivacyWithViewModel:(id)arg1;
- (id)buJSB3_clickEventWithViewModel:(id)arg1;
- (id)buJSB3_dynamicTrackWithViewModel:(id)arg1;
- (id)buJSB3_renderDidFinishWithViewModel:(id)arg1;
- (id)buJSB3_adInfoWithViewModel:(id)arg1;
- (id)buJSB3_show_skoverlayWithViewModel:(id)arg1;
- (id)buJSB3_getTemplateInfoWithViewModel:(id)arg1;
- (id)buJSB3_interactiveFinishWithViewModel:(id)arg1;
- (void)registerJSBridge3;
- (void)registerMiddlePageJSBridge;
- (void)registVideoInfo;
- (void)registerInterstitialWebViewClose;
- (void)registerOpenPlayable;
- (void)registerPreventTouchEvent;
- (void)registerWebview_time_track;
- (void)registRenderDidFinish;
- (void)registerRewardPlayAgain;
- (void)registAdAnalysisData;
- (void)registerOpenPrivacy;
- (void)registerClickEvent;
- (void)registerDynamicTrack;
- (void)registerGetTemplateInfo;
- (void)registerAdInfo;
- (void)registerOpenSKOverlay;
- (void)registerJsBridge;
- (void)sendTrackDataFromURLString:(id)arg1;
- (void)fireEventRelatedMaterialMeta;
- (void)registJS_ClientData;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)safeImplementationDelegate_dynamicRenderTemplateStrategyDidRender:(id)arg1;
- (void)safeImplementationDelegate_dynamicRenderTemplateStrategyWillRender:(id)arg1;
- (void)pbu_renderEndWithSuccessView:(id)arg1 error:(id)arg2;
- (void)retryTimerAction;
- (void)stopRetryTimer;
- (void)startRetryTimer;
- (double)memoryUsedPercent;
- (double)timeOut;
- (void)renderTimerAction;
- (void)stopRenderTimer;
- (void)startRenderTimerWithTimeInterval:(double)arg1;
- (void)setupViewWithFrame:(struct CGRect)arg1;
- (void)pbu_playableRecycle;
- (void)pbu_resetAndTrigger;
- (double)implementation_timeOut;
- (void)implementation_render_really;
- (long long)implementation_renderIndex;
- (void)invokeWebEvent:(id)arg1 data:(id)arg2;
- (void)updateWithThemeStatus:(long long)arg1;
- (void)sendShowToast:(id)arg1;
- (void)sendShowSkipInLiveScene:(_Bool)arg1;
- (void)sendPlayableStateChange:(_Bool)arg1 reduceDuration:(long long)arg2;
- (void)refreshWKWebViewIfNeed;
- (void)reportMaterialMetaIfNeedWithRelatedMaterialMetaJson:(id)arg1;
- (void)reportShowEventIfNeed;
- (void)detectBlankIfNeed;
- (void)reportExpressAdShowWithBool:(_Bool)arg1;
- (void)__pbu_internal_webview_load;
- (void)render_really;
- (void)render;
- (void)connectionChanged:(id)arg1;
- (void)dealloc;
- (id)initWithRenderEngineViewModel:(id)arg1 containerView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

