//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJRewardedVideoWebViewControllerVM.h"

@interface CSJEndcardWebVM : CSJRewardedVideoWebViewControllerVM
{
    _Bool _isLong_APIRet;
}

@property(nonatomic) _Bool isLong_APIRet; // @synthesize isLong_APIRet=_isLong_APIRet;
- (void)Do_RootOrg:(_Bool)arg1;
- (void)logoImageViewTapped:(id)arg1;
- (double)Sdk_CidIf;
- (_Bool)shouldTrack;
- (void)setUa_CodeNot:(id)arg1;
- (id)Id_TagPos;
- (id)Left_SDKAds:(double)arg1;
- (void)Weak_TapIdx;
- (void)reopenSKoverlay;
- (void)New_WeakLd;
- (void)New_FailMark:(_Bool)arg1;
- (_Bool)useLandingPageNewStyle;
- (void)handleViewWillLayoutSubviews;
- (void)handleViewDidAppear:(_Bool)arg1;
- (void)handleViewDidLoad;
- (id)initViewControllerWithAd:(id)arg1 isNativeExpress:(_Bool)arg2 pageType:(unsigned long long)arg3;

@end

