//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CSJRewardedVideoDownloadBarDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CSJAdSlot, CSJInterstitialCoverView, CSJMaterialMeta, CSJRewardedVideoDownloadBarView, CSJStarView, NSString, UIButton, UIImageView, UILabel, UITapGestureRecognizer;
@protocol CSJFullScreenInterstitialAdDelegate;

@interface CSJFullScreenInterstitialAdView : UIView <CSJRewardedVideoDownloadBarDelegate, UIGestureRecognizerDelegate>
{
    id <CSJFullScreenInterstitialAdDelegate> _Push_ADXR1;
    UIImageView *_adImageView;
    UIImageView *_adAppIconImageView;
    UILabel *_adTitleLabel;
    UILabel *_adDescriptionLabel;
    UILabel *_scoreLabel;
    CSJStarView *_starView;
    UIButton *_adDownloadButton;
    UIImageView *_logoImageView;
    UILabel *_ADXLabel;
    CSJRewardedVideoDownloadBarView *_This_OrAdID;
    CSJInterstitialCoverView *_interstitialCoverView;
    unsigned long long _Docs_TypeX2;
    CSJMaterialMeta *_materialMeta;
    CSJAdSlot *_slot;
    UITapGestureRecognizer *_Lock_R2Gdp;
}

+ (unsigned long long)With_LineItem:(id)arg1;
+ (id)AKey_MateRect:(id)arg1 adSlot:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) UITapGestureRecognizer *Lock_R2Gdp; // @synthesize Lock_R2Gdp=_Lock_R2Gdp;
@property(retain, nonatomic) CSJAdSlot *slot; // @synthesize slot=_slot;
@property(retain, nonatomic) CSJMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
@property(nonatomic) unsigned long long Docs_TypeX2; // @synthesize Docs_TypeX2=_Docs_TypeX2;
@property(retain, nonatomic) CSJInterstitialCoverView *interstitialCoverView; // @synthesize interstitialCoverView=_interstitialCoverView;
@property(retain, nonatomic) CSJRewardedVideoDownloadBarView *This_OrAdID; // @synthesize This_OrAdID=_This_OrAdID;
@property(retain, nonatomic) UILabel *ADXLabel; // @synthesize ADXLabel=_ADXLabel;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(retain, nonatomic) UIButton *adDownloadButton; // @synthesize adDownloadButton=_adDownloadButton;
@property(retain, nonatomic) CSJStarView *starView; // @synthesize starView=_starView;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) UILabel *adDescriptionLabel; // @synthesize adDescriptionLabel=_adDescriptionLabel;
@property(retain, nonatomic) UILabel *adTitleLabel; // @synthesize adTitleLabel=_adTitleLabel;
@property(retain, nonatomic) UIImageView *adAppIconImageView; // @synthesize adAppIconImageView=_adAppIconImageView;
@property(retain, nonatomic) UIImageView *adImageView; // @synthesize adImageView=_adImageView;
@property(nonatomic) __weak id <CSJFullScreenInterstitialAdDelegate> Push_ADXR1; // @synthesize Push_ADXR1=_Push_ADXR1;
- (id)Out_XzjLevi:(id)arg1;
- (id)interstitialPlayer;
- (id)Res_IdDocs:(id)arg1;
- (id)c_xyDict;
- (void)downloadButtonTapped:(id)arg1 extraDic:(id)arg2;
- (void)downloadBarTapped:(id)arg1 extraDic:(id)arg2;
- (void)logoImageViewAction;
- (void)adAction:(id)arg1;
- (void)adTapGestureAction:(id)arg1;
- (void)closeButtonTapped:(id)arg1;
- (void)dislikeButtonTapped:(id)arg1;
- (struct CGSize)Http_A2Not:(id)arg1 size:(struct CGSize)arg2 font:(id)arg3;
- (void)layoutSubviews;
- (void)Str_PosHpp;
- (id)initWithMaterial:(id)arg1 adSlot:(id)arg2 Docs_TypeX2:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

