//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJBasicModel.h"

@class NSString;

@interface CSJLiveStreamInfo : CSJBasicModel
{
    long long _live_author_follower_count;
    NSString *_live_author_nickname;
    NSString *_live_avatar_url;
    long long _live_avatar_height;
    long long _live_avatar_width;
    NSString *_live_cover_image_url;
    long long _live_cover_height;
    long long _live_cover_width;
    NSString *_live_description;
    NSString *_live_feed_url;
    long long _live_show_time;
    long long _live_watch_count;
    long long _stream_orientation;
}

- (void).cxx_destruct;
@property(nonatomic) long long stream_orientation; // @synthesize stream_orientation=_stream_orientation;
@property(nonatomic) long long live_watch_count; // @synthesize live_watch_count=_live_watch_count;
@property(nonatomic) long long live_show_time; // @synthesize live_show_time=_live_show_time;
@property(copy, nonatomic) NSString *live_feed_url; // @synthesize live_feed_url=_live_feed_url;
@property(copy, nonatomic) NSString *live_description; // @synthesize live_description=_live_description;
@property(nonatomic) long long live_cover_width; // @synthesize live_cover_width=_live_cover_width;
@property(nonatomic) long long live_cover_height; // @synthesize live_cover_height=_live_cover_height;
@property(copy, nonatomic) NSString *live_cover_image_url; // @synthesize live_cover_image_url=_live_cover_image_url;
@property(nonatomic) long long live_avatar_width; // @synthesize live_avatar_width=_live_avatar_width;
@property(nonatomic) long long live_avatar_height; // @synthesize live_avatar_height=_live_avatar_height;
@property(copy, nonatomic) NSString *live_avatar_url; // @synthesize live_avatar_url=_live_avatar_url;
@property(copy, nonatomic) NSString *live_author_nickname; // @synthesize live_author_nickname=_live_author_nickname;
@property(nonatomic) long long live_author_follower_count; // @synthesize live_author_follower_count=_live_author_follower_count;
- (id)liveAvatar;
- (_Bool)isValid;

@end

