//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJAdBaseObject.h"

#import "CSJAdClientBiddingProtocol-Protocol.h"
#import "CSJMopubAdMarkUpDelegate-Protocol.h"
#import "CSJNativeExpressAdViewDelegate-Protocol.h"
#import "CSJNativeExpressAdViewDismissDelegate-Protocol.h"
#import "CSJNativeExpressVideoAdDelegate-Protocol.h"
#import "CSJVideoAdDelegate-Protocol.h"

@class CSJADViewTrackInfo, CSJAdSlot, CSJDislikeContext, CSJFullScreenTransitioningDelegate, CSJNativeAd, CSJNativeExpressAdManager, CSJNativeExpressRewardedVideoAdView, CSJRewardedVideoModel, NSDictionary, NSString, UIViewController;
@protocol CSJNativeExpressFullscreenVideoAdDelegate;

@interface CSJNativeExpressFullscreenVideoAd : CSJAdBaseObject <CSJNativeExpressAdViewDelegate, CSJNativeExpressVideoAdDelegate, CSJVideoAdDelegate, CSJNativeExpressAdViewDismissDelegate, CSJMopubAdMarkUpDelegate, CSJAdClientBiddingProtocol>
{
    _Bool isRewardedVideo;
    _Bool _materialMetaIsFromPreload;
    _Bool _didSetADM;
    _Bool _isShow;
    _Bool _triggerNativeAdDidLoadCallback;
    _Bool _triggerNativeAdDidDownloadCallback;
    id <CSJNativeExpressFullscreenVideoAdDelegate> _delegate;
    CSJFullScreenTransitioningDelegate *_New_LoadBool;
    UIViewController *_Rect_FtTo;
    double _expireTimestamp;
    CSJADViewTrackInfo *_trackInfo;
    CSJNativeExpressAdManager *_nativeExpressAdManager;
    CSJAdSlot *_adSlot;
    CSJNativeAd *_purePlayableNativeAd;
    CSJNativeExpressRewardedVideoAdView *_expressAdView;
    CSJDislikeContext *_dislikeContext;
    long long _realSlotRenderType;
}

- (void).cxx_destruct;
@property(nonatomic) long long realSlotRenderType; // @synthesize realSlotRenderType=_realSlotRenderType;
@property(nonatomic) _Bool triggerNativeAdDidDownloadCallback; // @synthesize triggerNativeAdDidDownloadCallback=_triggerNativeAdDidDownloadCallback;
@property(nonatomic) _Bool triggerNativeAdDidLoadCallback; // @synthesize triggerNativeAdDidLoadCallback=_triggerNativeAdDidLoadCallback;
@property(retain, nonatomic) CSJDislikeContext *dislikeContext; // @synthesize dislikeContext=_dislikeContext;
@property(retain, nonatomic) CSJNativeExpressRewardedVideoAdView *expressAdView; // @synthesize expressAdView=_expressAdView;
@property(retain, nonatomic) CSJNativeAd *purePlayableNativeAd; // @synthesize purePlayableNativeAd=_purePlayableNativeAd;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(retain, nonatomic) CSJAdSlot *adSlot; // @synthesize adSlot=_adSlot;
@property(retain, nonatomic) CSJNativeExpressAdManager *nativeExpressAdManager; // @synthesize nativeExpressAdManager=_nativeExpressAdManager;
@property(nonatomic) _Bool didSetADM; // @synthesize didSetADM=_didSetADM;
@property(retain, nonatomic) CSJADViewTrackInfo *trackInfo; // @synthesize trackInfo=_trackInfo;
@property(nonatomic) double expireTimestamp; // @synthesize expireTimestamp=_expireTimestamp;
@property(nonatomic) _Bool materialMetaIsFromPreload; // @synthesize materialMetaIsFromPreload=_materialMetaIsFromPreload;
@property(nonatomic) __weak UIViewController *Rect_FtTo; // @synthesize Rect_FtTo=_Rect_FtTo;
@property(retain, nonatomic) CSJFullScreenTransitioningDelegate *New_LoadBool; // @synthesize New_LoadBool=_New_LoadBool;
@property(nonatomic) __weak id <CSJNativeExpressFullscreenVideoAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isRewardedVideo; // @synthesize isRewardedVideo;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (id)Call_T5Win;
- (_Bool)Meta_CCPAOnly:(id)arg1;
- (void)Code_DidPods;
- (id)Gdp_InitPop;
- (void)_dir_IDIdfa:(id)arg1 adModel:(id)arg2 extraDic:(id)arg3;
- (void)Lock_WeakRan:(id)arg1;
- (id)Ret_TimeRect:(id)arg1;
- (unsigned long long)Stmt_FtcText;
@property(readonly, copy, nonatomic) NSDictionary *mediaExt;
- (_Bool)isAdValid;
- (void)This_BeInt;
- (void)Json_XzjTm:(long long)arg1;
- (void)M_PI_DoesObj:(id)arg1;
- (void)_val_SlotFm:(id)arg1;
- (void)Stmt_FabsEnd;
- (void)Case_UserAdId;
- (void)Stop_TmTv;
- (void)Pos_UserMask;
- (void)Read_IsUrl:(id)arg1;
- (void)You_PodsFrom;
- (void)Does_logTrue;
- (void)The_MsRet;
- (void)Noti_LazyInfo;
- (void)Msg_NilApp;
- (void)interstitialAdDidClose;
- (void)And_UIWhen;
- (void)Skip_RitKey;
- (void)interstitialAdDidClick;
- (void)didCloseOtherControllerWithInteractionType:(long long)arg1;
- (void)videoAdDidClickSkip;
- (void)videoAdDidPlayFinishWithError:(id)arg1;
- (void)videoAdDidClose;
- (void)videoAdWillClose;
- (void)videoAdDidClick;
- (void)nativeExpressVideoAdEndcardDidClose;
- (void)nativeExpressVideoAdEndcardWillClose;
- (void)nativeExpressVideoAdDidClickSkip;
- (void)nativeExpressVideoAdDidPlayFinishWithError:(id)arg1;
- (void)nativeExpressAdViewDismiss:(id)arg1;
- (void)nativeExpressAdViewWillDismiss:(id)arg1;
- (void)nativeExpressAdViewDidCloseOtherController:(id)arg1 interactionType:(long long)arg2;
- (void)nativeExpressAdViewDidClick:(id)arg1;
- (void)nativeExpressAdViewRenderFail:(id)arg1 error:(id)arg2;
- (void)nativeExpressAdViewRenderSuccess:(id)arg1;
- (void)nativeExpressAdFailToLoad:(id)arg1 error:(id)arg2;
- (void)nativeExpressAdSuccessToLoad:(id)arg1 views:(id)arg2;
- (void)Call_AddOrg:(id)arg1;
- (_Bool)Fabs_MetaTop;
- (id)biddingToken;
- (void)setAdMarkup:(id)arg1;
- (void)loss:(id)arg1 lossReason:(id)arg2 winBidder:(id)arg3;
- (void)win:(id)arg1;
- (void)setPrice:(id)arg1;
- (void)MIT_AnInit;
- (void)Char_VliMark:(id)arg1 ritSceneStr:(id)arg2;
- (void)Read_EnumStd:(id)arg1 ritSceneStr:(id)arg2;
- (void)Stop_SetThe;
- (double)getExpireTimestamp;
- (_Bool)showAdFromRootViewController:(id)arg1 ritSceneDescribe:(id)arg2;
- (_Bool)showAdFromRootViewController:(id)arg1;
- (id)getAdCreativeToken;
- (void)loadAdData;
- (void)dealloc;
- (void)_applicationWillEnterForeground;
- (void)_applicationDidEnterBackground;
- (id)initWithSlot:(id)arg1;
- (id)initWithSlotID:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) CSJRewardedVideoModel *rewardedVideoModel;
@property(readonly) Class superclass;

@end

