//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJNativeExpressAdView.h"

@class BUPlayerItem, BUTimer, CSJVideoAdTracker;
@protocol CSJNativeExpressSplashVideoAdViewDelegate;

@interface CSJNativeExpressSplashVideoAdView : CSJNativeExpressAdView
{
    id <CSJNativeExpressSplashVideoAdViewDelegate> _delegate;
    BUPlayerItem *_playerItem;
    BUTimer *_quitTimer;
    CSJVideoAdTracker *_videoTracker;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJVideoAdTracker *videoTracker; // @synthesize videoTracker=_videoTracker;
@property(retain, nonatomic) BUTimer *quitTimer; // @synthesize quitTimer=_quitTimer;
@property(retain, nonatomic) BUPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(nonatomic) __weak id <CSJNativeExpressSplashVideoAdViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)invalidateQuitTimer;
- (void)forceQuit;
- (void)judgeQuit;
- (void)resetPlayer;
- (void)player:(id)arg1 decodeModeChanged:(unsigned long long)arg2;
- (void)playerDidPlayFinish:(id)arg1 error:(id)arg2;
- (void)player:(id)arg1 stateDidChanged:(long long)arg2;
- (void)playerReadyToPlay:(id)arg1;
- (void)handleClickEventIsVideoClicked:(_Bool)arg1 isEndcardClicked:(_Bool)arg2;
- (void)handleSkipVideo;
- (void)handleInvalidVideoUrl;
- (void)startPlayVideo;
- (void)_initPlayer;
- (_Bool)_shouldInitPlayer;
- (void)applicationWillTerminateNotification:(id)arg1;
- (void)removeNotification;
- (void)addNotification;
- (id)initWithFrame:(struct CGRect)arg1 nativeAd:(id)arg2 nativeExpressAdViewSource:(long long)arg3;
- (void)dealloc;

@end

