//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "CSJRewardedVideoDrawAdViewDelegate-Protocol.h"
#import "CSJRewardedVideoTopBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BUTimer, CSJAdSlot, CSJMaterialMeta, CSJNativeExpressRewardDrawAdView, CSJNativeExpressRewardDrawEndcardTransfer, CSJNativeExpressRewardDrawRewardSender, CSJNativeExpressRewardDrawUpSwipArrowView, CSJNativeExpressRewardUpSwipBottomView, CSJRewardedVideoTopBarView, CSJURitSettingModel, NSArray, NSString, UITableView;
@protocol CSJNativeExpressVideoAdDelegate;

@interface CSJNativeExpressRewardDrawDisplayViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, CSJRewardedVideoTopBarDelegate, CSJRewardedVideoDrawAdViewDelegate>
{
    _Bool _isMute;
    _Bool _isShowAlert;
    _Bool _Only_ResLen;
    id <CSJNativeExpressVideoAdDelegate> _rewardedVideoAd;
    NSArray *_expressAdViews;
    UIViewController *_parentVC;
    CSJAdSlot *_slot;
    UITableView *_tableView;
    CSJRewardedVideoTopBarView *_topBarView;
    CSJNativeExpressRewardDrawUpSwipArrowView *_Pop_StmtIcon;
    CSJNativeExpressRewardUpSwipBottomView *_Net_ByOrg;
    CSJMaterialMeta *_Pos_AdIdIpv4;
    CSJURitSettingModel *_ritModel;
    unsigned long long _On_CnUsed;
    unsigned long long _Zone_InitNet;
    NSString *_Ipv4_MsgCid;
    BUTimer *_Os_BOOLGdp;
    long long _This_AreaTop;
    BUTimer *_Adm_HashCode;
    long long _List_SqlNoti;
    BUTimer *_R0_CharEnum;
    CSJNativeExpressRewardDrawRewardSender *_rewardSender;
    CSJNativeExpressRewardDrawEndcardTransfer *_Stmt_TheBe;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool Only_ResLen; // @synthesize Only_ResLen=_Only_ResLen;
@property(retain, nonatomic) CSJNativeExpressRewardDrawEndcardTransfer *Stmt_TheBe; // @synthesize Stmt_TheBe=_Stmt_TheBe;
@property(retain, nonatomic) CSJNativeExpressRewardDrawRewardSender *rewardSender; // @synthesize rewardSender=_rewardSender;
@property(retain, nonatomic) BUTimer *R0_CharEnum; // @synthesize R0_CharEnum=_R0_CharEnum;
@property(nonatomic) long long List_SqlNoti; // @synthesize List_SqlNoti=_List_SqlNoti;
@property(retain, nonatomic) BUTimer *Adm_HashCode; // @synthesize Adm_HashCode=_Adm_HashCode;
@property(nonatomic) long long This_AreaTop; // @synthesize This_AreaTop=_This_AreaTop;
@property(retain, nonatomic) BUTimer *Os_BOOLGdp; // @synthesize Os_BOOLGdp=_Os_BOOLGdp;
@property(nonatomic) _Bool isShowAlert; // @synthesize isShowAlert=_isShowAlert;
@property(copy, nonatomic) NSString *Ipv4_MsgCid; // @synthesize Ipv4_MsgCid=_Ipv4_MsgCid;
@property(nonatomic) _Bool isMute; // @synthesize isMute=_isMute;
@property(nonatomic) unsigned long long Zone_InitNet; // @synthesize Zone_InitNet=_Zone_InitNet;
@property(nonatomic) unsigned long long On_CnUsed; // @synthesize On_CnUsed=_On_CnUsed;
@property(retain, nonatomic) CSJURitSettingModel *ritModel; // @synthesize ritModel=_ritModel;
@property(retain, nonatomic) CSJMaterialMeta *Pos_AdIdIpv4; // @synthesize Pos_AdIdIpv4=_Pos_AdIdIpv4;
@property(retain, nonatomic) CSJNativeExpressRewardUpSwipBottomView *Net_ByOrg; // @synthesize Net_ByOrg=_Net_ByOrg;
@property(retain, nonatomic) CSJNativeExpressRewardDrawUpSwipArrowView *Pop_StmtIcon; // @synthesize Pop_StmtIcon=_Pop_StmtIcon;
@property(retain, nonatomic) CSJRewardedVideoTopBarView *topBarView; // @synthesize topBarView=_topBarView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) CSJAdSlot *slot; // @synthesize slot=_slot;
@property(nonatomic) __weak UIViewController *parentVC; // @synthesize parentVC=_parentVC;
@property(copy, nonatomic) NSArray *expressAdViews; // @synthesize expressAdViews=_expressAdViews;
@property(nonatomic) __weak id <CSJNativeExpressVideoAdDelegate> rewardedVideoAd; // @synthesize rewardedVideoAd=_rewardedVideoAd;
- (void)Are_ItYou;
- (unsigned long long)Save_CnSlot;
@property(readonly, nonatomic) CSJMaterialMeta *Tm_TypeIpv4;
@property(readonly, nonatomic) CSJNativeExpressRewardDrawAdView *Org_IsPods;
- (void)Rect_FileBe;
- (void)sendReward;
- (void)rewardDrawAdViewEnableScroll:(_Bool)arg1;
- (id)rewardDrawAdViewReportGetAdExtraDic;
- (void)rewardDrawAdViewInteractSkipDuration:(long long)arg1;
- (void)rewardDrawAdViewShowNextAd;
- (void)rewardDrawAdViewIsShowAlert:(_Bool)arg1 adView:(id)arg2;
- (long long)rewardDrawAdViewGetRewardLeftTime;
- (void)rewardDrawAdViewDidPlayFinish:(id)arg1 player:(id)arg2 error:(id)arg3;
- (void)rewardDrawAdViewDimissCurrentVC:(id)arg1;
- (void)rewardDrawAdViewSwitchToEndcard:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)videoTopBarDislikeButtonTapped:(id)arg1;
- (void)videoTopBarCloseButtonTapped:(id)arg1;
- (void)videoTopBarSilentButtonTapped:(id)arg1;
- (void)storeKitDidClose:(id)arg1;
- (void)storeKitWillOpen:(id)arg1;
- (void)receiveWillResignActiveNotification:(id)arg1;
- (void)receivedidBecomeActiveNotification:(id)arg1;
- (void)Init_NotYES;
- (void)residentTimerAction:(id)arg1;
- (void)Text_IfOnly;
- (void)Y1_ThatA1;
- (void)updateSkipLeftSeconds:(id)arg1;
- (void)Com_TimeSql;
- (void)Lds_Up_xWin;
- (void)Body_CCPAMAX;
- (void)updateRewardLeftSeconds:(id)arg1;
- (void)Xzj_WithCarl;
- (void)At_TsUI;
- (void)Req_DataStr;
- (void)Set_ObjcVc;
- (void)Cta_Sdk_pos;
- (void)T5_PosUp_y;
- (void)Fabs_BoolData;
- (void)Can_RetObjc;
- (void)Log_NotTemp;
- (void)viewDidLoad;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)initLIdx_UserFabs;
- (id)initLFrom_ThatPath:(id)arg1 parentVC:(id)arg2 slot:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

