//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;
@protocol CSJNativeExpressBannerOverseaDislikeViewDelegate;

@interface CSJNativeExpressBannerOverseaDislikeView : UIView
{
    _Bool _isSmallBanner;
    id <CSJNativeExpressBannerOverseaDislikeViewDelegate> _delegate;
    UIImageView *_backgroundImageView;
    UILabel *_closeLabel;
    UIImageView *_iconImageView;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isSmallBanner; // @synthesize isSmallBanner=_isSmallBanner;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UILabel *closeLabel; // @synthesize closeLabel=_closeLabel;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) __weak id <CSJNativeExpressBannerOverseaDislikeViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)layoutSubviews;
- (void)gotoLogoWebViewVoid;
- (void)buildupView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

