//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BUVideoPlayerDelegate-Protocol.h"
#import "BUVideoPlayerTimeDelegate-Protocol.h"

@class CSJMaterialMeta, CSJPlayableVideoTipsView, CSJPlayableVideoView, NSString, UIActivityIndicatorView, UILabel, UIView;

@interface CSJPlayableVideoController : NSObject <BUVideoPlayerDelegate, BUVideoPlayerTimeDelegate>
{
    _Bool _mute;
    _Bool _storeKitOpen;
    _Bool _hidden;
    _Bool _isShowed;
    _Bool _isValidVideo;
    double _currentVideoPlayTime;
    CSJMaterialMeta *_materialMeta;
    CSJPlayableVideoView *_videoView;
    UIView *_superView;
    UIActivityIndicatorView *_loadingView;
    CSJPlayableVideoTipsView *_tipsView;
    UILabel *_errorTipsLabel;
    NSString *_orignalCategory;
    struct CGRect _originFrame;
}

- (void).cxx_destruct;
@property(nonatomic) NSString *orignalCategory; // @synthesize orignalCategory=_orignalCategory;
@property(retain, nonatomic) UILabel *errorTipsLabel; // @synthesize errorTipsLabel=_errorTipsLabel;
@property(retain, nonatomic) CSJPlayableVideoTipsView *tipsView; // @synthesize tipsView=_tipsView;
@property(retain, nonatomic) UIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) struct CGRect originFrame; // @synthesize originFrame=_originFrame;
@property(nonatomic) _Bool isValidVideo; // @synthesize isValidVideo=_isValidVideo;
@property(nonatomic) _Bool isShowed; // @synthesize isShowed=_isShowed;
@property(nonatomic) __weak UIView *superView; // @synthesize superView=_superView;
@property(nonatomic) _Bool hidden; // @synthesize hidden=_hidden;
@property(nonatomic) _Bool storeKitOpen; // @synthesize storeKitOpen=_storeKitOpen;
@property(retain, nonatomic) CSJPlayableVideoView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) CSJMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
@property(nonatomic) _Bool mute; // @synthesize mute=_mute;
@property(nonatomic) double currentVideoPlayTime; // @synthesize currentVideoPlayTime=_currentVideoPlayTime;
- (void)player:(id)arg1 second:(double)arg2;
- (void)playerDidPlayFinish:(id)arg1 error:(id)arg2;
- (void)playerReadyToPlayWhenApplicationEnterBackground:(id)arg1;
- (void)playerReadyToPlay:(id)arg1;
- (void)player:(id)arg1 decodeModeChanged:(unsigned long long)arg2;
- (void)player:(id)arg1 stateDidChanged:(long long)arg2;
- (void)dealloc;
- (void)applicationDidEnterBackGround;
- (void)applicationDidEnterForeGround;
- (void)storeKitDidClose:(id)arg1;
- (void)storeKitWillOpen:(id)arg1;
- (void)addNotification;
- (void)reset;
- (void)hide;
- (void)showInView:(id)arg1;
- (long long)edgeTo:(struct CGPoint)arg1;
- (void)moveAction:(id)arg1;
- (void)setupPlayer;
- (id)initWithMaterial:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

