//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface CSJPlayableTagView : UIView
{
    double _length;
    long long _Hopo_LeviName;
}

@property(nonatomic) long long Hopo_LeviName; // @synthesize Hopo_LeviName=_Hopo_LeviName;
@property(nonatomic) double length; // @synthesize length=_length;
- (_Bool)In_RitLock:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

