//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel, UIWindow;

@interface CSJRewardBrowseAlertView : UIView
{
    CDUnknownBlockType _App_SelOrg;
    CDUnknownBlockType _cancelBlock;
    UIImageView *_icon;
    UILabel *_titleLabel;
    UILabel *_Adm_LazyLog;
    UIButton *_confirmBtn;
    UIButton *_cancelBtn;
    UIView *_contentView;
    UIWindow *_bgWindow;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIWindow *bgWindow; // @synthesize bgWindow=_bgWindow;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UILabel *Adm_LazyLog; // @synthesize Adm_LazyLog=_Adm_LazyLog;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType App_SelOrg; // @synthesize App_SelOrg=_App_SelOrg;
- (void)hide;
- (void)show;
- (void)confirmBtnClicked;
- (void)closeBtnClicked;
- (id)initWith:(id)arg1 msg:(id)arg2;

@end

