//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface CSJRenderClickEventModel : NSObject
{
    long long _areaType;
    NSString *_clickAreaType;
    NSDictionary *_clickInfo;
    long long _userBehaviorType;
    long long _clickAreaCategory;
}

- (void).cxx_destruct;
@property(nonatomic) long long clickAreaCategory; // @synthesize clickAreaCategory=_clickAreaCategory;
@property(nonatomic) long long userBehaviorType; // @synthesize userBehaviorType=_userBehaviorType;
@property(copy, nonatomic) NSDictionary *clickInfo; // @synthesize clickInfo=_clickInfo;
@property(copy, nonatomic) NSString *clickAreaType; // @synthesize clickAreaType=_clickAreaType;
@property(nonatomic) long long areaType; // @synthesize areaType=_areaType;
- (id)initWithDictionary:(id)arg1;
- (id)init;

@end

