//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CSJRewardedVideoPreloaderManager : NSObject
{
    _Bool _isView_ExtStr;
    CDUnknownBlockType _MIT_UIY1;
}

+ (void)Or_LogoWhen;
+ (id)defaultPersistence;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType MIT_UIY1; // @synthesize MIT_UIY1=_MIT_UIY1;
@property(nonatomic) _Bool isView_ExtStr; // @synthesize isView_ExtStr=_isView_ExtStr;
- (void)Host_Be_pos:(id)arg1 slotId:(id)arg2;
- (void)M_PI_MustYou:(id)arg1 slot:(id)arg2;
- (void)Used_LenElse:(id)arg1;
- (void)Add_WithAry:(id)arg1 adSlot:(id)arg2 successLoadVideo:(CDUnknownBlockType)arg3;
- (void)Ua_ToAdID:(id)arg1 sucess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 successLoadVideo:(CDUnknownBlockType)arg4 failureLoadVideo:(CDUnknownBlockType)arg5 IsPre:(_Bool)arg6;
- (id)Os_ReqIv:(id)arg1;
- (void)Set_FtDiff:(id)arg1;
- (void)callSuccessBlock:(CDUnknownBlockType)arg1 withMaterial:(id)arg2;
- (void)callSuccessBlock:(CDUnknownBlockType)arg1 withMaterialMetas:(id)arg2;
- (void)Nil_MAXOnly:(id)arg1 sucess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 successLoadVideo:(CDUnknownBlockType)arg4;
- (void)Nil_MAXOnly:(id)arg1 materiaReuse:(CDUnknownBlockType)arg2 sucess:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4 successLoadVideo:(CDUnknownBlockType)arg5;
- (id)init;
- (id)Dic_ZoneKey:(id)arg1;
- (void)Sel_DataShow:(id)arg1 url:(id)arg2;
- (id)Or_SelOpen;
- (id)Will_ThisUse:(id)arg1;
- (void)Info_Y2Http:(id)arg1 sucess:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3 successLoadVideo:(CDUnknownBlockType)arg4;
- (_Bool)The_SetHost;

@end

