//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class CSJAdSlot, CSJMaterialMeta, CSJStarView, NSString, UIButton, UIImageView, UILabel;
@protocol CSJRewardedVideoDownloadBarDelegate;

@interface CSJRewardedVideoDownloadBarView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _isPortrait;
    _Bool _isMap_WinDiff;
    id <CSJRewardedVideoDownloadBarDelegate> _delegate;
    CSJMaterialMeta *_materialMeta;
    CSJAdSlot *_slot;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    UILabel *_Ua_Ios_pos;
    UIButton *_downloadButton;
    UILabel *_scoreLabel;
    CSJStarView *_starView;
    unsigned long long _Js_PodsURL;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long Js_PodsURL; // @synthesize Js_PodsURL=_Js_PodsURL;
@property(nonatomic) _Bool isMap_WinDiff; // @synthesize isMap_WinDiff=_isMap_WinDiff;
@property(nonatomic) _Bool isPortrait; // @synthesize isPortrait=_isPortrait;
@property(retain, nonatomic) CSJStarView *starView; // @synthesize starView=_starView;
@property(retain, nonatomic) UILabel *scoreLabel; // @synthesize scoreLabel=_scoreLabel;
@property(retain, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(retain, nonatomic) UILabel *Ua_Ios_pos; // @synthesize Ua_Ios_pos=_Ua_Ios_pos;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) CSJAdSlot *slot; // @synthesize slot=_slot;
@property(retain, nonatomic) CSJMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
@property(nonatomic) __weak id <CSJRewardedVideoDownloadBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void)addAccessibilityIdentifier;
- (id)buttonText;
- (void)downloadTapped;
- (void)downloadButtonTapped;
- (void)Key_RitFail;
- (void)API_TODOIs;
- (void)Self_IOSCarl;
- (void)layoutSubviews;
- (void)Or_AdmMain;
- (void)buildUpView;
- (id)initLApp_WinRit:(id)arg1 slot:(id)arg2 barStyle:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

