//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NSCoding-Protocol.h"

@class CSJSKANADImpressionModel, NSDate;

@interface CSJSKANADImpressionObject : NSObject <NSCoding>
{
    NSDate *_impressionDate;
    CSJSKANADImpressionModel *_skan_Impression_item;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJSKANADImpressionModel *skan_Impression_item; // @synthesize skan_Impression_item=_skan_Impression_item;
@property(retain) NSDate *impressionDate; // @synthesize impressionDate=_impressionDate;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

