//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJBaseLoadingPageView.h"

@class CSJMaterialMeta, CSJNumerAnimationLabel, UIImageView, UILabel;

@interface CSJScaleLoadingPageView : CSJBaseLoadingPageView
{
    _Bool _isPortrait;
    _Bool _hasIcon;
    CDUnknownBlockType _adButtonClickBlock;
    UIImageView *_iconImageView;
    UILabel *_loadingLabel;
    CSJNumerAnimationLabel *_progressLabel;
    UILabel *_percentLabel;
    CSJMaterialMeta *_materialMeta;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJMaterialMeta *materialMeta; // @synthesize materialMeta=_materialMeta;
@property(nonatomic) _Bool hasIcon; // @synthesize hasIcon=_hasIcon;
@property(retain, nonatomic) UILabel *percentLabel; // @synthesize percentLabel=_percentLabel;
@property(retain, nonatomic) CSJNumerAnimationLabel *progressLabel; // @synthesize progressLabel=_progressLabel;
@property(retain, nonatomic) UILabel *loadingLabel; // @synthesize loadingLabel=_loadingLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void)setAdButtonClickBlock:(CDUnknownBlockType)arg1;
- (CDUnknownBlockType)adButtonClickBlock;
- (_Bool)isPortrait;
- (void)startLoading;
- (void)setIsPortrait:(_Bool)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

