//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CSJNativeAdsManagerDelegate-Protocol.h"

@class CSJADLoadContext, CSJAdSlot, CSJImage, CSJMaterialMeta, CSJNativeAd, NSDictionary, NSString;
@protocol CSJSplashViewModelDelegate;

@interface CSJSplashViewModel : NSObject <CSJNativeAdsManagerDelegate>
{
    _Bool _showDislike;
    _Bool _hideSkipButton;
    _Bool _showAdLogoIcon;
    _Bool _showAdxLabel;
    _Bool _showMute;
    _Bool _isLoading;
    _Bool _setTolerateTimeoutDidCall;
    _Bool _canShowZoomOutView;
    _Bool _canShowCardView;
    id <CSJSplashViewModelDelegate> _delegate;
    CSJMaterialMeta *_materialMetaModel;
    CSJAdSlot *_adSlot;
    CSJNativeAd *_nativeAd;
    double _tolerateTimeout;
    CSJImage *_splashImage;
    CSJImage *_logoImage;
    double _countDown;
    NSString *_adxLabelText;
    NSDictionary *_extraInfo;
    double _splashStartLoad;
    unsigned long long _skipBtnPosition;
    long long _skipLeftOrRightMargin;
    long long _skipTopOrBottomMargin;
    CSJADLoadContext *_context;
    struct CGSize _adSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJADLoadContext *context; // @synthesize context=_context;
@property(nonatomic) long long skipTopOrBottomMargin; // @synthesize skipTopOrBottomMargin=_skipTopOrBottomMargin;
@property(nonatomic) long long skipLeftOrRightMargin; // @synthesize skipLeftOrRightMargin=_skipLeftOrRightMargin;
@property(nonatomic) unsigned long long skipBtnPosition; // @synthesize skipBtnPosition=_skipBtnPosition;
@property(nonatomic) _Bool canShowCardView; // @synthesize canShowCardView=_canShowCardView;
@property(nonatomic) _Bool canShowZoomOutView; // @synthesize canShowZoomOutView=_canShowZoomOutView;
@property(nonatomic) double splashStartLoad; // @synthesize splashStartLoad=_splashStartLoad;
@property(retain, nonatomic) NSDictionary *extraInfo; // @synthesize extraInfo=_extraInfo;
@property(nonatomic) _Bool setTolerateTimeoutDidCall; // @synthesize setTolerateTimeoutDidCall=_setTolerateTimeoutDidCall;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool showMute; // @synthesize showMute=_showMute;
@property(copy, nonatomic) NSString *adxLabelText; // @synthesize adxLabelText=_adxLabelText;
@property(nonatomic) _Bool showAdxLabel; // @synthesize showAdxLabel=_showAdxLabel;
@property(nonatomic) _Bool showAdLogoIcon; // @synthesize showAdLogoIcon=_showAdLogoIcon;
@property(nonatomic) double countDown; // @synthesize countDown=_countDown;
@property(nonatomic) _Bool hideSkipButton; // @synthesize hideSkipButton=_hideSkipButton;
@property(nonatomic) _Bool showDislike; // @synthesize showDislike=_showDislike;
@property(retain, nonatomic) CSJImage *logoImage; // @synthesize logoImage=_logoImage;
@property(retain, nonatomic) CSJImage *splashImage; // @synthesize splashImage=_splashImage;
@property(nonatomic) double tolerateTimeout; // @synthesize tolerateTimeout=_tolerateTimeout;
@property(nonatomic) struct CGSize adSize; // @synthesize adSize=_adSize;
@property(retain, nonatomic) CSJNativeAd *nativeAd; // @synthesize nativeAd=_nativeAd;
@property(retain, nonatomic) CSJAdSlot *adSlot; // @synthesize adSlot=_adSlot;
@property(retain, nonatomic) CSJMaterialMeta *materialMetaModel; // @synthesize materialMetaModel=_materialMetaModel;
@property(nonatomic) __weak id <CSJSplashViewModelDelegate> delegate; // @synthesize delegate=_delegate;
- (void)outerCallLoadTimeoutWithError:(id)arg1;
- (void)outerCallNoRspWithError:(id)arg1;
- (void)outerCallSend;
- (void)splashTotalLoadTimeTrack;
- (void)splashAdRenderTrackEnd;
- (void)splashAdRenderTrackBegin;
- (void)splashLoadImageTimeTrack;
- (void)splashAdLoadTimeTrack;
- (void)splashZoomOutShowTrackWithAdExtra:(id)arg1;
- (void)splashZoomOutVideoShowTimeTrackWithAdExtra:(id)arg1;
- (void)splashZoomOutCloseTrackWithExtra:(id)arg1;
- (void)splashCardCloseTrackWithAdExtra:(id)arg1;
- (void)splashCardClickTrackWithAdExtra:(id)arg1;
- (void)splashCardShowTrack;
- (void)splashEnterForegroundTrackWithExtra:(id)arg1;
- (void)splashEnterBackgroundTrackWithExtra:(id)arg1;
- (void)splashAdSkipTrackWithExtra:(id)arg1;
- (void)splashAdClickTrackWithExtra:(id)arg1;
- (id)trackView:(id)arg1 isCache:(id)arg2;
- (unsigned long long)getSplashZoomOutIconStatusWithMaterialMetaModel:(id)arg1;
- (id)handleSplashZoomOutIconLogMaterial:(id)arg1 extraInfo:(id)arg2;
- (double)_pbu_default_timeWithTime:(double)arg1 ritModel:(id)arg2;
- (double)tolerateTimeoutNativeTotalTime;
- (double)tolerateTimeoutDetachNativehanderTime;
- (double)tolerateTimeoutDetachNativehanderTimeForNetwork;
- (id)getAdCreativeToken;
- (void)preLoadMiddlePageWithAd:(id)arg1;
@property(readonly, nonatomic) double renderTimeoutLeft;
- (id)mediaExt;
- (void)loadAdData;
- (void)dealloc;
- (id)initWithSlot:(id)arg1 adSize:(struct CGSize)arg2;
- (id)initWithSlotID:(id)arg1 adSize:(struct CGSize)arg2;
- (void)nativeAdsManager:(id)arg1 didFailWithError:(id)arg2;
- (void)nativeAdsManagerSuccessToLoad:(id)arg1 nativeAds:(id)arg2;
- (id)getClientBiddingHandle;
- (id)clientBiddingHandle;
- (void)setClientBiddingHandle:(id)arg1;
- (id)adManager;
- (void)setAdManager:(id)arg1;
- (void)loss:(id)arg1 lossReason:(id)arg2 winBidder:(id)arg3;
- (void)win:(id)arg1;
- (void)setPrice:(id)arg1;
- (id)biddingToken;
- (void)setMopubAdMarkUp:(id)arg1;
- (void)setAdMarkup:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

