//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSDate, NSNumber, NSString;

@interface CSJSDKLocation : NSObject <CLLocationManagerDelegate>
{
    NSNumber *_latitude;
    NSNumber *_longitude;
    CLLocationManager *_locationManager;
    NSDate *_latestUpdateTimestamp;
    struct CLLocationCoordinate2D _latestLocation;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)locationService;
- (void).cxx_destruct;
@property(nonatomic) struct CLLocationCoordinate2D latestLocation; // @synthesize latestLocation=_latestLocation;
@property(retain, nonatomic) NSDate *latestUpdateTimestamp; // @synthesize latestUpdateTimestamp=_latestUpdateTimestamp;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain) NSNumber *longitude; // @synthesize longitude=_longitude;
@property(retain) NSNumber *latitude; // @synthesize latitude=_latitude;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (id)downNumber:(double)arg1;
- (_Bool)serviceEnable;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)asyncStartUpdate;
- (void)requestLatestStatus;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

