//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;

@interface CSJSchemeDetector : NSObject
{
    unsigned long long _activity;
    NSArray *_Bool_UIFile;
    long long _state;
    unsigned long long _Tmp_CaseId;
    NSMutableArray *_Cid_AKeyIOS;
    NSMutableArray *_To_MapPush;
    struct __CFRunLoopObserver *_observer;
    CDUnknownBlockType _completion;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) struct __CFRunLoopObserver *observer; // @synthesize observer=_observer;
@property(retain, nonatomic) NSMutableArray *To_MapPush; // @synthesize To_MapPush=_To_MapPush;
@property(retain, nonatomic) NSMutableArray *Cid_AKeyIOS; // @synthesize Cid_AKeyIOS=_Cid_AKeyIOS;
@property(nonatomic) unsigned long long Tmp_CaseId; // @synthesize Tmp_CaseId=_Tmp_CaseId;
@property(nonatomic) long long state; // @synthesize state=_state;
@property(copy, nonatomic) NSArray *Bool_UIFile; // @synthesize Bool_UIFile=_Bool_UIFile;
@property(nonatomic) unsigned long long activity; // @synthesize activity=_activity;
- (void)dealloc;
- (void)Need_ListJs;
- (void)Icon_MITSize;
- (void)start:(CDUnknownBlockType)arg1;
- (id)init;

@end

