//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface CSJTemplateResourceArchiveModel : NSObject
{
    NSString *_md5;
    NSString *_localUrl;
    NSString *_url;
    NSDictionary *_map;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSDictionary *map; // @synthesize map=_map;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *localUrl; // @synthesize localUrl=_localUrl;
@property(copy, nonatomic) NSString *md5; // @synthesize md5=_md5;
- (_Bool)valid;
- (id)dictionaryValue;
- (id)init;
- (id)initWithDicitonary:(id)arg1;

@end

