//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJRewardFullScreenBaseVM.h"

#import "CSJRewardedVideoWebViewDelegate-Protocol.h"
#import "CSJUgenAggregationAdapterDataSource-Protocol.h"
#import "CSJUgenAggregationAdapterDelegate-Protocol.h"
#import "CSJUgenAggregationLifeCycleProtocol-Protocol.h"

@class CSJAdInfoViewModel, CSJUgenAggregationAdapter, NSString;

@interface CSJUgenAggregationVM : CSJRewardFullScreenBaseVM <CSJUgenAggregationAdapterDataSource, CSJUgenAggregationAdapterDelegate, CSJRewardedVideoWebViewDelegate, CSJUgenAggregationLifeCycleProtocol>
{
    CSJAdInfoViewModel *_ugenAggregationInfoViewModel;
    CSJUgenAggregationAdapter *_aggregationAdapter;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJUgenAggregationAdapter *aggregationAdapter; // @synthesize aggregationAdapter=_aggregationAdapter;
@property(retain, nonatomic) CSJAdInfoViewModel *ugenAggregationInfoViewModel; // @synthesize ugenAggregationInfoViewModel=_ugenAggregationInfoViewModel;
- (void)vmAggregationViewDidDisappear;
- (void)vmAggregationViewDidAppear;
- (void)vmAggregationViewDidLoad;
- (void)X1_PosKey;
- (void)browseEcomAlertCancleAction;
- (void)browseEcomAlertSureAction;
- (void)setIsShowAlertView:(_Bool)arg1;
@property(nonatomic) _Bool aggregationPlayableRenderFailed;
@property(nonatomic) _Bool aggregationLoadingViewMute;
- (id)aggregationCurrentWebVC;
- (void)aggregationShowDislikeFeedback;
- (void)aggregationUpdateSlientBtnState:(_Bool)arg1;
- (void)aggregationRewardedVideoH5AdDidClickNeedJump:(_Bool)arg1;
- (void)aggregationSwitchToWebViewMute:(_Bool)arg1;
- (id)aggregationRewardedVideoAd;
- (void)showAggregationRewardBrowseEcomAlert:(id)arg1;
- (_Bool)isAggregationShowRewardBrowseEcomAlert;
- (id)closeButtonForLoadingView;
- (id)dislikeButtonForLoadingView;
- (id)ugenAggregationViewController;
- (id)ugenAggregationRootVC;
- (id)initLAt_KeyTm:(id)arg1 rootViewController:(id)arg2 slot:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

