//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CSJUgenAggregationAdapter.h"

@class CSJRewardedAgianAlertView;

@interface CSJUgenAggregationLUAdapter : CSJUgenAggregationAdapter
{
    _Bool _showOnceLU;
    _Bool _isShowLUAlert;
    CSJRewardedAgianAlertView *_alert;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CSJRewardedAgianAlertView *alert; // @synthesize alert=_alert;
@property(nonatomic) _Bool isShowLUAlert; // @synthesize isShowLUAlert=_isShowLUAlert;
@property(nonatomic) _Bool showOnceLU; // @synthesize showOnceLU=_showOnceLU;
- (void)pbu_showRewardLuSearchAlert;
- (_Bool)pbu_shouldShowLuSeachAlert;
- (void)invalidateCountDown;
- (void)scheduleCountDown;
- (_Bool)isValidCountDown;
- (void)resumeCountDown;
- (void)pauseCountDown;
- (long long)ugenAggregationTopBarStyle;
- (_Bool)shouldShowUgenAggregationAlert;
- (void)ugenAggregationSendReward;
- (void)ugenAggregationContentViewClose;
- (void)ugenAggregationGuidePageRender;
- (void)ugenAggregationCountDownWidgetRender;
- (void)ugenAggregationTopBarRender;
- (void)ugenAggregationContentViewRender;
- (void)ugenContentView:(id)arg1 event:(id)arg2;
- (void)ugenContentView:(id)arg1 loadFailWithInfo:(id)arg2 error:(id)arg3;
- (void)ugenContentView:(id)arg1 loadFinishWithInfo:(id)arg2;
- (void)ugenContentView:(id)arg1 loadStartWithInfo:(id)arg2;
- (void)vmAggregationViewDidDisappear;
- (void)vmAggregationViewDidAppear;
- (void)vmAggregationViewDidLoad;
- (void)vmAggregationLoadData;

@end

