//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BUWKWebView.h"

#import "WKScriptMessageHandler-Protocol.h"

@class BUThreadSafeDictionary, BUThreadSafeMutableArray, CSJAdInfoViewModel, CSJMaterialMeta, NSMutableArray, NSMutableDictionary, NSString;
@protocol CSJWKWebViewClientInterceptionDelegate, CSJWKWebViewClientResponseDelegate;

@interface CSJWKWebViewClient : BUWKWebView <WKScriptMessageHandler>
{
    _Bool _reallyRenderSuccess;
    _Bool _haveTouched;
    _Bool _didShow;
    _Bool _offlineMode;
    BUThreadSafeMutableArray *_interceptArray;
    CSJMaterialMeta *_targetMaterialMeta;
    CSJAdInfoViewModel *_targetInfoViewModel;
    double _startLoadTime;
    BUThreadSafeMutableArray *_interceptResourceList;
    id <CSJWKWebViewClientInterceptionDelegate> _interceptDelegate;
    id <CSJWKWebViewClientResponseDelegate> _responseDelegate;
    CDUnknownBlockType _jsCallNativeBlock;
    NSMutableDictionary *_jsOperationMap;
    BUThreadSafeDictionary *_logDictinary;
    NSMutableArray *_scriptMessageHandlerNameArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *scriptMessageHandlerNameArray; // @synthesize scriptMessageHandlerNameArray=_scriptMessageHandlerNameArray;
@property(retain, nonatomic) BUThreadSafeDictionary *logDictinary; // @synthesize logDictinary=_logDictinary;
@property(retain, nonatomic) NSMutableDictionary *jsOperationMap; // @synthesize jsOperationMap=_jsOperationMap;
@property(nonatomic) _Bool offlineMode; // @synthesize offlineMode=_offlineMode;
@property(copy, nonatomic) CDUnknownBlockType jsCallNativeBlock; // @synthesize jsCallNativeBlock=_jsCallNativeBlock;
@property(nonatomic) _Bool didShow; // @synthesize didShow=_didShow;
@property(nonatomic) _Bool haveTouched; // @synthesize haveTouched=_haveTouched;
@property(nonatomic) __weak id <CSJWKWebViewClientResponseDelegate> responseDelegate; // @synthesize responseDelegate=_responseDelegate;
@property(nonatomic) __weak id <CSJWKWebViewClientInterceptionDelegate> interceptDelegate; // @synthesize interceptDelegate=_interceptDelegate;
@property(retain, nonatomic) BUThreadSafeMutableArray *interceptResourceList; // @synthesize interceptResourceList=_interceptResourceList;
@property(nonatomic) double startLoadTime; // @synthesize startLoadTime=_startLoadTime;
@property(nonatomic) _Bool reallyRenderSuccess; // @synthesize reallyRenderSuccess=_reallyRenderSuccess;
@property(retain, nonatomic) CSJAdInfoViewModel *targetInfoViewModel; // @synthesize targetInfoViewModel=_targetInfoViewModel;
@property(retain, nonatomic) CSJMaterialMeta *targetMaterialMeta; // @synthesize targetMaterialMeta=_targetMaterialMeta;
@property(retain, nonatomic) BUThreadSafeMutableArray *interceptArray; // @synthesize interceptArray=_interceptArray;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)addPCMEventAttributionView;
- (double)getCurrentTime;
- (id)getInterceptResourceListDictWithStartTime:(double)arg1 url:(id)arg2 data:(id)arg3 extraDic:(id)arg4;
- (id)getInterceptDictWithStartTime:(double)arg1 url:(id)arg2 type:(id)arg3 isCache:(_Bool)arg4 extraDic:(id)arg5;
- (void)setCurrentLogType:(id)arg1 extraDic:(id)arg2;
- (void)pbu_removeAllScriptMessageHandlerAndUserScripts;
- (void)pbu_fireEvent:(id)arg1 params:(id)arg2;
- (void)pbu_postMessage:(id)arg1;
- (void)pbu_initJSB3Info;
- (void)ttr_fireEvent:(id)arg1 data:(id)arg2;
- (void)addScriptMessageWithHandler:(id)arg1 name:(id)arg2;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)dealloc;
- (struct CGRect)adjustFrameIfNeed:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 offlineMode:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

