//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CSJWKWebViewClient;

@interface CSJWebViewOwner : NSObject
{
    _Bool _isCache;
    CSJWKWebViewClient *_webViewClient;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isCache; // @synthesize isCache=_isCache;
@property(retain, nonatomic) CSJWKWebViewClient *webViewClient; // @synthesize webViewClient=_webViewClient;
- (void)dealloc;
- (id)initWithWebViewClient:(id)arg1 isCache:(_Bool)arg2;

@end

