//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface CSJWKURLSchemeTaskHandlerManager : NSObject
{
    NSMutableDictionary *_handlerDic;
    long long _count;
}

+ (id)sharedInstance;
+ (void)webView:(id)arg1 stopURLSchemeTask:(id)arg2;
+ (void)webView:(id)arg1 startURLSchemeTask:(id)arg2;
- (void).cxx_destruct;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(retain, nonatomic) NSMutableDictionary *handlerDic; // @synthesize handlerDic=_handlerDic;
- (id)p_handlerKey:(id)arg1 task:(id)arg2;
- (void)webView:(id)arg1 stopURLSchemeTask:(id)arg2;
- (void)webView:(id)arg1 startURLSchemeTask:(id)arg2;
- (id)init;

@end

