//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol CSJWebViewDynamicRenderDelegate;

@protocol CSJWebViewDynamicRenderInterface <NSObject>
@property(nonatomic) __weak id <CSJWebViewDynamicRenderDelegate> May_NOFtc;
- (double)Nb_BeADX;
- (void)Hash_A0Meta;
- (long long)An_SelfGDPR;
@end

