//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class DiscoverViewController, NSDictionary, UIImageView;

@interface DiscoverButton : UIButton
{
    UIImageView *_iconImageView;
    NSDictionary *_data;
    DiscoverViewController *_controller;
}

- (void).cxx_destruct;
@property(nonatomic) __weak DiscoverViewController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void)buttonAction;

@end

