//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface DiscoverModel : NSObject
{
    _Bool _isFinshAd;
    _Bool _hideNavRightItem;
    _Bool _needLogin;
    _Bool _needPresent;
    long long _style;
    NSString *_title;
    NSString *_subTitle;
    NSString *_lookAllTitle;
    NSString *_lookAllLink;
    NSString *_imgURL;
    NSString *_detailURL;
    NSString *_detailTitle;
    NSString *_appID;
    NSString *_btnTitle;
    NSString *_t1;
    NSString *_t2;
    NSString *_t3;
    NSString *_t4;
    NSString *_t5;
    NSMutableArray *_dataArray;
    double _sectionHeight;
    double _adHeight;
    NSString *_module;
    double _maxPricePeriodWidth;
    NSString *_theme_img_fill;
    NSString *_theme_img_stroke;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *theme_img_stroke; // @synthesize theme_img_stroke=_theme_img_stroke;
@property(copy, nonatomic) NSString *theme_img_fill; // @synthesize theme_img_fill=_theme_img_fill;
@property(nonatomic) double maxPricePeriodWidth; // @synthesize maxPricePeriodWidth=_maxPricePeriodWidth;
@property(copy, nonatomic) NSString *module; // @synthesize module=_module;
@property(nonatomic) _Bool needPresent; // @synthesize needPresent=_needPresent;
@property(nonatomic) _Bool needLogin; // @synthesize needLogin=_needLogin;
@property(nonatomic) _Bool hideNavRightItem; // @synthesize hideNavRightItem=_hideNavRightItem;
@property(nonatomic) _Bool isFinshAd; // @synthesize isFinshAd=_isFinshAd;
@property(nonatomic) double adHeight; // @synthesize adHeight=_adHeight;
@property(nonatomic) double sectionHeight; // @synthesize sectionHeight=_sectionHeight;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(copy, nonatomic) NSString *t5; // @synthesize t5=_t5;
@property(copy, nonatomic) NSString *t4; // @synthesize t4=_t4;
@property(copy, nonatomic) NSString *t3; // @synthesize t3=_t3;
@property(copy, nonatomic) NSString *t2; // @synthesize t2=_t2;
@property(copy, nonatomic) NSString *t1; // @synthesize t1=_t1;
@property(copy, nonatomic) NSString *btnTitle; // @synthesize btnTitle=_btnTitle;
@property(copy, nonatomic) NSString *appID; // @synthesize appID=_appID;
@property(copy, nonatomic) NSString *detailTitle; // @synthesize detailTitle=_detailTitle;
@property(copy, nonatomic) NSString *detailURL; // @synthesize detailURL=_detailURL;
@property(copy, nonatomic) NSString *imgURL; // @synthesize imgURL=_imgURL;
@property(copy, nonatomic) NSString *lookAllLink; // @synthesize lookAllLink=_lookAllLink;
@property(copy, nonatomic) NSString *lookAllTitle; // @synthesize lookAllTitle=_lookAllTitle;
@property(copy, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long style; // @synthesize style=_style;

@end

