//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FamilyViewController.h"

#import "UIScrollViewDelegate-Protocol.h"

@class AdjustButton, FamilyChartDetailTableView, FamilyChartSegmentView, FamilyChartView, FamilyDateManager, FamilyTypeChooseView, NSString, UIButton, UILabel, UISegmentedControl, UIView;

@interface FamilyChartViewController : FamilyViewController <UIScrollViewDelegate>
{
    AdjustButton *_titleBtn;
    UIButton *_rightBtn;
    UIView *_topView;
    UISegmentedControl *_segmentControl;
    FamilyDateManager *_dateManager;
    FamilyChartSegmentView *_segmentView;
    FamilyChartDetailTableView *_tableView;
    FamilyChartView *_chartView;
    UIView *_pieheaderline;
    UILabel *_typeLabel;
    _Bool _fromMediator;
    double _tabBarHeight;
    _Bool _chartDetail;
    _Bool _isPie;
    NSString *_typeName;
    long long _tallyType;
    long long _dateType;
    NSString *_date;
    NSString *_currentDate;
    double _typeSumAmount;
    NSString *_previousDate;
    FamilyTypeChooseView *_typeChooseView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FamilyTypeChooseView *typeChooseView; // @synthesize typeChooseView=_typeChooseView;
@property(copy, nonatomic) NSString *previousDate; // @synthesize previousDate=_previousDate;
@property(nonatomic) _Bool isPie; // @synthesize isPie=_isPie;
@property(nonatomic) double typeSumAmount; // @synthesize typeSumAmount=_typeSumAmount;
@property(copy, nonatomic) NSString *currentDate; // @synthesize currentDate=_currentDate;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
@property(nonatomic) long long dateType; // @synthesize dateType=_dateType;
@property(nonatomic) long long tallyType; // @synthesize tallyType=_tallyType;
@property(copy, nonatomic) NSString *typeName; // @synthesize typeName=_typeName;
@property(nonatomic, getter=isChartDetail) _Bool chartDetail; // @synthesize chartDetail=_chartDetail;
- (void)destroyNotification;
- (void)responseNotification:(id)arg1;
- (void)registerNotification;
- (void)refreshWithTheme;
- (void)adjustSegmentControlSelectIndex:(long long)arg1;
- (void)adjustTallyType:(long long)arg1;
- (void)addChartIncomeShortcuts;
- (void)typeChooseAction;
- (void)dateTypeChange:(id)arg1;
- (void)updateTallyTypeLabel;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

