//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FamilyViewController.h"

@class FamilySurplusView, NSString;

@interface FamilySurplusController : FamilyViewController
{
    NSString *_year;
    FamilySurplusView *_surplusView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FamilySurplusView *surplusView; // @synthesize surplusView=_surplusView;
@property(copy, nonatomic) NSString *year; // @synthesize year=_year;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

