//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FamilyDetailsBudgetItemLabel, NSString, PieChartView;

@interface FamilyDetailsBudgetItemView : UIView
{
    NSString *_date;
    double _budget;
    double _expend;
    PieChartView *_pieView;
    UIView *_conView;
    FamilyDetailsBudgetItemLabel *_lab1;
    UIView *_lineView;
    FamilyDetailsBudgetItemLabel *_lab2;
    FamilyDetailsBudgetItemLabel *_lab3;
    FamilyDetailsBudgetItemLabel *_lab4;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FamilyDetailsBudgetItemLabel *lab4; // @synthesize lab4=_lab4;
@property(retain, nonatomic) FamilyDetailsBudgetItemLabel *lab3; // @synthesize lab3=_lab3;
@property(retain, nonatomic) FamilyDetailsBudgetItemLabel *lab2; // @synthesize lab2=_lab2;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) FamilyDetailsBudgetItemLabel *lab1; // @synthesize lab1=_lab1;
@property(retain, nonatomic) UIView *conView; // @synthesize conView=_conView;
@property(retain, nonatomic) PieChartView *pieView; // @synthesize pieView=_pieView;
@property(nonatomic) double expend; // @synthesize expend=_expend;
@property(nonatomic) double budget; // @synthesize budget=_budget;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
- (void)reloadDataWithBudgetDetail:(id)arg1 sameDate:(_Bool)arg2;
- (void)reloadDataWithBudget:(id)arg1 sameDate:(_Bool)arg2;
- (void)reloadData;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

