//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSString, UIButton;

@interface FCXLeftPanController : UIViewController <UIGestureRecognizerDelegate>
{
    _Bool _isTransform;
    UIViewController *_leftController;
    UIViewController *_mainController;
    double _leftWidth;
    UIButton *_coverBtn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UIButton *coverBtn; // @synthesize coverBtn=_coverBtn;
@property(nonatomic) double leftWidth; // @synthesize leftWidth=_leftWidth;
@property(retain, nonatomic) UIViewController *mainController; // @synthesize mainController=_mainController;
@property(retain, nonatomic) UIViewController *leftController; // @synthesize leftController=_leftController;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)panGestureAction:(id)arg1;
- (void)showMain;
- (void)showLeft;
- (void)edgePanGestureActon:(id)arg1;
- (void)viewDidLoad;
- (id)initWithLeftController:(id)arg1 mainController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

