//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADEventContextSource-Protocol.h"

@class GADEventContext, GADObserverCollection, GADResourceBuffer, GADVideoConfiguration, GADWebAdView, NSString, NSTimer, NSURL;
@protocol OS_dispatch_queue;

@interface GADPrecacheResourceMonitor : NSObject <GADEventContextSource>
{
    GADWebAdView *_adView;
    NSObject<OS_dispatch_queue> *_lockQueue;
    GADObserverCollection *_resourceBufferObservers;
    GADResourceBuffer *_resourceBuffer;
    unsigned long long _byteThresholdToNotify;
    GADVideoConfiguration *_videoConfiguration;
    NSTimer *_resourceBufferNotifyUpdateTimer;
    GADEventContext *_context;
    long long _lastNotifiedBytes;
    NSURL *_videoSourceURL;
}

- (void).cxx_destruct;
@property(readonly) NSURL *videoSourceURL; // @synthesize videoSourceURL=_videoSourceURL;
@property(readonly, nonatomic) GADEventContext *context;
- (void)notifyPrecacheEvent:(id)arg1;
- (void)notifyPrecacheCompletedWithError:(id)arg1;
- (void)notifyPrecacheUpdate;
- (void)stopResourceBufferUpdateCheckTimer;
- (void)handleResourceBufferNotification:(id)arg1;
- (void)startPrecachingWithRequest:(id)arg1 fileURL:(id)arg2;
- (void)abort;
- (void)handlePrecacheAction:(id)arg1;
@property(readonly) GADResourceBuffer *resourceBuffer;
- (void)dealloc;
- (id)initWithWebAdView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

