//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTAdWKWebView;

@interface GDTBridge : NSObject
{
    GDTAdWKWebView *_webView;
}

@property(nonatomic) __weak GDTAdWKWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)GDTfunctione5OPRJ:(id)arg1;
- (id)GDTfunctionl8aILZ:(id)arg1;
- (_Bool)GDTfunctionj6oS8Y:(id)arg1;
- (void)GDTfunctiong3h2UF:(id)arg1;
- (void)GDTfunctionr9EUIJ:(id)arg1;
- (id)initLl4OnYe:(id)arg1;

@end

