//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;

@protocol GDTBizVideoPlayerViewDelegate <NSObject>

@optional
- (void)GDTfunctionw6Iw5t:(double)arg1 totalTime:(double)arg2;
- (void)GDTfunctionl5yTb5:(double)arg1 duration:(double)arg2;
- (void)GDTfunctionx4p7s2:(NSError *)arg1;
- (void)GDTfunctionn02bRg;
- (void)GDTfunctionl7tQCa;
- (void)GDTfunctiony2gpoy;
- (void)GDTfunctionp1B2XM:(unsigned long long)arg1 duration:(long long)arg2;
@end

