//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTDLBusinessWidget.h"

@class GDTLogoView;

@interface GDTDLAdLogoView : GDTDLBusinessWidget
{
    _Bool _needUpdateIcon;
    GDTLogoView *_logoView;
    long long _iconType;
    long long _contentMode;
}

@property(nonatomic) _Bool needUpdateIcon; // @synthesize needUpdateIcon=_needUpdateIcon;
@property(nonatomic) long long contentMode; // @synthesize contentMode=_contentMode;
@property(nonatomic) long long iconType; // @synthesize iconType=_iconType;
@property(retain, nonatomic) GDTLogoView *logoView; // @synthesize logoView=_logoView;
- (void).cxx_destruct;
- (void)GDTfunctiong2OvFN;
- (void)GDTfunctiony0O6pF;
- (_Bool)GDTfunctiono933aW:(id)arg1 value:(id)arg2;
- (id)cocoaView;
- (id)init;

@end

