//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QuartzCore/CALayer.h>

@class UIColor;

@interface GDTDLLayer : CALayer
{
    double _dl_borderRadius;
    double _dl_borderTopLeftRadius;
    double _dl_borderTopRightRadius;
    double _dl_borderBottomLeftRadius;
    double _dl_borderBottomRightRadius;
    double _dl_borderWidth;
    UIColor *_dl_borderColor;
    UIColor *_dl_backgroundColor;
    double _width;
    double _height;
}

@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double width; // @synthesize width=_width;
@property(retain, nonatomic) UIColor *dl_backgroundColor; // @synthesize dl_backgroundColor=_dl_backgroundColor;
@property(retain, nonatomic) UIColor *dl_borderColor; // @synthesize dl_borderColor=_dl_borderColor;
@property(nonatomic) double dl_borderWidth; // @synthesize dl_borderWidth=_dl_borderWidth;
@property(nonatomic) double dl_borderBottomRightRadius; // @synthesize dl_borderBottomRightRadius=_dl_borderBottomRightRadius;
@property(nonatomic) double dl_borderBottomLeftRadius; // @synthesize dl_borderBottomLeftRadius=_dl_borderBottomLeftRadius;
@property(nonatomic) double dl_borderTopRightRadius; // @synthesize dl_borderTopRightRadius=_dl_borderTopRightRadius;
@property(nonatomic) double dl_borderTopLeftRadius; // @synthesize dl_borderTopLeftRadius=_dl_borderTopLeftRadius;
@property(nonatomic) double dl_borderRadius; // @synthesize dl_borderRadius=_dl_borderRadius;
- (void).cxx_destruct;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)createPath:(struct CGContext *)arg1;
@property(readonly, nonatomic) struct CGSize dl_size; // @dynamic dl_size;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)init;

@end

