//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTDLBusinessWidget.h"

#import "GDTLandpageVideoModuleViewDelegate-Protocol.h"

@class GDTDLRootView, GDTLandingPageVideoModuleView, NSString;

@interface GDTDLLandingPageVideoView : GDTDLBusinessWidget <GDTLandpageVideoModuleViewDelegate>
{
    _Bool _needLayout;
    _Bool _hasReportClicked;
    _Bool _videoWindowEnable;
    GDTLandingPageVideoModuleView *_landPageVideoView;
    GDTDLRootView *_rootView;
    double _videoShowMinSpace;
    double _videoAdsorbRatio;
    double _verticalVideoHeight;
    double _videoMoveType;
    double _videoWindowWidth;
    double _videoWindowLeft;
    double _videoWindowRight;
    double _videoWindowTop;
    double _videoWindowBottom;
}

@property(nonatomic) double videoWindowBottom; // @synthesize videoWindowBottom=_videoWindowBottom;
@property(nonatomic) double videoWindowTop; // @synthesize videoWindowTop=_videoWindowTop;
@property(nonatomic) double videoWindowRight; // @synthesize videoWindowRight=_videoWindowRight;
@property(nonatomic) double videoWindowLeft; // @synthesize videoWindowLeft=_videoWindowLeft;
@property(nonatomic) double videoWindowWidth; // @synthesize videoWindowWidth=_videoWindowWidth;
@property(nonatomic) _Bool videoWindowEnable; // @synthesize videoWindowEnable=_videoWindowEnable;
@property(nonatomic) double videoMoveType; // @synthesize videoMoveType=_videoMoveType;
@property(nonatomic) double verticalVideoHeight; // @synthesize verticalVideoHeight=_verticalVideoHeight;
@property(nonatomic) double videoAdsorbRatio; // @synthesize videoAdsorbRatio=_videoAdsorbRatio;
@property(nonatomic) double videoShowMinSpace; // @synthesize videoShowMinSpace=_videoShowMinSpace;
@property(nonatomic) _Bool hasReportClicked; // @synthesize hasReportClicked=_hasReportClicked;
@property(nonatomic) __weak GDTDLRootView *rootView; // @synthesize rootView=_rootView;
@property(nonatomic) _Bool needLayout; // @synthesize needLayout=_needLayout;
@property(retain, nonatomic) GDTLandingPageVideoModuleView *landPageVideoView; // @synthesize landPageVideoView=_landPageVideoView;
- (void).cxx_destruct;
- (void)GDTfunctione0qE6V:(id)arg1;
- (void)GDTfunctionu6g2TR:(id)arg1 clicked:(id)arg2;
- (double)videoHeight;
- (struct CGRect)GDTfunctionr4x6zf;
- (_Bool)isVerticalVideo;
- (void)GDTfunctiong2OvFN;
- (_Bool)GDTfunctiond65EUh;
- (void)GDTfunctiont0uUMI:(id)arg1;
- (_Bool)GDTfunctiono933aW:(id)arg1 value:(id)arg2;
- (void)setAdModel:(id)arg1;
- (id)cocoaView;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

