//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTDLBusinessWidget.h"

@class GDTVideoProgressView;

@interface GDTDLProgressView : GDTDLBusinessWidget
{
    GDTVideoProgressView *_progressView;
}

@property(retain, nonatomic) GDTVideoProgressView *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;
- (_Bool)GDTfunctiono933aW:(id)arg1 value:(id)arg2;
- (id)cocoaView;
- (id)init;

@end

