//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTPODS_Reachability, NSMutableArray, NSString, NSTimer;
@protocol GDTEventReporterDelegate;

@interface GDTEventReporter : NSObject
{
    _Bool _isWorking;
    unsigned long long _reportInterval;
    unsigned long long _batchCount;
    unsigned long long _maxReportCount;
    long long _failureRertyCount;
    NSString *_serverURL;
    id <GDTEventReporterDelegate> _delegate;
    NSTimer *_timer;
    GDTPODS_Reachability *_reachability;
    NSMutableArray *_pendingEvents;
}

@property(retain, nonatomic) NSMutableArray *pendingEvents; // @synthesize pendingEvents=_pendingEvents;
@property(nonatomic) _Bool isWorking; // @synthesize isWorking=_isWorking;
@property(retain, nonatomic) GDTPODS_Reachability *reachability; // @synthesize reachability=_reachability;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak id <GDTEventReporterDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *serverURL; // @synthesize serverURL=_serverURL;
@property(nonatomic) long long failureRertyCount; // @synthesize failureRertyCount=_failureRertyCount;
@property(nonatomic) unsigned long long maxReportCount; // @synthesize maxReportCount=_maxReportCount;
@property(nonatomic) unsigned long long batchCount; // @synthesize batchCount=_batchCount;
@property(nonatomic) unsigned long long reportInterval; // @synthesize reportInterval=_reportInterval;
- (void).cxx_destruct;
- (id)GDTfunctiona5uNit:(id)arg1 length:(long long)arg2;
- (void)GDTfunctionm3Scti;
- (void)GDTfunctionj7Xe9i;
- (_Bool)GDTfunctionp7jCZN;
- (void)GDTfunctioni5YYhx;
- (void)GDTfunctiont2HViP;
- (void)GDTfunctiony1CWEM;
- (void)GDTfunctionu7wtun:(id)arg1;
- (void)didBecomeActive:(id)arg1;
- (void)didEnterBackground:(id)arg1;
- (void)GDTfunctioni0FcwV;
- (void)GDTfunctionk1YZ6W;
- (void)stop;
- (void)start;
- (void)GDTfunctiong52KTE:(id)arg1;
- (void)dealloc;
- (id)init;

@end

