//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GDTExpressView, NSDictionary;

@protocol GDTExpressViewDelegate <NSObject>

@optional
- (void)GDTfunctions14Ftc:(GDTExpressView *)arg1 rewardReduceTime:(long long)arg2 infoBlock:(void (^)(long long, long long))arg3;
- (void)GDTfunctionv4FeYI:(GDTExpressView *)arg1;
- (void)GDTfunctionf1KIgS:(GDTExpressView *)arg1;
- (void)GDTfunctions14Ftc:(GDTExpressView *)arg1 createVideoCorners:(unsigned long long)arg2 radius:(double)arg3;
- (void)GDTfunctiono8hPyC:(GDTExpressView *)arg1 finalAdSize:(struct CGSize)arg2 playerFrame:(struct CGRect)arg3;
- (void)GDTfunctionn9TW1q:(GDTExpressView *)arg1 forceCloseAd:(_Bool)arg2;
- (void)GDTfunctiono6BMDa:(GDTExpressView *)arg1 clickParamsFromH5:(NSDictionary *)arg2 CTAType:(long long)arg3;
- (void)GDTfunctionc4Rxrz:(GDTExpressView *)arg1 error:(unsigned long long)arg2;
- (void)GDTfunctionc2RUGZ:(GDTExpressView *)arg1 finalAdSize:(struct CGSize)arg2 playerFrame:(struct CGRect)arg3;
@end

