//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTAdContentViewProtocol-Protocol.h"
#import "GDTAdViewClickWithAntiSpamCheckerDelegate-Protocol.h"

@class GDTADActiveInformation, GDTADConfiguration, GDTAdViewClickWithAntiSpamChecker, GDTAntiSpamBusinessData, GDTAntiSpamClickData, GDTBizFeedVideoPlayerView, NSString, UIImageView, UILabel;
@protocol GDTAdContentViewDelegate;

@interface GDTInterstitialImageNativeView : UIView <GDTAdViewClickWithAntiSpamCheckerDelegate, GDTAdContentViewProtocol>
{
    _Bool _adViewIsValid;
    _Bool _viewVisible;
    GDTADConfiguration *_adConfig;
    GDTADActiveInformation *_adActiveInformation;
    id <GDTAdContentViewDelegate> _delegate;
    GDTBizFeedVideoPlayerView *_videoView;
    UIImageView *_nativeImageView;
    UIView *_gradientView;
    UIImageView *_arrowView;
    UILabel *_tipLabel;
    GDTAntiSpamBusinessData *_antiSpamBusinessData;
    GDTAntiSpamClickData *_clickData;
    GDTAdViewClickWithAntiSpamChecker *_clickChecker;
    struct CGPoint _beganPoint;
    struct CGPoint _endPoint;
}

@property(retain, nonatomic) GDTAdViewClickWithAntiSpamChecker *clickChecker; // @synthesize clickChecker=_clickChecker;
@property(retain, nonatomic) GDTAntiSpamClickData *clickData; // @synthesize clickData=_clickData;
@property(nonatomic) struct CGPoint endPoint; // @synthesize endPoint=_endPoint;
@property(nonatomic) struct CGPoint beganPoint; // @synthesize beganPoint=_beganPoint;
@property(retain, nonatomic) GDTAntiSpamBusinessData *antiSpamBusinessData; // @synthesize antiSpamBusinessData=_antiSpamBusinessData;
@property(nonatomic) _Bool viewVisible; // @synthesize viewVisible=_viewVisible;
@property(retain, nonatomic) UILabel *tipLabel; // @synthesize tipLabel=_tipLabel;
@property(retain, nonatomic) UIImageView *arrowView; // @synthesize arrowView=_arrowView;
@property(retain, nonatomic) UIView *gradientView; // @synthesize gradientView=_gradientView;
@property(retain, nonatomic) UIImageView *nativeImageView; // @synthesize nativeImageView=_nativeImageView;
@property(nonatomic) _Bool adViewIsValid; // @synthesize adViewIsValid=_adViewIsValid;
@property(nonatomic) __weak GDTBizFeedVideoPlayerView *videoView; // @synthesize videoView=_videoView;
@property(nonatomic) __weak id <GDTAdContentViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak GDTADActiveInformation *adActiveInformation; // @synthesize adActiveInformation=_adActiveInformation;
@property(nonatomic) __weak GDTADConfiguration *adConfig; // @synthesize adConfig=_adConfig;
- (void).cxx_destruct;
- (void)GDTfunctiong3Goz4:(id)arg1 didClickWithClickData:(id)arg2;
- (void)GDTfunctioni7u5Qz:(id)arg1;
- (void)GDTfunctionk1m2hH:(id)arg1;
- (void)GDTfunctionv8jVM4;
- (void)GDTfunctioni3f7aH;
- (void)GDTfunctionj25P4J;
- (void)GDTfunctionx4GChy:(id)arg1;
- (void)GDTfunctionc1ufc8;
- (void)GDTfunctiond3NURf;
- (void)GDTfunctiong0kIDm;
- (void)GDTfunctionb1nX7b;
- (id)initWithFrame:(struct CGRect)arg1 config:(id)arg2 adInfo:(id)arg3 delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

