//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTCustomFullScreenViewController.h"

#import "GDTFullScreenOverlayMediatorViewDelegate-Protocol.h"

@class GDTClickFacade, NSString;
@protocol GDTInterstitialFullScreenViewControllerDelegate;

@interface GDTInterstitialFullScreenViewController : GDTCustomFullScreenViewController <GDTFullScreenOverlayMediatorViewDelegate>
{
    _Bool _hadPlay;
    _Bool _hasLogVideoRmove;
    id <GDTInterstitialFullScreenViewControllerDelegate> _delegate;
    NSString *_placementId;
    GDTClickFacade *_clickFacade;
    GDTClickFacade *_clickOnlyReportFacade;
    long long _effectiveTime;
    long long _playFinished;
}

@property(nonatomic) _Bool hasLogVideoRmove; // @synthesize hasLogVideoRmove=_hasLogVideoRmove;
@property(nonatomic) _Bool hadPlay; // @synthesize hadPlay=_hadPlay;
@property(nonatomic) long long playFinished; // @synthesize playFinished=_playFinished;
@property(nonatomic) long long effectiveTime; // @synthesize effectiveTime=_effectiveTime;
@property(retain, nonatomic) GDTClickFacade *clickOnlyReportFacade; // @synthesize clickOnlyReportFacade=_clickOnlyReportFacade;
@property(retain, nonatomic) GDTClickFacade *clickFacade; // @synthesize clickFacade=_clickFacade;
@property(retain, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(nonatomic) __weak id <GDTInterstitialFullScreenViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)GDTfunctionl3GyrH;
- (id)GDTfunctionw8CBtL:(id)arg1;
- (void)GDTfunctiona9BodP;
- (void)GDTfunctionv8jVM4;
- (struct CGPoint)closeButtonClickPoint;
- (void)GDTfunctionu55onA:(id)arg1 clickArea:(long long)arg2;
- (void)GDTfunctioni6vqSk:(_Bool)arg1;
- (void)GDTfunctionv2BYGn;
- (void)GDTfunctionr5BvRD;
- (void)GDTfunctionu2fhVF;
- (void)GDTfunctionc6ZP0L;
- (void)GDTfunctiond6SHvo:(unsigned long long)arg1;
- (void)GDTfunctionp2griK:(double)arg1 totalTime:(double)arg2;
- (void)GDTfunctionn7LY4V;
- (void)GDTfunctioni6XLyw;
- (void)GDTfunctiond4adpo;
- (void)GDTfunctionn3Hg6g;
- (void)GDTfunctionb8V1lD;
- (void)GDTfunctionb4qvLp:(id)arg1;
- (void)GDTfunctionn7rszq;
- (void)GDTfunctionl5xTAW:(id)arg1 clickArea:(long long)arg2;
- (void)GDTfunctionj1gdZO;
- (void)GDTfunctionc19Wuj;
- (void)GDTfunctiont5MYIc:(id)arg1;
- (void)GDTfunctionw9UlGM:(id)arg1;
- (void)GDTfunctionu1aWwa:(id)arg1 bodyClicked:(id)arg2 clickAreaType:(long long)arg3;
- (void)GDTfunctionm9Nq7g:(id)arg1 forceCloseAd:(_Bool)arg2;
- (void)GDTfunctionl4zmpn:(id)arg1 didRenderFailWithError:(id)arg2;
- (void)GDTfunctiono3hKxO:(id)arg1;
- (void)GDTfunctionq7aEX9:(id)arg1 clickArea:(long long)arg2;
- (_Bool)prefersStatusBarHidden;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

