//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSExport-Protocol.h"

@class NSString;

@protocol GDTJSCoreBusinessManagerObjectJSExport <JSExport>
- (_Bool)GDTfunctionu0YfVP:(NSString *)arg1;
- (int)GDTfunctionw1nysD:(NSString *)arg1;
- (NSString *)GDTfunctionf8QUeX:(NSString *)arg1;
- (void)GDTfunctionv343XU:(NSString *)arg1;
- (void)GDTfunctiono2qYqO:(NSString *)arg1;
@end

