//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTActionWorkerDelegate-Protocol.h"

@class GDTActionWorker, GDTContentInfo, GDTMediaCacheWorker, NSString, NSURL, NSURLSessionDataTask;
@protocol GDTMediaDownloaderDelegate;

@interface GDTMediaDownloader : NSObject <GDTActionWorkerDelegate>
{
    _Bool _saveToCache;
    _Bool _videoHasCached;
    _Bool _downloadToEnd;
    NSURL *_url;
    id <GDTMediaDownloaderDelegate> _delegate;
    GDTContentInfo *_info;
    long long _cacheCount;
    NSString *_specifiedFileName;
    long long _tryCount;
    NSString *_customUA;
    NSURLSessionDataTask *_task;
    GDTMediaCacheWorker *_cacheWorker;
    GDTActionWorker *_actionWorker;
    double _downloadRatio;
}

@property(nonatomic) double downloadRatio; // @synthesize downloadRatio=_downloadRatio;
@property(nonatomic) _Bool downloadToEnd; // @synthesize downloadToEnd=_downloadToEnd;
@property(retain, nonatomic) GDTActionWorker *actionWorker; // @synthesize actionWorker=_actionWorker;
@property(retain, nonatomic) GDTMediaCacheWorker *cacheWorker; // @synthesize cacheWorker=_cacheWorker;
@property(retain, nonatomic) NSURLSessionDataTask *task; // @synthesize task=_task;
@property(nonatomic) _Bool videoHasCached; // @synthesize videoHasCached=_videoHasCached;
@property(copy, nonatomic) NSString *customUA; // @synthesize customUA=_customUA;
@property(nonatomic) long long tryCount; // @synthesize tryCount=_tryCount;
@property(readonly, copy, nonatomic) NSString *specifiedFileName; // @synthesize specifiedFileName=_specifiedFileName;
@property(nonatomic) long long cacheCount; // @synthesize cacheCount=_cacheCount;
@property(nonatomic) _Bool saveToCache; // @synthesize saveToCache=_saveToCache;
@property(retain, nonatomic) GDTContentInfo *info; // @synthesize info=_info;
@property(nonatomic) __weak id <GDTMediaDownloaderDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (_Bool)GDTfunctiond2CEl9;
- (void)actionWorker:(id)arg1 didFinishWithError:(id)arg2;
- (void)actionWorker:(id)arg1 didReceiveData:(id)arg2 isLocal:(_Bool)arg3;
- (void)actionWorker:(id)arg1 didReceiveResponse:(id)arg2;
- (void)GDTfunctionl2364S:(double)arg1;
- (void)cancel;
- (void)GDTfunctionp3w4MI;
- (id)GDTfunctionl1MPtw;
- (void)GDTfunctionr6behm:(unsigned long long)arg1 length:(unsigned long long)arg2 toEnd:(_Bool)arg3;
- (id)initWithURL:(id)arg1 specifiedFileName:(id)arg2;
- (id)initWithURL:(id)arg1;
- (void)dealloc;
@property(retain, nonatomic) id context;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

