//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTMNetworkConfigModel, NSTimer;
@protocol GDTMMediatorProtocol;

@interface GDTMAdapterLoader : NSObject
{
    _Bool _isLoading;
    id <GDTMMediatorProtocol> _mediator;
    CDUnknownBlockType _loadFinishBlock;
    GDTMNetworkConfigModel *_currentTopOne;
    long long _fetchFlag;
    double _timeout;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) double timeout; // @synthesize timeout=_timeout;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) long long fetchFlag; // @synthesize fetchFlag=_fetchFlag;
@property(readonly, nonatomic) GDTMNetworkConfigModel *currentTopOne; // @synthesize currentTopOne=_currentTopOne;
@property(copy, nonatomic) CDUnknownBlockType loadFinishBlock; // @synthesize loadFinishBlock=_loadFinishBlock;
@property(nonatomic) __weak id <GDTMMediatorProtocol> mediator; // @synthesize mediator=_mediator;
- (void).cxx_destruct;
- (void)GDTfunctioni5YYhx;
- (void)GDTfunctiony1CWEM;
- (id)GDTfunctionm9QKTq:(id)arg1;
- (id)GDTfunctionx2nUXs:(id)arg1;
- (void)GDTfunctionb2OqnI:(_Bool)arg1 forceFinish:(_Bool)arg2;
- (void)GDTfunctionb2OqnI:(id)arg1 filled:(_Bool)arg2 error:(id)arg3;
- (void)GDTfunctionr5jec6:(id)arg1;
- (void)stop;
- (void)start;
- (id)initLy1uzoh:(id)arg1;
- (void)dealloc;

@end

