//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface GDTMultiDelegateObject : NSObject
{
    NSMutableArray *_delegateArray;
}

@property(retain, nonatomic) NSMutableArray *delegateArray; // @synthesize delegateArray=_delegateArray;
- (void).cxx_destruct;
- (id)GDTfunctionk4cUfB;
- (void)removeDelegate:(id)arg1;
- (void)addDelegate:(id)arg1;
- (id)GDTfunctionx4PILO;
- (id)init;

@end

