//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTPlayer.h"

@class GDTAdBaseModel;

@interface GDTPlayer (Extension)
+ (void)load;
- (void)GDTfunctiona4FL1G:(id)arg1;
- (void)GDTfunctionh3jLsh:(id)arg1;
- (void)GDTfunctiond2H9Gv;
- (void)GDTfunctionk10fzO;
- (long long)GDTfunctionp8GwNc:(long long)arg1;
- (id)GDTfunctionv5sXIL:(id)arg1;
@property(nonatomic) __weak GDTAdBaseModel *adModel;
- (void)setGDTfunctionf0hGF9:(_Bool)arg1;
- (_Bool)GDTfunctionf0hGF9;
- (void)setIsCompleted:(_Bool)arg1;
- (_Bool)isCompleted;
- (void)setGDTfunctionf1FVjd:(unsigned long long)arg1;
- (unsigned long long)GDTfunctionf1FVjd;
- (void)setGDTfunctioni3IgHg:(_Bool)arg1;
- (_Bool)GDTfunctioni3IgHg;
- (void)pause:(_Bool)arg1;
- (void)play:(_Bool)arg1;
- (void)swi_dealloc;
- (void)GDTfunctionx4p4gw:(CDUnknownBlockType)arg1;
- (void)GDTfunctiont6O2za:(CDUnknownBlockType)arg1;
- (void)GDTfunctionf0K7gw:(CDUnknownBlockType)arg1;
- (void)GDTfunctiont3eazT:(unsigned long long)arg1;
- (void)GDTfunctione2K6Xo:(long long)arg1;
@end

