//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSError;

@protocol GDTRewardedVideoAdImpDelegate <NSObject>

@optional
- (void)GDTfunctionz4NLv8:(id)arg1;
- (void)GDTfunctionm11NXY:(id)arg1;
- (void)GDTfunctionm79tY2:(id)arg1 info:(NSDictionary *)arg2;
- (void)GDTfunctiono1cKyX:(id)arg1 didFailWithError:(NSError *)arg2;
- (void)GDTfunctiont3fwQq:(id)arg1;
- (void)GDTfunctionq5abg0:(id)arg1;
- (void)GDTfunctionh6cOGW:(id)arg1;
- (void)GDTfunctione0KCLK:(id)arg1;
- (void)GDTfunctiony5pzup:(id)arg1;
- (void)GDTfunctionk8U0GC:(id)arg1;
@end

