//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTAdBaseModel.h"

@interface GDTRewardVideoAdModel : GDTAdBaseModel
{
    _Bool _isDowngrade;
    long long _rewardType;
}

@property(nonatomic) _Bool isDowngrade; // @synthesize isDowngrade=_isDowngrade;
@property(nonatomic) long long rewardType; // @synthesize rewardType=_rewardType;
- (id)GDTfunctionf6sexg;
- (_Bool)isRewardPlay;
- (id)initLb56K1u:(id)arg1;

@end

