//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "GDTBizVideoPlayerViewDelegate-Protocol.h"
#import "GDTDLRootViewDelegate-Protocol.h"
#import "GDTSplashViewProtocol-Protocol.h"
#import "GDTVideoStoreViewControllerDelegate-Protocol.h"

@class GDTBizFeedVideoPlayerView, GDTDLBusinessManager, GDTPlayer, GDTSplashAdModel, GDTVideoViewRecorder, GDTWeakProxy, NSMutableDictionary, NSString;
@protocol GDTSplashViewDelegate><GDTSplashViewControllerDelegate;

@interface GDTSplashDLView : UIView <GDTDLRootViewDelegate, GDTBizVideoPlayerViewDelegate, GDTVideoStoreViewControllerDelegate, GDTSplashViewProtocol>
{
    _Bool _hasStartedPlay;
    id <GDTSplashViewDelegate><GDTSplashViewControllerDelegate> delegate;
    CDUnknownBlockType renderBlock;
    UIView *providerView;
    GDTDLBusinessManager *_manager;
    GDTSplashAdModel *_adModel;
    GDTPlayer *_player;
    GDTVideoViewRecorder *_recorder;
    GDTWeakProxy *_videoProxy;
    NSMutableDictionary *_dlDict;
    GDTBizFeedVideoPlayerView *_videoView;
}

@property(retain, nonatomic) GDTBizFeedVideoPlayerView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) NSMutableDictionary *dlDict; // @synthesize dlDict=_dlDict;
@property(retain, nonatomic) GDTWeakProxy *videoProxy; // @synthesize videoProxy=_videoProxy;
@property(nonatomic) _Bool hasStartedPlay; // @synthesize hasStartedPlay=_hasStartedPlay;
@property(retain, nonatomic) GDTVideoViewRecorder *recorder; // @synthesize recorder=_recorder;
@property(retain, nonatomic) GDTPlayer *player; // @synthesize player=_player;
@property(retain, nonatomic) GDTSplashAdModel *adModel; // @synthesize adModel=_adModel;
@property(retain, nonatomic) GDTDLBusinessManager *manager; // @synthesize manager=_manager;
@property(retain, nonatomic) UIView *providerView; // @synthesize providerView;
@property(copy, nonatomic) CDUnknownBlockType renderBlock; // @synthesize renderBlock;
@property(nonatomic) __weak id <GDTSplashViewDelegate><GDTSplashViewControllerDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (id)GDTfunctiong1iSqL;
- (void)GDTfunctionk3E2O0:(id)arg1;
- (void)GDTfunctionv3b6Oq:(id)arg1;
- (void)GDTfunctionl5yTb5:(double)arg1 duration:(double)arg2;
- (void)GDTfunctionx4p7s2:(id)arg1;
- (void)GDTfunctionl7tQCa;
- (void)GDTfunctionp1B2XM:(unsigned long long)arg1 duration:(long long)arg2;
- (void)GDTfunctionx3RNTb:(double)arg1;
- (void)GDTfunctiong9GptE;
- (void)GDTfunctione2tVkq;
- (void)GDTfunctionm4fHoo;
- (void)GDTfunctionh2xW2q:(_Bool)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)GDTfunctionf7FvBP;
- (void)GDTfunctiong99nEC;
- (id)initLk0QkxC:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

