//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class GDTSplashOverlayView;

@interface GDTSplashOverlaySubviewsManager : NSObject
{
    GDTSplashOverlayView *_overlay;
}

@property(nonatomic) __weak GDTSplashOverlayView *overlay; // @synthesize overlay=_overlay;
- (void).cxx_destruct;
- (id)adModel;
- (struct CGRect)GDTfunctionv20h3e;
- (struct CGRect)GDTfunctione4HYum;
- (long long)GDTfunctionz09wgJ;
- (_Bool)GDTfunctiono7D0pF;
- (id)initWithOverlay:(id)arg1;

@end

