//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTJSCoreBusinessManagerObjectDelegate-Protocol.h"
#import "GDTScriptCoreManagerDelegate-Protocol.h"

@class GDTDLBusinessManager, GDTJSCoreBusinessManagerObject, GDTJSCoreVideoPlayerObject, JSContext, JSVirtualMachine, NSString;

@interface GDTScriptCoreManager : NSObject <GDTJSCoreBusinessManagerObjectDelegate, GDTScriptCoreManagerDelegate>
{
    GDTDLBusinessManager *_businessManager;
    JSVirtualMachine *_virtualMachine;
    JSContext *_context;
    GDTJSCoreBusinessManagerObject *_businessManagerObject;
    GDTJSCoreVideoPlayerObject *_playerObject;
}

@property(retain, nonatomic) GDTJSCoreVideoPlayerObject *playerObject; // @synthesize playerObject=_playerObject;
@property(retain, nonatomic) GDTJSCoreBusinessManagerObject *businessManagerObject; // @synthesize businessManagerObject=_businessManagerObject;
@property(retain, nonatomic) JSContext *context; // @synthesize context=_context;
@property(retain, nonatomic) JSVirtualMachine *virtualMachine; // @synthesize virtualMachine=_virtualMachine;
@property(nonatomic) __weak GDTDLBusinessManager *businessManager; // @synthesize businessManager=_businessManager;
- (void).cxx_destruct;
- (id)videoPlayer;
- (id)adModel;
- (void)GDTfunctionv343XU:(id)arg1;
- (void)GDTfunctiono2qYqO:(id)arg1;
- (id)GDTfunctionn5K3Vp:(id)arg1 method:(id)arg2 arguments:(id)arg3;
- (id)GDTfunctionb5yylo:(id)arg1 arguments:(id)arg2;
- (void)evaluateScript:(id)arg1;
- (void)dealloc;
- (void)GDTfunctiony4YJ14:(id)arg1;
- (void)GDTfunctionf5HtaU:(id)arg1;
- (void)GDTfunctioni05i3M;
- (void)GDTfunctions5675z;
- (void)initLs9kXzP;
- (void)initLu7fHRY;
- (id)initLi3sOqk:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

