//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTBaseChainHandler.h"

#import "GDTDynamicChainHandlerProtocol-Protocol.h"

@class NSString;

@interface GDTTrackClickChainHandler : GDTBaseChainHandler <GDTDynamicChainHandlerProtocol>
{
}

- (void)GDTfunctiony6IOpg:(id)arg1;
- (void)GDTfunctionw2BrWt:(id)arg1 replacementData:(id)arg2 reportType:(long long)arg3;
- (void)GDTfunctionk0QJwG:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

