//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GDTTwistData : NSObject
{
    double _xTwistAngle;
    double _yTwistAngle;
    double _zTwistAngle;
    double _twistDuration;
}

@property(nonatomic) double twistDuration; // @synthesize twistDuration=_twistDuration;
@property(nonatomic) double zTwistAngle; // @synthesize zTwistAngle=_zTwistAngle;
@property(nonatomic) double yTwistAngle; // @synthesize yTwistAngle=_yTwistAngle;
@property(nonatomic) double xTwistAngle; // @synthesize xTwistAngle=_xTwistAngle;

@end

