//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GDTBaseAdAdapter.h"

#import "GDTUnifiedInterstitialAdImpDelegate-Protocol.h"
#import "GDTUnifiedinterstitialAdNetworkAdapterProtocol-Protocol.h"

@class GDTUnifiedInterstitialAdMediator, NSString;
@protocol GDTUnifiedInterstitialAdImpProtocol><GDTAdImpProtocol;

@interface GDTUnifiedInterstitialAdAdapter : GDTBaseAdAdapter <GDTUnifiedinterstitialAdNetworkAdapterProtocol, GDTUnifiedInterstitialAdImpDelegate>
{
    _Bool shouldLoadFullscreenAd;
    _Bool shouldShowFullscreenAd;
    GDTUnifiedInterstitialAdMediator *_connector;
    id <GDTUnifiedInterstitialAdImpProtocol><GDTAdImpProtocol> _interstitialAdImp;
    NSString *_posId;
}

+ (void)updateAppId:(id)arg1 extStr:(id)arg2;
@property(copy, nonatomic) NSString *posId; // @synthesize posId=_posId;
@property(retain, nonatomic) id <GDTUnifiedInterstitialAdImpProtocol><GDTAdImpProtocol> interstitialAdImp; // @synthesize interstitialAdImp=_interstitialAdImp;
@property(nonatomic) __weak GDTUnifiedInterstitialAdMediator *connector; // @synthesize connector=_connector;
@property(nonatomic) _Bool shouldShowFullscreenAd; // @synthesize shouldShowFullscreenAd;
@property(nonatomic) _Bool shouldLoadFullscreenAd; // @synthesize shouldLoadFullscreenAd;
- (void).cxx_destruct;
- (void)GDTfunctionq3M1mn:(id)arg1;
- (void)GDTfunctiona8cE0Y:(id)arg1 info:(id)arg2;
- (void)GDTfunctione4cgK5:(id)arg1;
- (void)GDTfunctions7S3o5:(id)arg1;
- (void)GDTfunctioni3J2f7:(id)arg1;
- (void)GDTfunctionn2V1Y2:(id)arg1;
- (void)GDTfunctionw1C3K1:(id)arg1 playerStatusChanged:(unsigned long long)arg2;
- (void)GDTfunctionz9iGKO:(id)arg1;
- (void)GDTfunctione4AMWH:(id)arg1;
- (void)GDTfunctionf5lGRG:(id)arg1;
- (void)GDTfunctione9AiAR:(id)arg1;
- (void)GDTfunctionh63Vqk:(id)arg1;
- (void)GDTfunctionm3u4DF:(id)arg1;
- (void)GDTfunctionu5ljDp:(id)arg1;
- (void)GDTfunctionu0ofax:(id)arg1;
- (void)GDTfunctionl32PQY:(id)arg1 error:(id)arg2;
- (void)GDTfunctiona9drfD:(id)arg1;
- (void)GDTfunctionh6uY7M:(id)arg1;
- (void)GDTfunctionc7VGoP:(id)arg1 error:(id)arg2;
- (void)GDTfunctiony78pca:(id)arg1;
- (id)adImp;
- (void)setMediationExtDict:(id)arg1;
- (_Bool)isContractAd;
- (double)videoPlayTime;
- (double)videoDuration;
@property(readonly, nonatomic) _Bool isVideoAd;
- (id)realMediationPrice;
- (id)eCPMLevel;
- (long long)eCPM;
- (_Bool)isAdValid;
- (void)presentAdFromRootViewController:(id)arg1;
- (void)setGDTfunctionq0jtAi;
- (void)loadAd;
- (id)initWithAdNetworkConnector:(id)arg1 posId:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool detailPageVideoMuted;
@property(readonly) unsigned long long hash;
@property(nonatomic) long long maxVideoDuration;
@property(nonatomic) long long minVideoDuration;
@property(readonly) Class superclass;
@property(nonatomic) _Bool videoAutoPlayOnWWAN;
@property(nonatomic) _Bool videoMuted;

@end

