//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GDTAdImpProtocol-Protocol.h"
#import "GDTAdImpS2SProtocol-Protocol.h"
#import "GDTBusinessMediaDownloaderDelegate-Protocol.h"
#import "GDTUnifiedNativeAdImpProtocol-Protocol.h"

@class GDTAdBaseModel, GDTLoadAdParams, GDTUnifiedNativeAd, NSArray, NSDictionary, NSMutableArray, NSString;
@protocol GDTUnifiedNativeAdDelegate;

@interface GDTUnifiedNativeAdImp : NSObject <GDTBusinessMediaDownloaderDelegate, GDTUnifiedNativeAdImpProtocol, GDTAdImpProtocol, GDTAdImpS2SProtocol>
{
    _Bool isFromS2S;
    _Bool _disableServerMediation;
    _Bool _isVideoAd;
    _Bool _C2SHasInvokeWinOrLoss;
    _Bool _C2SLimitInvokeTimeEnable;
    id <GDTUnifiedNativeAdDelegate> delegate;
    GDTUnifiedNativeAd *unifiedNativeAd;
    GDTLoadAdParams *loadAdParams;
    NSString *adNetworkName;
    unsigned long long videoPlayPolicy;
    unsigned long long videoRenderType;
    long long maxVideoDuration;
    long long minVideoDuration;
    NSString *fixedVideoDuration;
    NSString *vastClassName;
    NSDictionary *_mediationExtDict;
    NSString *s2sToken;
    NSString *_placementId;
    NSString *_threadId;
    long long _serverType;
    double _requestBeginTime;
    double _requestEndTime;
    GDTAdBaseModel *_adModelForEvent;
    NSArray *_dataObjects;
    NSMutableArray *_downloaderArray;
}

@property(retain, nonatomic) NSMutableArray *downloaderArray; // @synthesize downloaderArray=_downloaderArray;
@property(nonatomic) _Bool C2SLimitInvokeTimeEnable; // @synthesize C2SLimitInvokeTimeEnable=_C2SLimitInvokeTimeEnable;
@property(nonatomic) _Bool C2SHasInvokeWinOrLoss; // @synthesize C2SHasInvokeWinOrLoss=_C2SHasInvokeWinOrLoss;
@property(copy, nonatomic) NSArray *dataObjects; // @synthesize dataObjects=_dataObjects;
@property(retain, nonatomic) GDTAdBaseModel *adModelForEvent; // @synthesize adModelForEvent=_adModelForEvent;
@property(nonatomic) _Bool isVideoAd; // @synthesize isVideoAd=_isVideoAd;
@property(nonatomic) double requestEndTime; // @synthesize requestEndTime=_requestEndTime;
@property(nonatomic) double requestBeginTime; // @synthesize requestBeginTime=_requestBeginTime;
@property(nonatomic) long long serverType; // @synthesize serverType=_serverType;
@property(copy, nonatomic) NSString *threadId; // @synthesize threadId=_threadId;
@property(copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(nonatomic) _Bool disableServerMediation; // @synthesize disableServerMediation=_disableServerMediation;
@property(nonatomic) _Bool isFromS2S; // @synthesize isFromS2S;
@property(copy, nonatomic) NSString *s2sToken; // @synthesize s2sToken;
@property(retain, nonatomic) NSDictionary *mediationExtDict; // @synthesize mediationExtDict=_mediationExtDict;
@property(copy, nonatomic) NSString *vastClassName; // @synthesize vastClassName;
@property(copy, nonatomic) NSString *fixedVideoDuration; // @synthesize fixedVideoDuration;
@property(nonatomic) long long minVideoDuration; // @synthesize minVideoDuration;
@property(nonatomic) long long maxVideoDuration; // @synthesize maxVideoDuration;
@property(nonatomic) unsigned long long videoRenderType; // @synthesize videoRenderType;
@property(nonatomic) unsigned long long videoPlayPolicy; // @synthesize videoPlayPolicy;
@property(copy, nonatomic) NSString *adNetworkName; // @synthesize adNetworkName;
@property(retain, nonatomic) GDTLoadAdParams *loadAdParams; // @synthesize loadAdParams;
@property(nonatomic) __weak GDTUnifiedNativeAd *unifiedNativeAd; // @synthesize unifiedNativeAd;
@property(nonatomic) __weak id <GDTUnifiedNativeAdDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)GDTfunctiona0tgtU:(long long)arg1;
- (void)mediaDownloader:(id)arg1 didFinishedWithError:(id)arg2;
- (void)GDTfunctiont7AADb;
- (void)setBidECPM:(long long)arg1;
- (void)sendLossNotificationWithInfo:(id)arg1;
- (void)sendWinNotificationWithInfo:(id)arg1;
- (void)GDTfunctionn3aild:(unsigned long long)arg1 detailErrorCode:(long long)arg2;
- (void)GDTfunctionn3aild:(unsigned long long)arg1;
- (_Bool)GDTfunctionb1sW6o;
- (void)GDTfunctionb8eaf1:(id)arg1;
- (id)GDTfunctiond7CppK:(long long)arg1;
- (void)loadAdWithAdCount:(long long)arg1;
- (void)loadAd;
- (id)initWithPlacementId:(id)arg1 serverType:(long long)arg2;
- (id)initWithPlacementId:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

