//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GDTVideoStoreViewController;

@protocol GDTVideoStoreViewControllerDelegate <NSObject>

@optional
- (void)GDTfunctionn9Jx0b:(GDTVideoStoreViewController *)arg1;
- (void)GDTfunctionb44FMD:(GDTVideoStoreViewController *)arg1;
- (void)GDTfunctiont11gId:(GDTVideoStoreViewController *)arg1;
- (void)GDTfunctionh8z9B8:(GDTVideoStoreViewController *)arg1;
@end

