//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class GLWXLoginGuideController, NSArray, NSString, UITableView;

@interface GLWXLoginGuideStepView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    GLWXLoginGuideController *_controller;
    NSString *_nickName;
    UIView *_navBarView;
    UIView *_headerView;
    UITableView *_listTable;
    NSArray *_listData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *listData; // @synthesize listData=_listData;
@property(retain, nonatomic) UITableView *listTable; // @synthesize listTable=_listTable;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UIView *navBarView; // @synthesize navBarView=_navBarView;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(nonatomic) __weak GLWXLoginGuideController *controller; // @synthesize controller=_controller;
- (void)reloadData;
- (void)closeAction;
- (id)data;
- (id)attributeString:(id)arg1 font:(id)arg2 textColor:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

