//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface GLWXLoginGuideAccountItemView : UIView
{
    UILabel *_titleLab;
    UIView *_infoView;
    UIImageView *_headerImgView;
    UILabel *_nickNameLab;
    UILabel *_numLab;
    UIButton *_loginBtn;
    CDUnknownBlockType _loginBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType loginBlock; // @synthesize loginBlock=_loginBlock;
@property(retain, nonatomic) UIButton *loginBtn; // @synthesize loginBtn=_loginBtn;
@property(retain, nonatomic) UILabel *numLab; // @synthesize numLab=_numLab;
@property(retain, nonatomic) UILabel *nickNameLab; // @synthesize nickNameLab=_nickNameLab;
@property(retain, nonatomic) UIImageView *headerImgView; // @synthesize headerImgView=_headerImgView;
@property(retain, nonatomic) UIView *infoView; // @synthesize infoView=_infoView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
- (void)loginAction;
- (id)initWithFrame:(struct CGRect)arg1;

@end

