//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface HeimdallrBUEmbedConfig : NSObject
{
    struct _opaque_pthread_rwlock_t _filterLock;
    struct _opaque_pthread_rwlock_t _sdkIDLock;
    NSDictionary *_filter;
    NSString *_sdkID;
    NSArray *_addressRanges;
    NSString *_uploadAid;
    NSString *_deviceID;
    NSString *_sdkVersion;
    NSString *_hostAppID;
    NSArray *_libNames;
}

+ (id)defaultConfig;
- (void).cxx_destruct;
@property(retain) NSArray *libNames; // @synthesize libNames=_libNames;
@property(copy) NSString *hostAppID; // @synthesize hostAppID=_hostAppID;
@property(copy) NSString *sdkVersion; // @synthesize sdkVersion=_sdkVersion;
@property(copy) NSString *deviceID; // @synthesize deviceID=_deviceID;
@property(copy) NSString *uploadAid; // @synthesize uploadAid=_uploadAid;
@property(retain) NSArray *addressRanges; // @synthesize addressRanges=_addressRanges;
- (void)removeCustomFilterKey:(id)arg1;
- (void)setCustomFilterValue:(id)arg1 forKey:(id)arg2;
@property(retain, nonatomic) NSDictionary *filter; // @synthesize filter=_filter;
@property(copy) NSString *sdkID; // @synthesize sdkID=_sdkID;
- (id)init;

@end

