//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "HLBaseController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UITableView, UIView;

@interface HLResultController : HLBaseController <UITableViewDelegate, UITableViewDataSource>
{
    UITableView *_resultTableView;
    UIView *_sectionHeaderView;
    NSMutableArray *_loanPeriodListArray;
    NSString *_loanTypeStr;
    NSString *_loanAmount;
    NSString *_loanRate;
    NSString *_loanYear;
    NSString *_totalInterest;
    NSString *_totalAmount;
    NSString *_commercialLoanAmount;
    NSString *_commercialRate;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *commercialRate; // @synthesize commercialRate=_commercialRate;
@property(copy, nonatomic) NSString *commercialLoanAmount; // @synthesize commercialLoanAmount=_commercialLoanAmount;
@property(copy, nonatomic) NSString *totalAmount; // @synthesize totalAmount=_totalAmount;
@property(copy, nonatomic) NSString *totalInterest; // @synthesize totalInterest=_totalInterest;
@property(copy, nonatomic) NSString *loanYear; // @synthesize loanYear=_loanYear;
@property(copy, nonatomic) NSString *loanRate; // @synthesize loanRate=_loanRate;
@property(copy, nonatomic) NSString *loanAmount; // @synthesize loanAmount=_loanAmount;
@property(copy, nonatomic) NSString *loanTypeStr; // @synthesize loanTypeStr=_loanTypeStr;
@property(retain, nonatomic) NSMutableArray *loanPeriodListArray; // @synthesize loanPeriodListArray=_loanPeriodListArray;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)shareTableView;
- (id)generateShareImage:(id)arg1 tableHeaderViewLayer:(id)arg2 sectionHeaderViewLayer:(id)arg3 tableHeaderViewHeight:(double)arg4 sectionHeaderHeight:(double)arg5 totalHeight:(double)arg6 tableViewHeight:(double)arg7;
- (id)assetCollection:(id)arg1;
- (void)saveImageToAlbum:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)shareToPlatform:(id)arg1;
- (void)setupSectionHeaderView;
- (void)addTableHeaderView;
- (void)addTableView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

