//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface InviteFriendsModel : NSObject
{
    NSString *_headerURL;
    NSString *_name;
    NSString *_statusStr;
}

+ (id)parseData:(id)arg1 status:(id)arg2;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *statusStr; // @synthesize statusStr=_statusStr;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *headerURL; // @synthesize headerURL=_headerURL;

@end

