//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSString, NSURLSessionDataTask;
@protocol JDDMLoginDelegate;

@interface JDDMOAuth : NSObject
{
    NSString *_accessToken;
    NSString *_refreshToken;
    NSDate *_expirationDate;
    id <JDDMLoginDelegate> _loginDelegate;
    NSString *_localShemes;
    NSString *_redirectUri;
    NSString *_appkey;
    NSString *_appsecret;
    NSDictionary *_passData;
    NSString *_openId;
    CDUnknownBlockType _jdInnerLogin;
    long long _jdInnerLoginFailureCount;
    NSURLSessionDataTask *_openJDLoginTask;
    NSURLSessionDataTask *_JDLoginStatusTask;
    double _requestTimeInterval;
}

+ (void)getKeplerJDATimeStampInfo;
+ (id)sharedOAuthor;
+ (_Bool)jxAppInstalled;
+ (_Bool)iphoneAppInstalled;
- (void).cxx_destruct;
@property(nonatomic) double requestTimeInterval; // @synthesize requestTimeInterval=_requestTimeInterval;
@property(nonatomic) __weak NSURLSessionDataTask *JDLoginStatusTask; // @synthesize JDLoginStatusTask=_JDLoginStatusTask;
@property(nonatomic) __weak NSURLSessionDataTask *openJDLoginTask; // @synthesize openJDLoginTask=_openJDLoginTask;
@property(nonatomic) long long jdInnerLoginFailureCount; // @synthesize jdInnerLoginFailureCount=_jdInnerLoginFailureCount;
@property(copy, nonatomic) CDUnknownBlockType jdInnerLogin; // @synthesize jdInnerLogin=_jdInnerLogin;
@property(copy, nonatomic) NSString *openId; // @synthesize openId=_openId;
@property(copy, nonatomic) NSDictionary *passData; // @synthesize passData=_passData;
@property(retain, nonatomic) NSString *appsecret; // @synthesize appsecret=_appsecret;
@property(retain, nonatomic) NSString *appkey; // @synthesize appkey=_appkey;
@property(copy, nonatomic) NSString *redirectUri; // @synthesize redirectUri=_redirectUri;
@property(copy, nonatomic) NSString *localShemes; // @synthesize localShemes=_localShemes;
@property(nonatomic) __weak id <JDDMLoginDelegate> loginDelegate; // @synthesize loginDelegate=_loginDelegate;
@property(copy, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(copy, nonatomic) NSString *refreshToken; // @synthesize refreshToken=_refreshToken;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
- (id)deviceAddresses;
- (void)getTokenByCode:(id)arg1;
- (id)handleTokenAuth:(id)arg1;
- (_Bool)handleJDAuthorizedLoginURL:(id)arg1;
- (_Bool)handleOpenURL:(id)arg1;
- (_Bool)reauthorize;
- (_Bool)authorize;
- (id)initWithAppID:(id)arg1 appKey:(id)arg2 secretKey:(id)arg3 redirectUri:(id)arg4 delegate:(id)arg5;
- (_Bool)isSDKAuthedByAppID:(id)arg1;
- (id)init;
- (_Bool)checkRegisteredScheme;

@end

