//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface JDS_CPSDynamicEnCommon : NSObject
{
}

+ (id)genEncryedParm:(id)arg1 timeStamp:(unsigned long long)arg2 uuid:(id)arg3;
+ (id)genDkey:(id)arg1 withDyHash:(id)arg2;
+ (id)genDkey;
+ (id)encrypt:(id)arg1 withKey:(id)arg2 withError:(id *)arg3;
+ (id)decrypt:(id)arg1 withKey:(id)arg2 withError:(id *)arg3;
+ (id)JDSaesDecryptString:(id)arg1 key:(id)arg2;
+ (id)JDSaesDecryptData:(id)arg1 key:(id)arg2;

@end

