//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CMBaseModel.h"

@class CMCommentModel, NSAttributedString, NSDictionary, NSString;

@interface MineMessageModel : CMBaseModel
{
    _Bool _canGoDetail;
    _Bool _headerBtnCanClick;
    NSString *_imgURL;
    NSString *_rightText;
    NSAttributedString *_rightAttributedText;
    NSString *_cellReuseID;
    double _rowHeight;
    double _messagenickWidth;
    NSString *_toastMessage;
    CMCommentModel *_commentModel;
    CDUnknownBlockType _deleteCommentHandle;
    NSDictionary *_ident_info;
    long long _ident_flag;
    NSString *_ident_show;
    NSDictionary *_jump_info;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDictionary *jump_info; // @synthesize jump_info=_jump_info;
@property(retain, nonatomic) NSString *ident_show; // @synthesize ident_show=_ident_show;
@property(nonatomic) long long ident_flag; // @synthesize ident_flag=_ident_flag;
@property(copy, nonatomic) NSDictionary *ident_info; // @synthesize ident_info=_ident_info;
@property(nonatomic) _Bool headerBtnCanClick; // @synthesize headerBtnCanClick=_headerBtnCanClick;
@property(copy, nonatomic) CDUnknownBlockType deleteCommentHandle; // @synthesize deleteCommentHandle=_deleteCommentHandle;
@property(retain, nonatomic) CMCommentModel *commentModel; // @synthesize commentModel=_commentModel;
@property(nonatomic) _Bool canGoDetail; // @synthesize canGoDetail=_canGoDetail;
@property(copy, nonatomic) NSString *toastMessage; // @synthesize toastMessage=_toastMessage;
@property(nonatomic) double messagenickWidth; // @synthesize messagenickWidth=_messagenickWidth;
@property(nonatomic) double rowHeight; // @synthesize rowHeight=_rowHeight;
@property(copy, nonatomic) NSString *cellReuseID; // @synthesize cellReuseID=_cellReuseID;
@property(retain, nonatomic) NSAttributedString *rightAttributedText; // @synthesize rightAttributedText=_rightAttributedText;
@property(copy, nonatomic) NSString *rightText; // @synthesize rightText=_rightText;
@property(copy, nonatomic) NSString *imgURL; // @synthesize imgURL=_imgURL;
- (double)contentHeight;
- (id)initWithCommentInfo:(id)arg1 deleteCommentHandle:(CDUnknownBlockType)arg2;
- (id)initWithNotificationInfo:(id)arg1;

@end

