//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CBAttributedLabel, NSExpressionDescription, NSFetchRequest, NSString, UINavigationController;

@interface MonthSurplusView : UIView
{
    CBAttributedLabel *_dateLabel;
    CBAttributedLabel *_expenditureLabel;
    CBAttributedLabel *_incomeLabel;
    CBAttributedLabel *_surplusLabel;
    NSFetchRequest *_fetchRequest;
    NSExpressionDescription *_expressionDescription;
    NSString *_date;
    UINavigationController *_navigationController;
}

- (void).cxx_destruct;
@property(nonatomic) UINavigationController *navigationController; // @synthesize navigationController=_navigationController;
- (void)queryMonthData:(id)arg1;
- (void)tallyDataRefresh;
- (void)tallyDataChange:(id)arg1;
- (void)updateMoneyLabel:(id)arg1 text:(id)arg2;
- (void)updateDateLabel:(id)arg1;
- (void)refreshCurrentDateData;
- (void)lookAllAction;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

