//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class DiscoverModel, UIImageView, UILabel, UIView;

@interface MoreFuncItemCell : UICollectionViewCell
{
    UIView *_iconView;
    UIImageView *_iconImgView;
    UIImageView *_iconImgFillView;
    UIImageView *_iconImgStrokeView;
    UILabel *_titleLab;
    double _iconCornerRadius;
    double _leftSpace;
    DiscoverModel *_model;
}

- (void).cxx_destruct;
@property(retain, nonatomic) DiscoverModel *model; // @synthesize model=_model;
@property(nonatomic) double leftSpace; // @synthesize leftSpace=_leftSpace;
@property(nonatomic) double iconCornerRadius; // @synthesize iconCornerRadius=_iconCornerRadius;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *iconImgStrokeView; // @synthesize iconImgStrokeView=_iconImgStrokeView;
@property(retain, nonatomic) UIImageView *iconImgFillView; // @synthesize iconImgFillView=_iconImgFillView;
@property(retain, nonatomic) UIImageView *iconImgView; // @synthesize iconImgView=_iconImgView;
@property(retain, nonatomic) UIView *iconView; // @synthesize iconView=_iconView;
- (void)reloadData;
- (void)clearData;
- (void)setHighlighted:(_Bool)arg1;
- (void)setupViews;
- (void)layoutSubviews;

@end

