//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "BURewardedVideoAdDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class BURewardedVideoAd, MyPointsHeaderView, NSDictionary, NSMutableArray, NSString, UITableView;

@interface MyPointsViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, BURewardedVideoAdDelegate>
{
    _Bool _mustbackPreviousLevel;
    _Bool _scrollToPointsExchange;
    _Bool _finishPlay;
    _Bool _moreVideo;
    BURewardedVideoAd *_rewardedVideoAd;
    NSMutableArray *_dataArray;
    UITableView *_tableView;
    MyPointsHeaderView *_headerView;
    long long _ruleid;
    long long _videoScore;
    NSDictionary *_taskInfo;
    NSString *_getTipString;
    long long _total_score;
}

- (void).cxx_destruct;
@property(nonatomic) long long total_score; // @synthesize total_score=_total_score;
@property(retain, nonatomic) NSString *getTipString; // @synthesize getTipString=_getTipString;
@property(retain, nonatomic) NSDictionary *taskInfo; // @synthesize taskInfo=_taskInfo;
@property(nonatomic) long long videoScore; // @synthesize videoScore=_videoScore;
@property(nonatomic) _Bool moreVideo; // @synthesize moreVideo=_moreVideo;
@property(nonatomic) _Bool finishPlay; // @synthesize finishPlay=_finishPlay;
@property(nonatomic) long long ruleid; // @synthesize ruleid=_ruleid;
@property(retain, nonatomic) MyPointsHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) BURewardedVideoAd *rewardedVideoAd; // @synthesize rewardedVideoAd=_rewardedVideoAd;
@property(nonatomic) _Bool scrollToPointsExchange; // @synthesize scrollToPointsExchange=_scrollToPointsExchange;
@property(nonatomic) _Bool mustbackPreviousLevel; // @synthesize mustbackPreviousLevel=_mustbackPreviousLevel;
- (void)goPointCardDetail;
- (void)completeTask;
- (void)dealPoints;
- (void)getPoint;
- (void)rewardedVideoAdDidClickSkip:(id)arg1;
- (void)rewardedVideoAdServerRewardDidFail:(id)arg1;
- (void)rewardedVideoAdServerRewardDidSucceed:(id)arg1 verify:(_Bool)arg2;
- (void)rewardedVideoAdDidPlayFinish:(id)arg1 didFailWithError:(id)arg2;
- (void)rewardedVideoAdDidClick:(id)arg1;
- (void)rewardedVideoAdDidClose:(id)arg1;
- (void)rewardedVideoAdWillClose:(id)arg1;
- (void)rewardedVideoAdDidVisible:(id)arg1;
- (void)rewardedVideoAdWillVisible:(id)arg1;
- (void)rewardedVideoAdVideoDidLoad:(id)arg1;
- (void)rewardedVideoAd:(id)arg1 didFailWithError:(id)arg2;
- (void)rewardedVideoAdDidLoad:(id)arg1;
- (void)requestVideoNext;
- (void)requestVideo;
- (void)showPopView;
- (void)viewVideo;
- (void)goCommunity;
- (void)goTally;
- (void)followWXAccount;
- (void)ModifyHeaderName;
- (void)bindPhone;
- (void)bindWX;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)requestData;
- (void)goPointsRule;
- (void)setupUI;
- (void)viewWillAppear:(_Bool)arg1;
- (void)popViewController;
- (void)scrollToTop;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

