//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"

@class InviteFriendsResultView, NSMutableDictionary, NSString, NewInviteFriendTableView, UIButton, UIImageView, UIScrollView, UIView;

@interface NewInviteFriendsViewController : UIViewController <UIScrollViewDelegate>
{
    UIView *_navBarView;
    UIScrollView *_contentScroll;
    UIView *_whiteView0;
    UIView *_whiteView1;
    UIView *_whiteView2;
    UIView *_ruleView;
    InviteFriendsResultView *_buyersView;
    UIButton *_inviteBtn;
    UIImageView *_inviteTip;
    UIButton *_moreBtn;
    NewInviteFriendTableView *_listView;
    NSMutableDictionary *_dataDic;
    NSString *_last_id;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *last_id; // @synthesize last_id=_last_id;
@property(retain, nonatomic) NSMutableDictionary *dataDic; // @synthesize dataDic=_dataDic;
@property(retain, nonatomic) NewInviteFriendTableView *listView; // @synthesize listView=_listView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)shareToPlat:(long long)arg1;
- (void)inviteFriends;
- (void)ruleClose;
- (void)clickActivityRule;
- (void)requestData;
- (void)backAction;
- (void)setupListData;
- (void)setupBuyuserList;
- (void)setupUI;
- (void)setupUI0;
- (void)setupNavBar;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

