//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSTimer.h>

@interface NSTimer (TBTimer)
+ (void)timerAction:(id)arg1;
+ (id)tb_timerWithTimeInterval:(double)arg1 repeats:(_Bool)arg2 block:(CDUnknownBlockType)arg3;
+ (void)bu_blockInvoke:(id)arg1;
+ (id)bu_scheduledTimerWithTimeInterval:(double)arg1 repeats:(_Bool)arg2 block:(CDUnknownBlockType)arg3;
@property(nonatomic) double GDTfunctionx60zkS;
- (void)GDTfunctiona5WIWe;
- (void)GDTfunctione49iZN;
@end

