//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSNumberFormatter, NSTimer, UITextField;

@interface RConverterKeyboard : UIView
{
    NSNumberFormatter *_numberFormatter;
    NSTimer *_timer;
    _Bool _isDeleting;
    UITextField *_textField;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UITextField *textField; // @synthesize textField=_textField;
- (void)textFieldDidChange:(id)arg1;
- (void)editingChaned;
- (void)longDelete;
- (void)longPressAction:(id)arg1;
- (void)deleteAction;
- (void)digitButtonAction:(id)arg1;
- (void)addKeyboard;
- (id)imageWithColor:(id)arg1 size:(struct CGSize)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

