//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UINavigationController, YYLabel;

@interface RegisterAgreePrivacyView : UIView
{
    UIButton *_agreeBtn;
    YYLabel *_agreeLab;
    _Bool _isAgree;
    UINavigationController *_pushNaviController;
    CDUnknownBlockType _agreeCallback;
    CDUnknownBlockType _userAgreementCallback;
    CDUnknownBlockType _privacyAgreementCallback;
    double _btnImgWidth;
}

- (void).cxx_destruct;
@property(nonatomic) double btnImgWidth; // @synthesize btnImgWidth=_btnImgWidth;
@property(copy, nonatomic) CDUnknownBlockType privacyAgreementCallback; // @synthesize privacyAgreementCallback=_privacyAgreementCallback;
@property(copy, nonatomic) CDUnknownBlockType userAgreementCallback; // @synthesize userAgreementCallback=_userAgreementCallback;
@property(copy, nonatomic) CDUnknownBlockType agreeCallback; // @synthesize agreeCallback=_agreeCallback;
@property(nonatomic) __weak UINavigationController *pushNaviController; // @synthesize pushNaviController=_pushNaviController;
@property(nonatomic) _Bool isAgree; // @synthesize isAgree=_isAgree;
@property(retain, nonatomic) YYLabel *agreeLab; // @synthesize agreeLab=_agreeLab;
@property(retain, nonatomic) UIButton *agreeBtn; // @synthesize agreeBtn=_agreeBtn;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)privacyAgreementAction;
- (void)userAgreementAction;
- (void)agreeBtnAction:(id)arg1;
- (id)agreementTextAttribute;
- (id)initWithFrame:(struct CGRect)arg1;

@end

