//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/NSManagedObject.h>

@class NSNumber, NSString;

@interface RemarkModel : NSManagedObject
{
}


// Remaining properties
@property(retain, nonatomic) NSNumber *count; // @dynamic count;
@property(retain, nonatomic) NSString *remark; // @dynamic remark;
@property(retain, nonatomic) NSString *time; // @dynamic time;
@property(retain, nonatomic) NSString *typeID; // @dynamic typeID;
@end

