//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSOperation.h>

@interface SDImageCachesManagerOperation : NSOperation
{
    struct os_unfair_lock_s _pendingCountLock;
    int _pendingCountLock_deprecated;
    _Bool _executing;
    _Bool _finished;
    _Bool _cancelled;
    unsigned long long _pendingCount;
}

- (_Bool)isCancelled;
- (_Bool)isFinished;
- (_Bool)isExecuting;
- (void)setCancelled:(_Bool)arg1;
- (void)setExecuting:(_Bool)arg1;
- (void)setFinished:(_Bool)arg1;
- (void)reset;
- (void)done;
- (void)cancel;
- (void)completeOne;
@property(readonly, nonatomic) unsigned long long pendingCount; // @synthesize pendingCount=_pendingCount;
- (void)beginWithTotalCount:(unsigned long long)arg1;
- (id)init;

@end

