//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CBBillDatePicker, UIImageView, UILabel;

@interface SearchTallyChooseView : UIView
{
    UIImageView *_righticon;
    _Bool _show;
    UILabel *_starttimeLabel;
    UILabel *_endtimeLabel;
    _Bool _ischooseStart;
    long long _chooseType;
    CDUnknownBlockType _selectedHandle;
    CDUnknownBlockType _dismissBlock;
    CDUnknownBlockType _dateHandle;
    UIView *_whitebgView;
    CBBillDatePicker *_datePicker;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CBBillDatePicker *datePicker; // @synthesize datePicker=_datePicker;
@property(retain, nonatomic) UIView *whitebgView; // @synthesize whitebgView=_whitebgView;
@property(copy, nonatomic) CDUnknownBlockType dateHandle; // @synthesize dateHandle=_dateHandle;
@property(copy, nonatomic) CDUnknownBlockType dismissBlock; // @synthesize dismissBlock=_dismissBlock;
@property(copy, nonatomic) CDUnknownBlockType selectedHandle; // @synthesize selectedHandle=_selectedHandle;
@property(nonatomic) long long chooseType; // @synthesize chooseType=_chooseType;
- (void)sureBtnClick;
- (void)resetBtnClick;
- (void)datebtn:(id)arg1;
- (void)setupdateUI;
- (void)btnClick:(id)arg1;
- (void)setupView:(id)arg1 withdefault:(long long)arg2;
- (void)updateTimeString:(id)arg1 end:(id)arg2;
- (void)setup:(long long)arg1 withdefault:(long long)arg2;
- (void)dismiss;
- (void)show;
- (id)initWithFrame:(struct CGRect)arg1 tallyType:(long long)arg2 defaultindex:(long long)arg3;

@end

