//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CBAttributedLabel, UILabel;

@interface SearchHeaderView : UIView
{
    UILabel *_timeLabel;
    UILabel *_expenditureicon;
    CBAttributedLabel *_expenditureLabel;
    UILabel *_expenditurecountLabel;
    UILabel *_incomeicon;
    CBAttributedLabel *_incomeLabel;
    UILabel *_incomecountLabel;
}

- (void).cxx_destruct;
- (void)updateTimeString:(id)arg1 end:(id)arg2;
- (void)updateHedaerInfo:(double)arg1 income:(double)arg2 expcnt:(long long)arg3 incomecnt:(long long)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

