//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseReq.h"

@class NSString;

@interface SendAuthReq : BaseReq
{
    _Bool _isOption1;
    NSString *_scope;
    NSString *_state;
    NSString *_extData;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *extData; // @synthesize extData=_extData;
@property(nonatomic) _Bool isOption1; // @synthesize isOption1=_isOption1;
@property(copy, nonatomic) NSString *state; // @synthesize state=_state;
@property(copy, nonatomic) NSString *scope; // @synthesize scope=_scope;

@end

