//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class INVoiceShortcut, NSAttributedString, NSString;

@interface ShortcutsItem : NSObject
{
    NSString *_iconName;
    NSString *_invocationPhrase;
    NSString *_amount;
    INVoiceShortcut *_voiceShortcut;
    double _amountWidth;
    NSAttributedString *_typeAttributedText;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSAttributedString *typeAttributedText; // @synthesize typeAttributedText=_typeAttributedText;
@property(nonatomic) double amountWidth; // @synthesize amountWidth=_amountWidth;
@property(retain, nonatomic) INVoiceShortcut *voiceShortcut; // @synthesize voiceShortcut=_voiceShortcut;
@property(copy, nonatomic) NSString *amount; // @synthesize amount=_amount;
@property(copy, nonatomic) NSString *invocationPhrase; // @synthesize invocationPhrase=_invocationPhrase;
@property(copy, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;

@end

