//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SKConvert : NSObject
{
}

+ (id)loadCacheData;
+ (void)saveCacheData:(id)arg1;
+ (_Bool)openPage:(id)arg1 parameters:(id)arg2;
+ (id)getCurrentDateString;
+ (_Bool)shouldShowConvert:(long long)arg1 uuid:(id)arg2 alertTimes:(long long)arg3;
+ (void)showAlert:(id)arg1 finish:(CDUnknownBlockType)arg2;
+ (void)loadConvertCache:(CDUnknownBlockType)arg1;
+ (void)startConvertWithCache:(id)arg1 responseBlock:(CDUnknownBlockType)arg2 finish:(CDUnknownBlockType)arg3;
+ (void)startConvert:(id)arg1 finish:(CDUnknownBlockType)arg2;
+ (void)startConvert:(id)arg1;

@end

