//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class CALayer, SKFeedbackModel, UIActivityIndicatorView, UIButton, UIColor, UIImageView, UILabel;

@interface SKFeedbackCell : UITableViewCell
{
    CALayer *_bgLayer;
    UILabel *_label;
    UILabel *_dateLabel;
    UIImageView *_bgImgView;
    UIButton *_failedBtn;
    UIActivityIndicatorView *_loadingView;
    UIColor *_contentColor;
    SKFeedbackModel *_model;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SKFeedbackModel *model; // @synthesize model=_model;
- (void)drawRect:(struct CGRect)arg1;
- (id)controller;
- (void)showActionSheet;
- (void)sendMsg:(id)arg1;
- (void)showFailed;
- (void)showFinish;
- (void)showSending;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 contentColor:(id)arg3 textColor:(id)arg4;
- (id)circleImageWithColor:(id)arg1 left:(_Bool)arg2;

@end

