//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSDictionary, NSString;

@interface SKOnlineConfig : NSObject
{
    NSDictionary *_configDict;
    NSString *_appKey;
    NSDate *_date;
    _Bool _isUseSKSelfConfig;
}

+ (id)MTAGetConfigParameters:(id)arg1 defaultValue:(id)arg2;
+ (id)getJSONConfigParams:(id)arg1;
+ (long long)getIntegerConfigParams:(id)arg1 defaultValue:(id)arg2;
+ (long long)getIntegerConfigParams:(id)arg1;
+ (_Bool)getBoolConfigParams:(id)arg1 defaultValue:(id)arg2;
+ (_Bool)getBoolConfigParams:(id)arg1;
+ (id)getConfigParams:(id)arg1 defaultValue:(id)arg2;
+ (id)getConfigParams:(id)arg1;
+ (void)startWithAppKey:(id)arg1 responseBlock:(CDUnknownBlockType)arg2;
+ (void)startWithAppKey:(id)arg1;
+ (id)sharedOnlineConfig;
- (void).cxx_destruct;
@property(nonatomic) _Bool isUseSKSelfConfig; // @synthesize isUseSKSelfConfig=_isUseSKSelfConfig;
- (void)dealloc;
- (id)skGetConfigParams:(id)arg1 defaultValue:(id)arg2;
- (id)documentsPath;
- (void)saveConfig:(id)arg1;
- (void)handleConfig:(id)arg1;
- (void)setAppkey:(id)arg1;
- (void)judgeConfigType:(id)arg1 finish:(CDUnknownBlockType)arg2;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (id)init;

@end

