//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, PHAsset, UIImage;

@interface SKPhotoModel : NSObject
{
    _Bool _isICloud;
    _Bool _iCloudDownloading;
    _Bool _selected;
    int _iCloudRequestID;
    PHAsset *_asset;
    NSString *_localIdentifier;
    UIImage *_thumbPhoto;
    UIImage *_previewPhoto;
    NSString *_albumName;
    double _iCloudProgress;
    long long _selectedIndex;
    NSString *_selectIndexStr;
    long long _albumIndex;
    struct CGSize _listSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize listSize; // @synthesize listSize=_listSize;
@property(nonatomic) long long albumIndex; // @synthesize albumIndex=_albumIndex;
@property(copy, nonatomic) NSString *selectIndexStr; // @synthesize selectIndexStr=_selectIndexStr;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) int iCloudRequestID; // @synthesize iCloudRequestID=_iCloudRequestID;
@property(nonatomic) double iCloudProgress; // @synthesize iCloudProgress=_iCloudProgress;
@property(nonatomic) _Bool iCloudDownloading; // @synthesize iCloudDownloading=_iCloudDownloading;
@property(nonatomic) _Bool isICloud; // @synthesize isICloud=_isICloud;
@property(copy, nonatomic) NSString *albumName; // @synthesize albumName=_albumName;
@property(retain, nonatomic) UIImage *previewPhoto; // @synthesize previewPhoto=_previewPhoto;
@property(retain, nonatomic) UIImage *thumbPhoto; // @synthesize thumbPhoto=_thumbPhoto;
@property(copy, nonatomic) NSString *localIdentifier; // @synthesize localIdentifier=_localIdentifier;
@property(retain, nonatomic) PHAsset *asset; // @synthesize asset=_asset;

@end

