//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SKThemeImageTool : NSObject
{
}

+ (id)expendIncomeWidgetImage:(id)arg1;
+ (id)todayWidgetSeletedImage:(id)arg1;
+ (id)todayWidgetImage:(id)arg1;
+ (id)skthemeImageToolThemeImageWithImageT:(id)arg1 imageM:(id)arg2 colorT:(id)arg3 colorM:(id)arg4;
+ (id)skthemeImageToolColorWithHexString:(id)arg1 alpha:(double)arg2;
+ (id)skthemeImageToolImageWithTintColor:(id)arg1 color:(id)arg2;
+ (id)skthemeToolCompositeImages:(id)arg1;

@end

