//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "StockBaseController.h"

@class StockTradeRecordTableView, UIButton, UIView;

@interface StockTradeRecordsViewController : StockBaseController
{
    long long _tabIndex;
    UIButton *_entrustBtn;
    UIButton *_doneBtn;
    UIView *_bottomlineView;
    UIView *_sectionView1;
    UIView *_sectionView2;
    StockTradeRecordTableView *_entrustTableView;
    StockTradeRecordTableView *_doneTableView;
}

- (void).cxx_destruct;
- (void)switchTypeAction:(id)arg1;
- (void)setupSegementView;
- (void)setupUI;
- (void)viewDidLoad;

@end

