//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class StockModel, UILabel;

@interface StockSearchKeysTableViewCell : UITableViewCell
{
    StockModel *_model;
    UILabel *_nameLabel;
    UILabel *_codeLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *codeLabel; // @synthesize codeLabel=_codeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) StockModel *model; // @synthesize model=_model;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

