//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface SurplusBaseViewController : UIViewController
{
}

- (long long)minniProgramsNavigationStyle;
- (id)category;
- (id)topDes;
- (id)topName;
- (id)topImageName;
- (id)shareImage;
- (id)shareURL;
- (id)shareContent;
- (id)shareTitle;
- (_Bool)theme;
- (id)sk_miniProgramsName;
- (void)viewDidLoad;

@end

