//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, SKThemeSettingItem, TallyLedgerInfo, TallyLedgerTabBarController;

@interface TallyLedgerManager : NSObject
{
    _Bool _updating;
    TallyLedgerTabBarController *_rootController;
    long long _tallyLedgerID;
    TallyLedgerInfo *_tallyLedgerlInfo;
    SKThemeSettingItem *_tallyLedgerTheme;
    NSArray *_themes;
}

+ (id)localTallyLedgerIDsWithNumber;
+ (id)localTallyLedgerIDsWithString;
+ (void)deleteTallyLedger:(id)arg1;
+ (void)updateModelWithDictionary:(id)arg1 updateInfo:(id)arg2;
+ (id)modelWithDictionary:(id)arg1;
+ (void)compareAndUpdateAll:(id)arg1 localData:(id)arg2 updateWidget:(_Bool)arg3 finsh:(CDUnknownBlockType)arg4;
+ (void)requestTallyLedgerListWithConfig;
+ (void)requestTallyLedgerList;
+ (long long)tallyLedgerWithMyJoinedNumbers;
+ (long long)tallyLedgerMemberRightWithBookId:(id)arg1;
+ (long long)tallyLedgerMemberRightWithBook:(id)arg1;
+ (id)colorImageName:(id)arg1 colorType:(long long)arg2;
+ (_Bool)tallyLedgerVIPValid:(id)arg1;
+ (id)sharedManager;
- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *themes; // @synthesize themes=_themes;
@property(nonatomic) _Bool updating; // @synthesize updating=_updating;
@property(retain, nonatomic) SKThemeSettingItem *tallyLedgerTheme; // @synthesize tallyLedgerTheme=_tallyLedgerTheme;
@property(retain, nonatomic) TallyLedgerInfo *tallyLedgerlInfo; // @synthesize tallyLedgerlInfo=_tallyLedgerlInfo;
@property(nonatomic) long long tallyLedgerID; // @synthesize tallyLedgerID=_tallyLedgerID;
@property(nonatomic) __weak TallyLedgerTabBarController *rootController; // @synthesize rootController=_rootController;
- (id)themeWithThemeColor:(id)arg1;
- (id)themeWithThemeId:(long long)arg1;
- (id)imageDefaultColor;
- (id)colorImageName:(id)arg1;
- (id)loadThemes;
- (id)showTallyMemberNickName:(id)arg1;
- (_Bool)canDeleteTallyLedgerModelWithDay;
- (_Bool)canDeleteTallyLedgerModel:(id)arg1;
- (long long)tallyChartCycleTypeDefault;
- (long long)tallyChartTypeDefault;
- (long long)tallyTypeDefault;
- (long long)acMonthDay;
- (void)clearData;
- (void)loadTallyLedgerInfoBaseInfo:(id)arg1;
- (void)loadTallyLedgerInfo:(long long)arg1;
- (id)init;

@end

