//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TallyLabelAddTallyDynamicViewProtocal-Protocol.h"

@class NSString, SKThemeSettingItem, TallyLabelAddTallyDynamicView, UIButton, UIScrollView, UIViewController;

@interface TallyLabelChooseView : UIView <TallyLabelAddTallyDynamicViewProtocal>
{
    _Bool _isReadOnly;
    _Bool _supportAllScrolling;
    long long _source;
    long long _bookID;
    long long _cID;
    NSString *_typeName;
    long long _tallyType;
    double _bottomEdge;
    SKThemeSettingItem *_curThemeItem;
    UIViewController *_controller;
    NSString *_defVal;
    CDUnknownBlockType _beginResponseActionBlock;
    CDUnknownBlockType _endResponseActionBlock;
    CDUnknownBlockType _updateBlock;
    CDUnknownBlockType _submitBlock;
    UIView *_lineView;
    UIView *_titleView;
    UIButton *_settingBtn;
    UIView *_scrollTitleView;
    UIView *_helpView;
    UIButton *_addBtn;
    UIScrollView *_flowScroll;
    TallyLabelAddTallyDynamicView *_flowView;
    UIView *_submitView;
    UIButton *_deleteBtn;
    UIButton *_submitBtn;
    NSString *_curVal;
}

- (void).cxx_destruct;
@property(copy, nonatomic) NSString *curVal; // @synthesize curVal=_curVal;
@property(retain, nonatomic) UIButton *submitBtn; // @synthesize submitBtn=_submitBtn;
@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) UIView *submitView; // @synthesize submitView=_submitView;
@property(retain, nonatomic) TallyLabelAddTallyDynamicView *flowView; // @synthesize flowView=_flowView;
@property(retain, nonatomic) UIScrollView *flowScroll; // @synthesize flowScroll=_flowScroll;
@property(retain, nonatomic) UIButton *addBtn; // @synthesize addBtn=_addBtn;
@property(retain, nonatomic) UIView *helpView; // @synthesize helpView=_helpView;
@property(retain, nonatomic) UIView *scrollTitleView; // @synthesize scrollTitleView=_scrollTitleView;
@property(retain, nonatomic) UIButton *settingBtn; // @synthesize settingBtn=_settingBtn;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(copy, nonatomic) CDUnknownBlockType submitBlock; // @synthesize submitBlock=_submitBlock;
@property(copy, nonatomic) CDUnknownBlockType updateBlock; // @synthesize updateBlock=_updateBlock;
@property(copy, nonatomic) CDUnknownBlockType endResponseActionBlock; // @synthesize endResponseActionBlock=_endResponseActionBlock;
@property(copy, nonatomic) CDUnknownBlockType beginResponseActionBlock; // @synthesize beginResponseActionBlock=_beginResponseActionBlock;
@property(copy, nonatomic) NSString *defVal; // @synthesize defVal=_defVal;
@property(nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
@property(retain, nonatomic) SKThemeSettingItem *curThemeItem; // @synthesize curThemeItem=_curThemeItem;
@property(nonatomic) double bottomEdge; // @synthesize bottomEdge=_bottomEdge;
@property(nonatomic) _Bool supportAllScrolling; // @synthesize supportAllScrolling=_supportAllScrolling;
@property(nonatomic) _Bool isReadOnly; // @synthesize isReadOnly=_isReadOnly;
@property(nonatomic) long long tallyType; // @synthesize tallyType=_tallyType;
@property(retain, nonatomic) NSString *typeName; // @synthesize typeName=_typeName;
@property(nonatomic) long long cID; // @synthesize cID=_cID;
@property(nonatomic) long long bookID; // @synthesize bookID=_bookID;
@property(nonatomic) long long source; // @synthesize source=_source;
- (void)reloadData;
- (void)helpAction;
- (void)addAction;
- (void)submitAction;
- (void)deleteAction;
- (void)settingAction;
- (void)tapGesture;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)tallyLabelChangedNotification:(id)arg1;
- (void)clickWithTallyLabelAddTallyDynamicView:(id)arg1;
- (void)outBoundsAlertWithTallyLabelAddTallyDynamicView:(id)arg1;
- (void)selectedWithTallyLabelAddTallyDynamicView:(id)arg1 data:(id)arg2;
- (void)refreshDeleteBtnState:(id)arg1;
- (id)createTitleView:(id)arg1 frame:(struct CGRect)arg2;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

