//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableSet, NSString, NTallyModel, TypeButton, UIButton, UIViewController;

@interface TallyTypeSelectScrollView : UIScrollView <UIScrollViewDelegate>
{
    NSMutableSet *_resuseSet;
    NSMutableSet *_visibleSet;
    NSMutableArray *_typeArray;
    TypeButton *_addBtn;
    _Bool _hideSettingBtn;
    _Bool _isFromFamily;
    _Bool _unlockSuccessed;
    long long _tallyType;
    CDUnknownBlockType _didSelectedType;
    NTallyModel *_editModel;
    NSString *_editTypeID;
    UIViewController *_gestureVC;
    UIButton *_lastSelectedBtn;
    NSString *_removeTypeID;
    long long _selectcid;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool unlockSuccessed; // @synthesize unlockSuccessed=_unlockSuccessed;
@property(nonatomic) long long selectcid; // @synthesize selectcid=_selectcid;
@property(copy, nonatomic) NSString *removeTypeID; // @synthesize removeTypeID=_removeTypeID;
@property(nonatomic) _Bool isFromFamily; // @synthesize isFromFamily=_isFromFamily;
@property(nonatomic) _Bool hideSettingBtn; // @synthesize hideSettingBtn=_hideSettingBtn;
@property(retain, nonatomic) UIButton *lastSelectedBtn; // @synthesize lastSelectedBtn=_lastSelectedBtn;
@property(nonatomic) __weak UIViewController *gestureVC; // @synthesize gestureVC=_gestureVC;
@property(copy, nonatomic) NSString *editTypeID; // @synthesize editTypeID=_editTypeID;
@property(retain, nonatomic) NTallyModel *editModel; // @synthesize editModel=_editModel;
@property(copy, nonatomic) CDUnknownBlockType didSelectedType; // @synthesize didSelectedType=_didSelectedType;
@property(nonatomic) long long tallyType; // @synthesize tallyType=_tallyType;
- (id)getSelectedTallyTypeInfo;
@property(readonly, copy, nonatomic) NSString *typeID;
- (_Bool)updateTallyType:(id)arg1;
- (void)selectShortcutInfo:(id)arg1;
- (_Bool)updateTallyModel:(id)arg1;
- (void)tallyTypeSelectedAction:(id)arg1;
- (void)typeButtonAction:(id)arg1;
- (void)removeSelectStatus;
- (void)adjustTypeButtonIndex;
- (id)createButtonWithFrame:(long long)arg1 frame:(struct CGRect)arg2 title:(id)arg3 normalImageName:(id)arg4 selectImageName:(id)arg5 isLocalImage:(_Bool)arg6;
- (void)layoutTallyTypeList;
- (id)controller;
- (void)goTallyTypeAction;
- (void)tallytypeedite:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

