//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class TallyLedgerInfo, UIButton, UIImageView, UILabel, UIView;

@interface TallyLedgerListCollectionCell : UICollectionViewCell
{
    _Bool _isEditing;
    UIView *_maskConView;
    UIView *_conView;
    UIView *_bgView;
    UIImageView *_iconBigImgView;
    UIImageView *_iconImgView;
    UILabel *_titleLab;
    UIView *_membersView;
    UIImageView *_membersIconImgView;
    UILabel *_membersLab;
    UIButton *_deleteBtn;
    TallyLedgerInfo *_model;
    CDUnknownBlockType _deleteBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType deleteBlock; // @synthesize deleteBlock=_deleteBlock;
@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(retain, nonatomic) TallyLedgerInfo *model; // @synthesize model=_model;
@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) UILabel *membersLab; // @synthesize membersLab=_membersLab;
@property(retain, nonatomic) UIImageView *membersIconImgView; // @synthesize membersIconImgView=_membersIconImgView;
@property(retain, nonatomic) UIView *membersView; // @synthesize membersView=_membersView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIImageView *iconImgView; // @synthesize iconImgView=_iconImgView;
@property(retain, nonatomic) UIImageView *iconBigImgView; // @synthesize iconBigImgView=_iconBigImgView;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) UIView *conView; // @synthesize conView=_conView;
@property(retain, nonatomic) UIView *maskConView; // @synthesize maskConView=_maskConView;
- (void)deleteAction;
- (void)reloadData;
- (void)clearData;
- (void)setHighlighted:(_Bool)arg1;
- (void)setupViews;

@end

