//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableArray, NSMutableSet, NSString, TallyLedgerCategoryController, TallyLedgerCategoryItemButton, TallyLedgerModel, UIButton;

@interface TallyLedgerCategoryScrollView : UIScrollView <UIScrollViewDelegate>
{
    NSMutableSet *_resuseSet;
    NSMutableSet *_visibleSet;
    NSMutableArray *_typeArray;
    TallyLedgerCategoryItemButton *_addBtn;
    _Bool _hideSettingBtn;
    TallyLedgerCategoryController *_controller;
    long long _tallyType;
    TallyLedgerModel *_editModel;
    NSString *_editTypeID;
    UIButton *_lastSelectedBtn;
    NSString *_removecid;
    long long _selectcid;
    CDUnknownBlockType _didSelectedType;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType didSelectedType; // @synthesize didSelectedType=_didSelectedType;
@property(nonatomic) long long selectcid; // @synthesize selectcid=_selectcid;
@property(copy, nonatomic) NSString *removecid; // @synthesize removecid=_removecid;
@property(nonatomic) _Bool hideSettingBtn; // @synthesize hideSettingBtn=_hideSettingBtn;
@property(retain, nonatomic) UIButton *lastSelectedBtn; // @synthesize lastSelectedBtn=_lastSelectedBtn;
@property(copy, nonatomic) NSString *editTypeID; // @synthesize editTypeID=_editTypeID;
@property(retain, nonatomic) TallyLedgerModel *editModel; // @synthesize editModel=_editModel;
@property(nonatomic) long long tallyType; // @synthesize tallyType=_tallyType;
@property(nonatomic) __weak TallyLedgerCategoryController *controller; // @synthesize controller=_controller;
- (void)goTallyTypeAction;
- (id)getSelectedTallyTypeInfo;
@property(readonly, copy, nonatomic) NSString *typeID;
- (_Bool)updateTallyType:(id)arg1;
- (void)selectShortcutInfo:(id)arg1;
- (_Bool)updateTallyModel:(id)arg1;
- (void)tallyTypeSelectedAction:(id)arg1;
- (void)categoryItemBtnAction:(id)arg1;
- (void)removeSelectStatus;
- (void)adjustTypeButtonIndex;
- (id)createButtonWithFrame:(struct CGRect)arg1 cid:(long long)arg2 title:(id)arg3 normalImageName:(id)arg4 selectImageName:(id)arg5 isLocalImage:(_Bool)arg6;
- (void)layoutTallyTypeList;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

