//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TallyLedgerViewController.h"

@class AdjustButton, NSPredicate, NSString, TallyLedgerTallyChooseView, TallyLedgerTallyMemberDetailTableView;

@interface TallyLedgerTallyMemberDetailViewController : TallyLedgerViewController
{
    AdjustButton *_currentBtn;
    TallyLedgerTallyChooseView *_chooseView;
    TallyLedgerTallyMemberDetailTableView *_tableView;
    NSPredicate *_datePredicate;
    NSString *_dateShowString;
    NSString *_uidString;
    long long _tallyType;
    long long _sortType;
    NSString *_cID;
    NSString *_typeName;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *typeName; // @synthesize typeName=_typeName;
@property(retain, nonatomic) NSString *cID; // @synthesize cID=_cID;
@property(nonatomic) long long sortType; // @synthesize sortType=_sortType;
@property(nonatomic) long long tallyType; // @synthesize tallyType=_tallyType;
@property(nonatomic) NSString *uidString; // @synthesize uidString=_uidString;
@property(retain, nonatomic) NSString *dateShowString; // @synthesize dateShowString=_dateShowString;
@property(retain, nonatomic) NSPredicate *datePredicate; // @synthesize datePredicate=_datePredicate;
- (void)searchData;
- (void)btnClick:(id)arg1;
- (void)setupSegmentView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

