//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class FCXPieChartView, NSMutableArray, NSString, SKThemeSettingItem, UIButton, UILabel, UIView, UIViewController;

@interface TallyLabelChartHeaderView : UITableViewHeaderFooterView
{
    _Bool _hasVIP;
    _Bool _hasMore;
    _Bool _moreExpended;
    UIViewController *_controller;
    SKThemeSettingItem *_curThemeItem;
    NSString *_date;
    CDUnknownBlockType _moreExpendBlock;
    CDUnknownBlockType _vipBlock;
    UIButton *_moreBtn;
    UILabel *_titleLab;
    UIView *_vipAlertView;
    FCXPieChartView *_pieView;
    long long _dateType;
    long long _tallyType;
    NSMutableArray *_data;
    NSMutableArray *_defData;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *defData; // @synthesize defData=_defData;
@property(retain, nonatomic) NSMutableArray *data; // @synthesize data=_data;
@property(nonatomic) long long tallyType; // @synthesize tallyType=_tallyType;
@property(nonatomic) long long dateType; // @synthesize dateType=_dateType;
@property(retain, nonatomic) FCXPieChartView *pieView; // @synthesize pieView=_pieView;
@property(retain, nonatomic) UIView *vipAlertView; // @synthesize vipAlertView=_vipAlertView;
@property(retain, nonatomic) UILabel *titleLab; // @synthesize titleLab=_titleLab;
@property(retain, nonatomic) UIButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(copy, nonatomic) CDUnknownBlockType vipBlock; // @synthesize vipBlock=_vipBlock;
@property(copy, nonatomic) CDUnknownBlockType moreExpendBlock; // @synthesize moreExpendBlock=_moreExpendBlock;
@property(nonatomic) _Bool moreExpended; // @synthesize moreExpended=_moreExpended;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(nonatomic) _Bool hasVIP; // @synthesize hasVIP=_hasVIP;
@property(copy, nonatomic) NSString *date; // @synthesize date=_date;
@property(retain, nonatomic) SKThemeSettingItem *curThemeItem; // @synthesize curThemeItem=_curThemeItem;
@property(nonatomic) __weak UIViewController *controller; // @synthesize controller=_controller;
- (void)reloadData:(id)arg1 dateType:(long long)arg2 tallyType:(long long)arg3;
- (void)helpAction;
- (void)clickPieView;
- (void)refreshPieView;
- (void)clickVIPAction;
- (void)refreshVIPAlertView;
- (void)refreshTitleLab;
- (void)moreBtnAction;
- (void)refreshMoreBtn;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

