//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TallyLedgerViewController.h"

@class TallyLedgerSettingsDataSource, TallyLedgerSettingsHandleEvent, TallyLedgerSettingsViewManager;

@interface TallyLedgerSettingsController : TallyLedgerViewController
{
    TallyLedgerSettingsDataSource *_dataSource;
    TallyLedgerSettingsViewManager *_viewManager;
    TallyLedgerSettingsHandleEvent *_handleEvent;
}

- (void).cxx_destruct;
@property(retain, nonatomic) TallyLedgerSettingsHandleEvent *handleEvent; // @synthesize handleEvent=_handleEvent;
@property(retain, nonatomic) TallyLedgerSettingsViewManager *viewManager; // @synthesize viewManager=_viewManager;
@property(retain, nonatomic) TallyLedgerSettingsDataSource *dataSource; // @synthesize dataSource=_dataSource;
- (void)responseNotification:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

@end

