//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSIndexPath, NSString, SKLoadFailedView, TallyLedgerListCollectionViewFlowLayout, TallyLedgerListController, TallyLedgerListDataSource, TallyLedgerListHandleEvent, TallyLedgerSettingsHandleEvent, UIButton, UICollectionView, UILongPressGestureRecognizer, UIView;

@interface TallyLedgerListViewManager : NSObject <UICollectionViewDelegate, UICollectionViewDataSource, UIGestureRecognizerDelegate>
{
    TallyLedgerListController *_controller;
    TallyLedgerListDataSource *_dataSource;
    TallyLedgerListHandleEvent *_handleEvent;
    UIButton *_backBtn;
    UIButton *_setBtn;
    UIView *_lineView;
    UICollectionView *_listCollection;
    UIButton *_bottomAddBtn;
    UIView *_bottomSortBtnView;
    SKLoadFailedView *_loadNoDataView;
    double _itemLeft;
    double _itemRight;
    double _itemHSpace;
    double _itemVSpace;
    UILongPressGestureRecognizer *_longGesture;
    TallyLedgerSettingsHandleEvent *_settingsHandle;
    TallyLedgerListCollectionViewFlowLayout *_flowLayout;
    NSIndexPath *_moveIndexPath;
    struct CGSize _itemSize;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSIndexPath *moveIndexPath; // @synthesize moveIndexPath=_moveIndexPath;
@property(retain, nonatomic) TallyLedgerListCollectionViewFlowLayout *flowLayout; // @synthesize flowLayout=_flowLayout;
@property(retain, nonatomic) TallyLedgerSettingsHandleEvent *settingsHandle; // @synthesize settingsHandle=_settingsHandle;
@property(retain, nonatomic) UILongPressGestureRecognizer *longGesture; // @synthesize longGesture=_longGesture;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
@property(nonatomic) double itemVSpace; // @synthesize itemVSpace=_itemVSpace;
@property(nonatomic) double itemHSpace; // @synthesize itemHSpace=_itemHSpace;
@property(nonatomic) double itemRight; // @synthesize itemRight=_itemRight;
@property(nonatomic) double itemLeft; // @synthesize itemLeft=_itemLeft;
@property(retain, nonatomic) SKLoadFailedView *loadNoDataView; // @synthesize loadNoDataView=_loadNoDataView;
@property(retain, nonatomic) UIView *bottomSortBtnView; // @synthesize bottomSortBtnView=_bottomSortBtnView;
@property(retain, nonatomic) UIButton *bottomAddBtn; // @synthesize bottomAddBtn=_bottomAddBtn;
@property(retain, nonatomic) UICollectionView *listCollection; // @synthesize listCollection=_listCollection;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIButton *setBtn; // @synthesize setBtn=_setBtn;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(nonatomic) __weak TallyLedgerListHandleEvent *handleEvent; // @synthesize handleEvent=_handleEvent;
@property(nonatomic) __weak TallyLedgerListDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak TallyLedgerListController *controller; // @synthesize controller=_controller;
- (void)tallytypeChanged:(id)arg1;
- (void)refreshBottomView:(_Bool)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)handlelongGesture:(id)arg1;
- (void)resetLonggesture;
- (void)addLongGesture;
- (void)deleteAction:(id)arg1;
- (void)collectionView:(id)arg1 moveItemAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)collectionView:(id)arg1 canMoveItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)bottomSortBtnTitleSubtitleString:(id)arg1 subTitle:(id)arg2 textColor:(id)arg3;
- (void)bottomAddBtnAction;
- (void)setupViews;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

