//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CBAttributedLabel, UIImageView, UILabel;

@interface TrialModelDetailTopView : UIView
{
    CBAttributedLabel *_dateLabel;
    CBAttributedLabel *_expenditureLabel;
    CBAttributedLabel *_incomeLabel;
    UIImageView *_arrowImageView;
    UIView *_verLine;
    UILabel *_upExpenditureLabel;
    UILabel *_upIncomeLabel;
    CDUnknownBlockType _trailBlock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType trailBlock; // @synthesize trailBlock=_trailBlock;
- (id)imageNameWithName:(id)arg1;
- (id)textColor;
- (void)refreshWithTheme;
- (void)gotoMonthDetail:(id)arg1;
- (void)updateDateLabelWithHighlighted:(id)arg1;
- (void)updateDateLabel:(id)arg1;
- (void)reloadDateViewWithHighlighted:(_Bool)arg1;
- (void)updateHideMoneyLabel:(id)arg1 text:(id)arg2;
- (void)updateMoneyLabel:(id)arg1 text:(id)arg2;
- (void)updateIncome:(double)arg1;
- (void)updateExpenditure:(double)arg1;
- (void)setup;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

