//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface UMCrash : NSObject
{
}

+ (void)setMaxLimitForUserException:(long long)arg1;
+ (id)getCrashVCTrack;
+ (void)setCrashVCTrack:(id)arg1;
+ (void)printNetworkLogFoProtocol;
+ (void)enableNetworkForProtocol:(_Bool)arg1;
+ (void)setAPMConfig:(id)arg1;
+ (void)_setAPMConfig:(id)arg1;
+ (void)configANRWithSendBeatInterval:(float)arg1 checkBeatInterval:(float)arg2 toleranceBeatMissingCount:(long long)arg3;
+ (void)enablePage:(_Bool)arg1;
+ (void)enableH5:(_Bool)arg1;
+ (void)enableNetwork:(_Bool)arg1;
+ (void)enableOOM:(_Bool)arg1;
+ (void)enableMem:(_Bool)arg1;
+ (void)enableLaunch:(_Bool)arg1;
+ (void)enableBlock:(_Bool)arg1;
+ (void)enableCrashAndBlock:(_Bool)arg1;
+ (void)useIntlServices:(_Bool)arg1;
+ (void)handleUMAPMReportExceptionNotification:(id)arg1;
+ (void)handleAPMOOMSamplingNotification:(id)arg1;
+ (void)handleAPMCrashSamplingNotification:(id)arg1;
+ (void)handleAPMNetworkSamplingNotification:(id)arg1;
+ (void)handleAPMInnerConfigNotification:(id)arg1;
+ (void)processAPMMemWithInnerConfig:(_Bool)arg1;
+ (void)processAPMNetworkWithInnerConfig:(_Bool)arg1;
+ (void)handleAPMLaunchConfigNotification:(id)arg1;
+ (void)handleAPMANRConfigNotification:(id)arg1;
+ (id)UMAPMFlag;
+ (void)removeUMAPMFlag:(id)arg1;
+ (void)addUMAPMFlag:(id)arg1 objValue:(id)arg2;
+ (void)addUMAPMFlag:(id)arg1 value:(long long)arg2;
+ (id)UMAPMFlagDic;
+ (void)setAppVersion:(id)arg1 buildVersion:(id)arg2;
+ (void)setBuildData:(id)arg1;
+ (void)setAppVersion:(id)arg1;
+ (id)buildVersion;
+ (id)shortVersion;
+ (id)infoDictionary;
+ (void)reportExceptionWithName:(id)arg1 reason:(id)arg2 stackTrace:(id)arg3 terminateProgram:(_Bool)arg4;
+ (void)sendAllReports;
+ (void)enableDebugLog:(_Bool)arg1;
+ (void)setCrashUerInfo:(id)arg1;
+ (void)initUMCrash:(id)arg1 channel:(id)arg2;
+ (void)setCrashEnable:(_Bool)arg1;
+ (void)doSetCrashEnable:(_Bool)arg1;
+ (id)getVersion;

@end

