//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface UMNativePageFile : NSObject
{
}

+ (void)sendNativePage:(id)arg1;
+ (void)_sendNativePage:(id)arg1;
+ (void)sendTempNativePageFilesWithUmid:(id)arg1;
+ (void)saveTempNativePageDic:(id)arg1;
+ (void)generateTempNativePageFile:(id)arg1;

@end

