//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface UMShareLink : NSObject
{
}

+ (void)trackcode:(id)arg1 url:(id)arg2 umid:(id)arg3 uid:(id)arg4 userInfo:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
+ (_Bool)checkShareLinkValueStr:(id)arg1;
+ (_Bool)checkShareLinkKeyStr:(id)arg1;

@end

