//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSString, UIButton, UIImageView, UILabel, UIScrollView, UIView;

@interface VIPBuyPopupViewController : UIViewController <UIScrollViewDelegate>
{
    NSArray *_rightarrayTemp;
    UIView *_whiteView;
    UIView *_priceView;
    UIScrollView *_priceScrollView;
    UILabel *_pricedetaildesc;
    UIView *_bottomView;
    UIButton *_abbuyButton;
    UIImageView *_balanceView;
    long long _priceindex;
    NSString *_enterSourceString;
    NSArray *_vipArray;
    CDUnknownBlockType _paymentSuccessHandle;
    NSString *_eventID;
    NSString *_paymentEventSource;
    long long _showindex;
}

- (void).cxx_destruct;
@property(nonatomic) long long showindex; // @synthesize showindex=_showindex;
@property(copy, nonatomic) NSString *paymentEventSource; // @synthesize paymentEventSource=_paymentEventSource;
@property(copy, nonatomic) NSString *eventID; // @synthesize eventID=_eventID;
@property(copy, nonatomic) CDUnknownBlockType paymentSuccessHandle; // @synthesize paymentSuccessHandle=_paymentSuccessHandle;
@property(retain, nonatomic) NSArray *vipArray; // @synthesize vipArray=_vipArray;
- (void)ABbuyVIP:(id)arg1;
- (void)requestVIPModel;
- (void)abPopupClickBuyVIP;
- (void)adjustBuyButton:(long long)arg1;
- (void)agreementAction:(id)arg1;
- (void)setContentBuyBtn;
- (void)priceClick:(id)arg1;
- (void)setContentPriceView:(double)arg1;
- (void)setupUI;
- (void)closeClick;
- (void)viewWillAppear:(_Bool)arg1;
- (void)showup;
- (void)buyVIPSuccess;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

