//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WCWealthClassBaseViewController.h"

@class NSMutableDictionary, UIImageView;

@interface WCCertificateViewController : WCWealthClassBaseViewController
{
    long long _course_id;
    NSMutableDictionary *_dataDic;
    UIImageView *_shareBgView;
    double _transScale;
}

- (void).cxx_destruct;
@property(nonatomic) double transScale; // @synthesize transScale=_transScale;
@property(retain, nonatomic) UIImageView *shareBgView; // @synthesize shareBgView=_shareBgView;
@property(retain, nonatomic) NSMutableDictionary *dataDic; // @synthesize dataDic=_dataDic;
@property(nonatomic) long long course_id; // @synthesize course_id=_course_id;
- (void)requestData;
- (void)setupUI;
- (void)viewDidLoad;

@end

