//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UILabel, UIView, WCCourseStep;

@interface WCCourseCalendarTableViewCell : UITableViewCell
{
    UIView *_whitebg;
    UILabel *_stepLabel;
    UILabel *_courseLabel;
    UIView *_lineView;
    WCCourseStep *_model;
}

+ (double)getCellHeight:(id)arg1;
+ (void)initialSizeLabel;
- (void).cxx_destruct;
@property(copy, nonatomic) WCCourseStep *model; // @synthesize model=_model;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

