//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WCCourseModel : NSObject
{
    _Bool _is_buy;
    _Bool _is_plus;
    NSString *_course_name;
    NSString *_course_img;
    NSString *_course_desc;
    NSString *_origin_price;
    NSString *_sale_price;
    NSString *_course_id;
    NSString *_chapter_num;
    long long _plus_type;
}

+ (id)parseFromdic:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) long long plus_type; // @synthesize plus_type=_plus_type;
@property(retain, nonatomic) NSString *chapter_num; // @synthesize chapter_num=_chapter_num;
@property(nonatomic) _Bool is_plus; // @synthesize is_plus=_is_plus;
@property(retain, nonatomic) NSString *course_id; // @synthesize course_id=_course_id;
@property(nonatomic) _Bool is_buy; // @synthesize is_buy=_is_buy;
@property(retain, nonatomic) NSString *sale_price; // @synthesize sale_price=_sale_price;
@property(retain, nonatomic) NSString *origin_price; // @synthesize origin_price=_origin_price;
@property(retain, nonatomic) NSString *course_desc; // @synthesize course_desc=_course_desc;
@property(retain, nonatomic) NSString *course_img; // @synthesize course_img=_course_img;
@property(retain, nonatomic) NSString *course_name; // @synthesize course_name=_course_name;
- (id)init;

@end

