//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSDictionary;

@interface WCHomeworkButton : UIButton
{
    _Bool _isRight;
    NSDictionary *_info;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool isRight; // @synthesize isRight=_isRight;
@property(retain, nonatomic) NSDictionary *info; // @synthesize info=_info;
- (void)layoutSubviews;

@end

