//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CAShapeLayer, UIActivityIndicatorView, UIBezierPath, UIImage;

@interface WCPlayerProgressButton : UIButton
{
    CAShapeLayer *_progressLayer;
    UIBezierPath *_bezierPath;
    UIImage *_normalImage;
    UIImage *_circleImage;
    double _indicatorWidth;
    long long _activityIndicatorViewStyle;
    double _progress;
    UIActivityIndicatorView *_indicatorView;
}

+ (id)playerButtonWithNormalImage:(id)arg1 selectedImage:(id)arg2 circleImage:(id)arg3 indicatorWidth:(double)arg4 activityIndicatorViewStyle:(long long)arg5;
- (void).cxx_destruct;
@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) double progress; // @synthesize progress=_progress;
- (void)stopAnimating;
- (void)startAnimating;
- (void)setupProgressLayer;

@end

