//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WPKThreadBlockChecker.h"

@interface WPKInternalThreadBlockChecker : WPKThreadBlockChecker
{
}

- (void)markAsMainThreadCheckingReset;
- (void)markAsMainThreadStayHealthy:(_Bool)arg1;
- (void)markAsMainThreadKeepOnBlocking;
- (void)markAsMainThreadBlockedWithInterval:(double)arg1;
- (id)initWithDelegate:(id)arg1;

@end

