//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WPKLogFile.h"

@class NSArray, NSMutableDictionary, NSString;

@interface WPKLogJSONFile : WPKLogFile
{
    NSString *_type;
    NSMutableDictionary *_contentDict;
    NSArray *_wpkSortKeys;
}

+ (id)generateJSONFileWithType:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSArray *wpkSortKeys; // @synthesize wpkSortKeys=_wpkSortKeys;
@property(retain, nonatomic) NSMutableDictionary *contentDict; // @synthesize contentDict=_contentDict;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
- (long long)writeWithImmediatelySend:(_Bool)arg1;
- (long long)write;
- (long long)send;
- (id)toString;
- (id)currentDict;
- (void)setIndexKeys:(id)arg1;
- (void)appendDict:(id)arg1;
- (id)commonInfo;
- (id)initWithType:(id)arg1;

@end

