//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WPKLogFile.h"

@class NSMutableArray, NSString;

@interface WPKLogTextFile : WPKLogFile
{
    NSString *_type;
    NSMutableArray *_sectionContents;
}

+ (id)generateTextFileWithType:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *sectionContents; // @synthesize sectionContents=_sectionContents;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (void)addText:(id)arg1;
- (void)addJSONSectionWithName:(id)arg1 linebreak:(_Bool)arg2 jsonContent:(id)arg3;
- (void)addTextSectionWithName:(id)arg1 linebreak:(_Bool)arg2 content:(id)arg3;
- (void)addKVSectionWithName:(id)arg1 linebreak:(_Bool)arg2 contentDict:(id)arg3;
- (id)genDeviceInfo;
- (id)genGlobalHead;
- (long long)writeWithImmediatelySend:(_Bool)arg1;
- (long long)write;
- (long long)send;
- (id)toString;
- (id)initWithType:(id)arg1;

@end

