//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface WPKLogFileStreamElement : NSObject
{
    NSString *_type;
    NSString *_filePath;
    double _fileCreateTime;
    long long _delayUploadSeconds;
}

- (void).cxx_destruct;
@property(nonatomic) long long delayUploadSeconds; // @synthesize delayUploadSeconds=_delayUploadSeconds;
@property(nonatomic) double fileCreateTime; // @synthesize fileCreateTime=_fileCreateTime;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
- (id)description;
- (id)init;

@end

