//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDateFormatter, NSFileHandle, NSString;

@interface WPKMobiWALogManager : NSObject
{
    unsigned int _flags;
    NSString *_uploadHost;
    NSString *_waBaseUrl;
    NSDateFormatter *_dateFormatter;
    NSString *_currentLogFileName;
    NSFileHandle *_fileHandle;
}

+ (id)aesCBCEncryptData:(id)arg1 key:(id)arg2;
+ (id)waEncrypt:(id)arg1;
+ (id)shortVersion;
+ (id)hardwareModel;
+ (id)getBasePath;
+ (id)sharedInstance;
- (void).cxx_destruct;
@property(nonatomic) unsigned int flags; // @synthesize flags=_flags;
@property(retain, nonatomic) NSFileHandle *fileHandle; // @synthesize fileHandle=_fileHandle;
@property(retain, nonatomic) NSString *currentLogFileName; // @synthesize currentLogFileName=_currentLogFileName;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) NSString *waBaseUrl; // @synthesize waBaseUrl=_waBaseUrl;
@property(retain, nonatomic) NSString *uploadHost; // @synthesize uploadHost=_uploadHost;
- (void)recordCrash:(long long)arg1 scn:(long long)arg2 cty:(long long)arg3 crashUUID:(id)arg4;
- (void)recordCrash:(long long)arg1 scn:(long long)arg2 cty:(long long)arg3;
- (void)start;
- (void)addPV;
- (void)appendInfo:(id)arg1;
- (void)uploadWAData;
- (id)reqParamsToReqURL:(id)arg1 reqParams:(id)arg2;
- (id)reqParams;
- (id)waDataToEncryptAndGzipData:(id)arg1;
- (id)fieldsToEncryptData:(id)arg1;
- (id)fieldsToString:(id)arg1;
- (id)commonFields;
- (void)createWaFileHandle;
- (void)refeshUploadUrl;
- (void)changeIntlDomainNotify:(id)arg1;
- (id)init;

@end

